### ISSUE TITLE
Please add .column_modifier() back into library

### ISSUE THREAD

**Issue by peterritter** [jtv/libpqxx#115]
Hi
I was using an older version of libpqxx on windows. This version does not seem to be compatible with postgres 10.  I have now recompiled on windows with the latest source only to discover that  the result::column_modifier() member is gone!?   I really need this function because I am creating new tables in another database based from the result set and I need to know the max size/length of string columns. 
Is there a particular reason why this member is gone? can I just paste the code from the old source? 
Thanks, Peter

**Comment by jtv** [comment]
To be honest, I'm not sure I remember!  It may have been because the documentation wasn't clear to me, so I didn't really know what to document, or why anyone would use it.  And for text fields, I don't even think size limits were actually enforced at the time!
So yes, we can bring it back.  Although I do wonder if `PQfsize` wouldn't have been a better vehicle for libpq to convey maximum size information...  Maybe something like "if it returns a negative value other than the lowest possible int, its absolute value is the maximum size."

**Comment by jtv** [comment]
I'm trying it out and `PQfmod` is giving me 0 for a `VARCHAR(10)`.  Are you sure it's the modifier you want and not the field size?

**Comment by jtv** [comment]
No joy with PQfsize either.  I'm just not sure where you can get this information now...

**Comment by jtv** [comment]
I did some digging, and it looks like this was an extension you made yourself.  You proposed it as an extension, but I never adopted it because it wasn't clear to me what PQfmod did.  I could probably have been more communicative about that.

Now, I'd be happy to add it, but as I said above, would it actually solve your problem?

**Comment by jtv** [comment]
I think this issue has reached a dead end for now.  :-(  If you don't mind I'll close it, but if you feel there's more to say, do please reopen it or start a new one!
