### ISSUE TITLE
Custom data type support.

### ISSUE THREAD

**Issue by LovePinkFloyd** [jtv/libpqxx#119]
Hi,
I have some custom data types defined like this:
create type item as(
     name text,
     supplier_id integer,
     price numeric);
creat type complex as(
     id integer,
     itemtype item,
     describe varchar);
and,i use them like this:
create table complextest (
     comp complex,
     id int);
and,i insert some data in this table,like this:
insert into complextest values(row(1,row('lee',18,20.0),'test'),200);
and,i query data like this:
![image](https://user-images.githubusercontent.com/40681026/45199896-cab26300-b2a0-11e8-8119-ac1a15b9de6d.png)
ok,when i get the data in my program with libpqxx,the value of the field named 'comp' in table 'complextest' is that string:
(1,"(lee,18,20.0)",test)
now i want operate this field like a row or convert  the string to a row (i don't want the operate the raw string),what should i do?
I tried field.as<pqxx::row>(),but it does't work! Is there any way can solve this?
Thank you！

**Comment by jtv** [comment]
Since you defined your own type, you'll have to provide your own parsing.

What you do is:
1. Define a C++ class matching your SQL type.  As an example I'll assume that you call it `mytype`.
2. Define a specialisation of the `pqxx::string_traits` template for your new class, i.e. `pqxx::string_traits<mytype>`.  Implement all the member functions that the other specialisations have in common.
3. Now, if you have the result of your query as `r`, you can parse the `comp` column into a `mytype` object using `r[0][0].as<mytype>()`.  It will call the parsing function in your `string_traits` struct.
4. You can now also use `pqxx::from_string` and `pqxx::to_string` to convert between `mytype` and its SQL representation.

**Comment by LovePinkFloyd** [comment]
Thanks! it seems a good way to do it,i would like to try it!

**Comment by jtv** [comment]
I'd love to hear how you get on, because to be honest I rarely hear from people who do this.  I'll close this ticket, and if you have any problems, feel free to open a new one.

Celebrating libpqxx's 18th birthday today.  I don't think I'd have guessed in 2000 that the library would still be alive today!

**Comment by njfox** [comment]
> 2. Define a specialisation of the pqxx::string_traits template for your new class, i.e. pqxx::string_traits<mytype>. Implement all the member functions that the other specialisations have in common.

@jtv sorry to resurrect an old thread (and for the newbie question), but can you show a very basic example of this being done? I have a class in the `models` namespace that I'm trying to automatically convert to/from the postgresql database and I've read the docs but I'm struggling to find any examples to work with. For instance, assuming the class I'm trying to support is `models::User`, what would the code look like to specialize and implement the necessary templates to be able to convert with `.as<models::User>()`?

Thanks!

**Comment by tt4g** [comment]
@njfox You must convert individual fields. It would be nice if the `User` fields were all valid values, but it is possible that values may appear that should be mapped to `NULL` . The template functions for conversion cannot determine if individual fields are nullable.

It is recommended to create a helper function to convert `User` fields to row instead of libpqxx features.

**Comment by jtv** [comment]
For examples of implementing your own field conversions, see [the conversions.hxx header](../blob/master/include/pqxx/internal/conversions.hxx).
