### ISSUE TITLE
Remove globbing from cmake build files

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#129]
Now that cmake stuff is working (yay), does it make sense to remove the globbing? The downside of globbing is that adding new files to the source won't work correctly for people using cmake as the cmake won't re-run as part of their builds. The advantage of course is not having to manage the source file lists in 2 places (the make files and the cmake files).

It is possible to factor out the source list into separate files and use them from cmake, presumably this can also be done with the make files?

Also, you could just abandon the old make files and only use cmake :-)

**Comment by egorpugin** [comment]
I'm for globbing.

**Comment by jtv** [comment]
Kirit, do you see any solution in changing _when_ the globbing happens — i.e. during the cmake step, or during the actual build?

**Comment by KayEss** [comment]
You can't change when the globbing happens. You'd have to explicitly re-run cmake one way or another when you add files. [As this SO answer points out](https://stackoverflow.com/a/18538444/115526), this is a lot less convenient for your users than it is for you. I believe (but don't know for sure) that the globbing causes more problems when you're using the cmake files to drive an IDE (many understand cmake directly, for others you can generate project files from cmake).

When I looked into this for our projects I removed all of the globbing we did have and replaced with explicit file names. It's not much more work in maintaining the build, and at least means that the cmake files explicitly state what is expected to happen.

**Comment by jtv** [comment]
Then I suppose the alternatives are: either drop the current main build system completely (which I'm not quite prepared to do at this stage), or generate the file lists in a single place and re-use it between both build systems.

We already have a simple templating script to do the latter kind of thing, although there are probably decent alternatives to doing this in custom code.

**Comment by egorpugin** [comment]
... or keep globbing.

**Comment by jtv** [comment]
Well, this probably _would_ glob, just at an earlier time in the process — I could even just check the file into revision control.

**Comment by jtv** [comment]
I'm still partial to globbing at generation time, if possible: wrte a list of source files to a simple text file, and have the CMake files depend on those files.

The contents of the files may not even matter, as long as CMake notices when it gets modified, and automatically re-generates its build files.

**Comment by JadeMatrix** [comment]
Well, that sounds like simply adding in an extra step to do what CMake already does.  Instead of having a separate sources file generated from a CMake glob (that you then edit to tell CMake there are new files), simply keep the source list for each target in the `ADD_LIBRARY()`/`ADD_EXECUTABLE()` directive.

**Comment by jtv** [comment]
Yes, the difference is that CMake will notice when the list has changed, and —as I understand it— re-generate the build files accordingly.

**Comment by JadeMatrix** [comment]
Which list are you referring to?  If you have an explicit file list in the `ADD_*` directives, and modify the list, CMake will detect a change to the configuration and reconfigure/regenerate.

**Comment by jtv** [comment]
I may be misunderstanding.  We had an issue reported the other day where somebody mistakenly believed that CMake wasn't updating — but they were actually using the native build.

But I've been given to understand that if you use globs for the source files in a CMakeLists file, and then a file is added to the directory, without any further changes, you need to run cmake again in order to get the new file incorporated into the build.  Is that incorrect?

**Comment by jtv** [comment]
Yup, that seems to work.  It's still awful because it still has the GLOB commands, but they contain the actual filenames instead of wildcard patterns.

But, I did discover a pre-existing problem along the way: the CMake build seems to rely, accidentally, on the configuration produced by the native build!  For instance, if I run "configure" for C++17 inside the source tree, and then somewhere else I run cmake off that same source tree and build, I get loads of compilation errors.

It looks to me as if the build reads the configuration headers from the source tree, not from the build tree.  It's not an issue with the native build, because it refuses to build out-of-tree when the source tree is already configured.
