### ISSUE TITLE
Windows: compilation failed because of deprecated function

### ISSUE THREAD

**Issue by Amaracs** [jtv/libpqxx#151]
Hi,

So, I am trying to compile the libpqxx 6.3 on a windows using cygwin with C++11 and I get the following errors:

_include\pqxx\prepared_statement.hxx(84): error C2416: attribute 'deprecated' cannot be applied in this context (compiling source file connection.cxx)_

In the config-public-compiler.h file I manually defined the PQXX_HAVE_DEPRECATED to 0 because as I saw it wants to use a [[deprecated]] attribute which is a C++14 attibute, but it does not help.

Do I have to do anything else to overcome this problem?

Thank you very much,
Best,
Adam

**Comment by jtv** [comment]
Setting it to 0 won't make a difference — the only thing that matters is whether it's defined at all.

But didn't the `configure` script test for support, and change the definition in that file accordingly?

**Comment by Amaracs** [comment]
You were right. I reviewed the attributes I used to run the configure script. I do not get this error anymore.

On the other hand I get the following error:
src\field.cxx(24): error C2397: conversion from 'pqxx::row::size_type' to 'long' requires a narrowing conversion

Is it because:

**Comment by jtv** [comment]
Yeah, these width issues are annoying.  There is a lot of friction between libpq's data widths and those in the standard library, and if the application accepts ridiculous sizes of various items, there could be truncation bugs or negative numbers.

In this case though, I suspect the problem is a sign difference: `pqxx::row::size_type` is `unsigned int`, so it's really only a narrowing conversion in the sense that `int` and `long` are the same width but the signed version "needs an extra bit."

**Comment by jtv** [comment]
Hopefully that last commit fixed it.
