### ISSUE TITLE
Support string_view arguments for the exec_prepared* functions

### ISSUE THREAD

**Issue by Eelis** [jtv/libpqxx#154]
Right now I'm getting:

    /usr/include/pqxx/internal/statement_parameters.hxx:197:36: error: 'is_null' is not a member of 'pqxx::string_traits<std::basic_string_view<char> >'

**Comment by jtv** [comment]
This gets a little easier once libpqxx requires C++17 (which is planned for the next major release, 7.0).  I think I'll also need to add `string_view` support to the string conversions, which could make a big difference to performance.

But getting this right may break compatibility with people's custom string conversions.  For now, you could try enabling support locally by specialising `pqxx::string_traits<std::string_view>`.  Should be something like:

`namespace pqxx
{
template<> struct string_traits<std::string_view>
{
  static constexpr const char *name() { return "string_view"; }
  static constexpr bool has_null() noexcept { return true; }
  static bool is_null(std::string_view Obj) { return Obj.data() == nullptr; }
  static std::string_view null() { return std::string_view(); }
  static void from_string(const char Str[], string_view &Obj) { return std::string_view(Str); }
  static std::string to_string(std::string_view Obj)
  {
    return (Obj.data() == nullptr) ? std::string_view() : std::string_view(Obj.data(), Obj.size());
  }
};
}
`

Put this (or include it) in your code before you make your call.

That's a quick approximation; it may have bugs or typos.  But it should implement string conversions so libpqxx can convert string views to/from strings.  Not very efficiently, but that's for a major release.

**Comment by Eelis** [comment]
Ah, I didn't realize C++17 support was planned for the next major release. Sounds great, looking forward to it!

**Comment by jtv** [comment]
The bad news is, I can't overload functions to accept _either_ `std::string` _or_ `std::string_view` — because the overload will then be ambiguous if you pass a string constant.

Some ideas for dealing with this:
 * Also accept `const char[]` — maybe with an added length.  I'd want this in a lot of places, so it's a lot of extra functions.  Not attractive.  I've prototyped it and there were additional ambiguities in overloading.
 * Add the `string_traits` for `std::string_view`, so you can pass a string view in just this one place.  Neither efficient nor very complete.
 * Wait until 7.0, which requires C++17, and then use `std::string_view` for all string parameters which don't get stored.  It needs a change to the string conversion API: it should accept `string_view` not `string`.  Maybe for string parameters which _do_ get stored it would be better to accept an lvalue reference instead of the traditional const reference.

That last one is my preference at this point.

**Comment by JadeMatrix** [comment]
@jtv You can introduce a meta-`string_traits` like the one I create for optional-likes that should accept both `std::string` and `std::string_view` — would that help?  If you like I could whip up a quick PR.

**Comment by jtv** [comment]
@JadeMatrix it may help to play with it a bit...  I imagine there's a risk of incompatibility for people who wrote their own string conversions, or of some things becoming less efficient instead of more efficient.

**Comment by jtv** [comment]
By the way, if we're going to have `string_view` support, I suppose the new proper way of taking string parameters is to take `string_view` for strings whose lifetime is limited to the call, and for cases where the string is copied, alternative overloads of `const string &` and `string &&`...

**Comment by KayEss** [comment]
In most cases where you're going to hold on to a copy of the string don't do the two overloads, but just take a `string` by value and then move it to where you want it. The one case where you do want the two overloads is where you are returning the string (so you can alter the return types).

**Comment by jtv** [comment]
Thanks, @KayEss.  It'll be a bit of a struggle to suppress instincts acquired and honed over decades, but I like the simplicity.  It sounds like a better palette of string-passing options than we've had in the past.

**Comment by Eelis** [comment]
There's also std::byte, and we'll probably also get char8_t and corresponding specializations of std::string_view and std::basic_string. And I guess at some point we'll also get std::array_view.

And a library like libpqxx should probably support all of these... Palette overload! :)

**Comment by jtv** [comment]
We may have to templatise a bunch of functions if we want to deal with all of that.

By the way, I like to be cautious when it comes to supporting string conversions for character types.  For `char` there's the implementation-defined signedness, of course, but also I think the intent is often ambiguous: did you mean to convert this character as a character, or as a number?

**Comment by jtv** [comment]
Quick update on use of `string_view` and progress towards 7.0...  In many cases it's actually not suitable because the strings get passed on to libpq...  which expects zero-terminated C-style strings.  There's no guarantee of a terminating zero at the end of a `string_view`, so I'd have to copy the whole thing into a buffer anyway!

So, I introduced a utility class called `zview` which is really just a `string_view` but with the convention that there has to be a terminating zero.  It's not fully compatible with `string_view` but I hope it helps.

**Comment by Eelis** [comment]
Hmm, interesting! I guess this is another argument for the pgasio approach, since it will not have this problem at all. It will be able to provide idiomatic C++ interfaces using idiomatic C++ types with no performance penalty.

**Comment by KayEss** [comment]
I guess nobody knows what idiomatic coroutine based code will look like yet, but I should at least make sure that pgasio has proper `string_view` support :-)

**Comment by jtv** [comment]
Once every so often I look at re-implementing it all _without_ libpq, but shrink back from the task.  SSL, authentication protocols, networking code...  Just too much stuff that will need maintenance.  :(

**Comment by Eelis** [comment]
Yeah, totally understandable. The task is probably so big that it would need corporate funding or some sort of crowdfunding.

**Comment by jtv** [comment]
Yeah.  So far, tragically, no corporate funding.  But if you know an interested corporation, do let me know.  :-)
