### ISSUE TITLE
Enable asynchronously sending prepared statements

### ISSUE THREAD

**Issue by Eelis** [jtv/libpqxx#164]
I grepped the libpqxx source for `PQsendQueryPrepared` to find out how its functionality is exposed, but found nothing. :(

**Comment by jtv** [comment]
That's right, it's not exposed.  It would be possible to add it to `pqxx::pipeline`...  It's a bit of work, but I guess the payoff is that you don't need to deal with quoting and escaping.  Certainly easier since C++11.

_However._  If you're doing this for performance, bear in mind that prepared statements are often _slower_ than regular queries.  That's because the database has to come up with a generic plan for the query, without knowing the parameter values.  So chances are you'll get a very risk-averse, slow-but-sure query plan.

Prepared statements are probably more useful for very fast queries where _parsing the SQL_ is a major cost.  But in those cases, I would guess (but only guess) that the overhead of working asynchronously will defeat the advantage of preparing the statement.

**Comment by Eelis** [comment]
Hmm, I see `PGsendQueryParams` is not used/exposed by libpqxx either.

Yes, I'm interested in performance, and want to benchmark the various ways of executing my application's queries, but it's hard when libpqxx only exposes a fraction of the available options.

(Hence, for my application I'm now seriously considering just ditching libpqxx and using libpq directly.)

**Comment by jtv** [comment]
Then it does sound as if libpq may be the way for you.  If nothing else, you'll want to measure the overhead so you can make good tradeoffs between performance and ease of development.  The overhead may be in places that actually affect your application, or conversely, features like `pqxx::stream_to` or `pqxx::pipeline` may give you speedups that would take too much work to develop on top of libpq directly.

There are plans for reducing the overhead in libpqxx once we go to C++17 as a baseline, but that's with 7.0.  You'll then be able to avoid a lot of string allocation.

**Comment by Eelis** [comment]
That makes a lot of sense, thanks. :)

**Comment by jtv** [comment]
No worries, and hope to see you back someday.  :-)  Mind if I close this one then?

**Comment by Eelis** [comment]
Sure, done.

**Comment by Eelis** [comment]
After looking some more, I've now actually come to the view that a C++ PostgreSQL client library should ideally not be based on libpq at all, but should instead be founded on a direct ASIO-based implementation of the frontend-backend protocol.

libpq is just a shabby C implementation of a network client. Implementing the network protocol directly and exposing an ASIO-based interface would be far more convenient and flexible (and likely efficient), *especially* for asynchronous applications. :)

**Comment by KayEss** [comment]
Then you might be interested in looking at [pgasio](https://github.com/KayEss/pgasio). The current implementation handles the first part of the protocol -- sending text commends to the server and getting recordsets etc. back. Now that coroutines are in C++20 hopefully we'll get a gcc implementation and the project can move forwards again.

**Comment by Eelis** [comment]
@KayEss: Ah nice, thanks for the link! That looks exactly like what I had in mind.

**Comment by jtv** [comment]
@Eelis, I was going to recommend @KayEss' pgasio, but he beat me to it.  :-)

The problem is of course that libpq just takes care of some details that I'd prefer not to duplicate, such as authentication and SSL.  In libpqxx I've got to support all that stuff, whereas a more specialised library such as pgasio can simply leave them out.  So one thing I've been considering (after seeing pgasio) is, in the long run, using libpq to set up a connection, but then hijacking the file handle and doing all the rest myself.

**Comment by Eelis** [comment]
@jtv: Hmm, those are good points.
Using libpq to only make the connection sounds like a neat compromise, I hope that approach turns out to be viable. :)

**Comment by jtv** [comment]
My overarching plan for libpqxx is to rewire everything for greater performance:
 * Use `std::string_view` instead of `std::string` where possible, especially in string conversion.
 * Support binary data transfers, using a separate set of string conversions.
 * When converting data to a string in particular, accept callbacks as an alternative to copying strings around.  The callback takes a `string_view`.

To keep the callbacks for string conversions convenient and backwards-compatible, I'm thinking "the default is a callback that converts to a string, and the string conversion returns whatever your callback returns."  So if you wanted to print a field, for instance, you might say something like `pqxx::to_string(x, [&out](std::string_view s){ out << s; });`

The callbacks can help in several ways:
1. You may no longer need the output copied into a `string`.  The string conversion can construct it in a buffer on the stack, and just deallocate it after your callback has executed.
2. If you do need your data copied into a short-lived string, you can re-use the same string object across loop iteration so you don't need to keep allocating buffers.
3. You might want to co-allocate a bunch of items that you want to convert to strings, so that you need fewer allocations and deallocations.

**Comment by jtv** [comment]
Oh, I have not addressed asio at all.  Compilers do not seem to be ready for it yet, and I haven't put much thought into it recently.

All we have for now is `pqxx::pipeline`, which is sort of a "beginners' asio."  It was conceived before C++ coroutines, as a compromise to let you hide _some_ latency without adding too much complexity to your application.  It's not an all-out performance play, but more of a safe compromise.  It does, however, help you save a few network roundtrips by sending multiple pending queries at once.  It might be fun to add a nonblocking is-my-query-done-yet check.  Of course there's probably a lot more string copying in there than is strictly necessary.

**Comment by jonesmz** [comment]
Asio with either Boost::Asio or the Networking TS would be perfectly acceptable. Coroutines aren't needed to support real Asio :-)

**Comment by jtv** [comment]
You can do asio without coroutines, but the next-best alternative that I'm aware of is callbacks.  I don't like those much from a manageability standpoint.

**Comment by KayEss** [comment]
Totally with Jeroen on that one: friends don't let friends write callbacks :-)
