### ISSUE TITLE
make check error test49

### ISSUE THREAD

**Issue by Fornax301** [jtv/libpqxx#173]
Hi, Jeroen
I'm a student and recently I start learning database by using PostgreSQL with Mac. Both sql and shell are new to me. I'm not sure whether I have the right settings while installing the psql and libpqxx. I followed these steps and some errors generated during the make check process. 
```
$ export PATH=/Library/PostgreSQL/11/bin/:$PATH
$ ./configure
$ make PGHOST=localhost PGPORT=5432 PGUSER=postgres PGPASSWORD=123456 PGDATABASE=postgres check

[...]
g++ -std=c++11 -DHAVE_CONFIG_H   -I../include -I../include   -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT test49.o -MD -MP -MF .deps/test49.Tpo -c -o test49.o test49.cxx
test49.cxx:69:46: error: use of undeclared identifier 'bind'
      Greater = count_if(R.begin(), R.end(), bind(Cmp(Key), _1, T)),
                                             ^
test49.cxx:70:46: error: use of undeclared identifier 'bind'
      Smaller = count_if(R.begin(), R.end(), bind(Cmp(Key), T, _1));
                                             ^
2 errors generated.
make[3]: *** [test49.o] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

It seems that no one else has ran into this problem and I'm really confused. 
Please tell me if I didn't describe the problem clearly somewhere. Thanks.

**Comment by JadeMatrix** [comment]
Do you include `<functional>` from the standard library?  That's where `bind()` is declared (I assume you have a `using namespace std;` in scope).

**Comment by Fornax301** [comment]
Now I pass almost all the test but something wrong with the test93.
```
/bin/sh: line 1:  3855 Segmentation fault: 11  ${dir}$tst
FAIL: runner
====================================
1 of 1 test failed
Please report to Jeroen T. Vermeulen
====================================
make[3]: *** [check-TESTS] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```
I read another issue about this problem and tried several solutions but didn't work.
If I just ignore it and continue make install, then simply try the example program
```
$ g++ test.cpp -std=c++11 -L/usr/local/include/pqxx -lpqxx -lpq
$ ./a.out

Connected to postgres
Found 1employees:
a
Doubling all employees' salaries...
Making changes definite: OK.
```
seems everything is ok.
I'm not sure whether there is any potential problem. (hope not)
Thanks ever so much for your help.

**Comment by jtv** [comment]
The first problem (the compiler error) looks as if I simply should have typed `std::bind` instead of just `bind`, and for some reason my versions of the compilers I use never complained about it.  My latest commit should fix that one — although if it doesn't, or you run into similar problems elsewhere, please let me know.

The next one, the segfault while running the tests, lkooks like it could be a duplicate of #172.  I'm still wracking my brain over that one.

**Comment by jtv** [comment]
By the way, what version of gcc are you using, and what's your locale setting?  I'm trying to reproduce the problem so I can debug it locally.

**Comment by Fornax301** [comment]
Another similar problem in test_87, I included <sys/select.h> directly
`#include <sys/select.h>`
`using namespace std;`

And my c/c++ compiler is clang. I heard that clang sometimes gives inexplicable warnings and errors, so should I keep using clang or change to gcc?
```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
```
My psql version is 11.2, locale set to default.

**Comment by jtv** [comment]
Ah!  Somehow I thought you were running gcc.  I do test with clang, just not as often as with gcc.  And guess what?  I get the error when I use clang _and_ enable optimisation.

**Comment by Fornax301** [comment]
Yeah! For me, it's hard to tell who's better. I use it just because someone told me it's faster and uses less memory. Maybe I will have my own choice after further study. : ) 
And no more question here, thanks for your help!

**Comment by jtv** [comment]
Thanks for reporting it.  I like clang, and the competition really made gcc up its game!

One important difference is the interesting way in which clang handles undefined behaviour...  Treats it more or less as a special value, which the compiler can use for optimisation.  "This code path uses an undefined value, therefore the optimiser can assume that this path is never taken."  There's an interesting talk about it on YouTube somewhere, from CppCon I think, one or two years ago.  It explains why clang might actually have exposed some subtle bug.

**Comment by JadeMatrix** [comment]
Clang isn't the only one, personally I've experienced GCC (6 fwiw) not throwing certain warnings (e.g. deprecation) for certain files when no optimization flag is used.

**Comment by jtv** [comment]
Okay, found and fixed the problem at last.  Or perhaps I should say, I half worked around it and half just documented it.  There was a completely different problem..

A libpqxx connection installs a libpq "notice processor" callback on its underlying libpq connection, for accepting error/warning messages and handing them to the application's error handlers.  When an error occurs in a libpq call, it will invoke this notice processor.  Great.

But it turns out libpq can still call the connection's notice processor even after the connection has been closed!  Each libpq result keeps a copy of its connection's notice processor, and this doesn't change when that connection is closed.  And as it happens, our notice processor would look up the connection's list of error handlers... a list which at that time no longer exists.

I solved it by installing that notice processor only when needed.  This way, at least you don't need to worry about it as long as you don't install an error handler.

**Comment by jtv** [comment]
@JadeMatrix back in the day when I used the SAS C compiler, you'd often get extra warnings out of the optimiser's code analysis.  Often enough I'd enable optimisation just for those.  I see less of it now, and so I mostly test without optimisation.  Time to reconsider that...
