### ISSUE TITLE
Make to/from streams more flexible

### ISSUE THREAD

**Issue by qw42** [jtv/libpqxx#180]
I have several suggestions.

1. Streams use tuple for input/output. This prevents setting number of columns at run-time.
   I wish the following was possible

```
vector<string> row(n); // n is set at run-time
my_stream >> row; // read n values as-is

```
2. Implement SQL transformation functions on client side, e.g. a function to extract Unix time from timestamp.

3. Allow indexing output using column names. Currently it is done using tuple indexes - not very readable.

4. Allow in place modification of table columns: read a row, modify some of the values and write it back.

**Comment by JadeMatrix** [comment]
1. I know this was removed part-way through implementation (12da59f4) but don't remember why and can't find reference to any discussion (do you @jtv ?); it should be easy to add back in.
2. While this could be possible for `TIMESTAMP`, `TIMESTAMPTZ` would require a timezone-aware date/time type not available in the standard library.  I've written `libpqxx` support for [Howard Hinnant's `date` library](https://github.com/HowardHinnant/date), which will very likely be added to the standard library in C++20.  Additionally, `date` already supports parsing & serializing date/times, so adding custom support for `TIMESTAMP` → `std::time_point<>` would interfere with any `libpxx` users' `string_traits<>` implementation that uses `date` (for example mine).  If you want I can share my code, but I would not recommend this be added directly to `libpqxx` (yet).
3. This would probably require a universal `row` type usable for both input/output, something I've mentioned to Jeroen but IIRC he and @KayEss have already discussed something similar for `libpqxx` 7.  Adding it right now would either require refactoring the whole `result`/`row` system or adding a second `row`-like type just for `stream_to`/`stream_from`.
4. `stream_to` only appends to tables, as it's a wrapper for `COPY FROM`, so there's no way for this to work.

**Comment by jtv** [comment]
We're doing parallel vectorised threads of conversation then?  Just like the old days!

1. Sorry @JadeMatrix —  I have no specific memories about why column indexing was removed...  But could it perhaps be because it relied on a post-C++11 language feature, à la C++11 structured bindings perhaps, or concepts?  If so, well, we're about to move the baseline up to C++17, so don't let me stop anyone who wants to experiment.  :-)

2. As @JadeMatrix says, _in principle_ you can add timestamp support for all of libpqxx, not just in this one place!  There are many reasons why I haven't built it into the library yet: lack of good standard C++ types for this, the sheer work of producing a good parser without  adding non-standard dependencies, the headaches of matching up C++ types with SQL types, and...  the infuriating ambiguity introduced by configurable SQL date formats.  Is 01/02/2019 a date in January or in February?  Depends on the settings, and by the time you're doing this conversion, you're in no position to query the setting.  :-(

3. Details on `row` types escape me, to be honest.  @KayEss would be more conversant with any C++ standard-library classes which may help us here.  But yes, it'd be good to factor our all  that commonality.  One step at a time, I think.

4. I like the idea...  But again I concur with what's been said: it'd require a whole different facility, and I'm almost entirely certain that you'd lose much of the performance gain from using table streams.  I have worked on more flexible "on-demand result" classes based on cursors, providing either stream-like or random-access APIs, but in the end it was a lot of complexity for surprisingly little gain.  Using these things effectively often means understanding exactly what they do under the hood.  Which in turn sort of defeats the benefits of abstraction.

**Comment by KayEss** [comment]
I'm not sure I know which row class we're talking about (point 3). Can somebody give me a link to it?

**Comment by qw42** [comment]
What is the fastest way to do the following:
Given a very large table one needs to scan all row and modify some of the values based on processing  done on C++ side. The table is so big that even index doesn't fit into system memory. Only small fraction of rows are actually modified. The values that are modified are not indexed and not constrained, except maybe by not-null constrain.

I think in this case iterator like access might work well.

**Comment by jtv** [comment]
That does indeed sound like a case where an iterator-style interface would work well.  The hard part though is mapping the problem to the available constructs in SQL and in libpq.

I think the answer depends on such questions as: could the modifications be done completely server-side?  Is there a relatively tiny number of modifications so that  they could fit into memory?  Would it be acceptable to make the modifications outside of the transaction which reads the table?

If it's OK to make the modifications in a separate transaction, it may make sense to issue them as individual queries on a separate connection, perhaps through a `pqxx::pipeline`.  A cursor might be another solution: fetch chunk `n` of the data through a cursor, write changes, fetch the next chunk.

**Comment by jtv** [comment]
I suppose we're a little stuck with this one.  If you don't mind, I'll close the ticket.  Feel free to open a new one if anything concrete comes up.
