### ISSUE TITLE
Full CMake build rewrite

### ISSUE THREAD

**Issue by JadeMatrix** [jtv/libpqxx#181]
Back in January I played around with converting libpqxx to using CMake as the primary (well, only) build configuration.  I just finished bringing the branch up-to-date with 6.4.4: [JadeMatrix/libpqxx@modern-cmake](https://github.com/JadeMatrix/libpqxx/tree/modern-cmake).

Some notes:
* Requires a minimum of CMake 3.7 (reasonably old, current is 3.13)
* Targets for static & shared versions of libpqxx are exported for CMake users.  They are called `libpqxx::pqxx` and `libpqxx::pqxx-shared`, respectively, with an alias target called `libpqxx::pqxx-static` for completeness.
* The exported CMake package configuration does basic version checking using [CMakePackageConfigHelpers](https://cmake.org/cmake/help/v3.7/module/CMakePackageConfigHelpers.html)
* Compiler-specific configuration (e.g. `PQXX_HAVE_OPTIONAL`) is run both when libpqxx is compiled and when the user uses `FIND_PACKAGE()` in their own CMake-based project.  The definitions are split between public (only used in libpqxx headers), which are applied transiently through the exported library targets, and private (only used to compile libpqxx sources).
* A target-based find script for `libpq` is also installed to transiently link against `libpq` (the user does not have to explicitly link against it).
* `pkg-config` support is also generated & installed, including a dependency on `libpq` (again so linking against it is implicit).  As I'm not terribly familiar with `pkg-config`, this needs a second pair of eyes (but it seems pretty straightforward).
* None of the documentation or CI configuration has been updated yet.
* libpqxx tests are integrated into CTest
* Building libpqxx with CMake is set up for out-of-source build, but it is not enforced.
* **I've only tested this on macOS 10.12.6 and CentOS 7.5** but it *should* work elsewhere, with at most minor modifications

To build the branch, I'd suggest running something similar to:

```sh
mkdir -p libpqxx-cmake/{src,build,install}
cd libpqxx-cmake
git clone https://github.com/JadeMatrix/libpqxx.git src
cd src; git checkout modern-cmake
cd ../build; cmake -D CMAKE_INSTALL_PREFIX=../install/ ../src
make all test install
```

A simple `CMakeLists.txt` that can use the exported package configuration (`pqxx_cmake_test.cpp` being some small libpqxx test program in the same directory):

```cmake
FIND_PACKAGE(libpqxx 6.4.4 REQUIRED COMPONENTS pqxx)
ADD_EXECUTABLE(pqxx_cmake_test "pqxx_cmake_test.cpp")
TARGET_LINK_LIBRARIES(pqxx_cmake_test PRIVATE libpqxx::pqxx)
```

The `lib{64}/cmake/libpqxx` directory simply needs to be added to the `CMAKE_PREFIX_PATH` variable when configuring the project.  (This shouldn't be necessary when installed at the system level.)

**Comment by KayEss** [comment]
One thing that's bitten me in the past was the tests were opt out rather than opt in. Is that still the case?

Jeroen and I also made some updates to the old scripts to get the configure parts to work a bit more effectively. I can look up the commits if you want to see what we had to do.

**Comment by jtv** [comment]
One recent change was to reorder the include directories.  The old CMake setup preferred headers from the source tree over equivalents in the build tree, and so the CMake-generated configuration headers weren't taking effect.

**Comment by jtv** [comment]
By the way, @JadeMatrix your new CMake setup works on my Ubuntu 18.04  system.  (Not that I expected any different, but you can add it to your known-to-work list.)

There have been a lot of changes to the codebase over the last week or so, but for the CMake build, our custom little templating system should just generate new build configuration.  In `master` we're already working on 7.0.0, and I'm about to move the baseline to C++17!

**Comment by jtv** [comment]
...and that's done now.  Unfortunately CircleCI uses Debian Stretch systems for its build slaves, and it looks as if its `autoconf-archive` doesn't support C++17 yet.  :-/

**Comment by JadeMatrix** [comment]
@KayEss They're still opt-out, but that's just the CTest default; it's really easy to change.  Also, a lot of what the configure scripts do is already handled by CMake, but I didn't look too closely at them.  I basically replicated what the `configure-*.h` files did as far as I could tell, but using CMake targets instead of headers (which end up being hard-coded once installed).

@jtv I did include the build-before-source-tree fix, although I don't see that being too big an issue as long as libpqxx is build out-of-source (like CMake is meant to be used). This also completely replaces the CMake templating in `master` with native CMake; the idea was to completely replace all build configuration with CMake.  I didn't remove the other build files or clean up the `.gitignore` though in case I missed some configuration (of course it would be easy enough to `git revert` but it's still a bit of a pain).

I can update to `master` on this branch too, I just figured getting it up-to-date with 6.4.4 was enough merge conflict resolution for one night.  I also wanted to have a commit where the new build worked for each version since I started on it.

**Comment by jtv** [comment]
Less of the templating is a good thing, I'm sure.  :)

One thing we could do for the versioning is to release a 6.4.5 with your changes.  I don't want to make a habit out of supporting a release branch, but the changes in 7.0 are radical enough that realistically, it probably calls for one.

I'd like to keep the autoconf build around though, for things like `--enable-maintainer-mode` and `--enable-audit`, as well as compatibility with existing build chains.  CMake probably has alternatives for these things, but I'd have to learn about them first.

**Comment by moodboom** [comment]
Thanks for the move to CMake, autotools isn't fun and when I started getting this autotools error, I just now made the switch to CMake and a fresh build worked :100: without issue.

`configure: error: 
Can't find libpq-fe.h in .  Are you sure the libpq
headers are installed correctly?  They should be in the directory returned by
"pg_config --includedir" or "pkg-config libpq --cflags".
`

**Comment by JadeMatrix** [comment]
@jtv You'll need to describe what those do, I'm not familiar with autoconf and can't find much online.  From what I can tell though something like `--enable-maintainer-mode` doesn't make sense for CMake — it's designed to rebuild/reconfigure/regenerate outputs & configurations as-needed.  It works best if you set up all file generation as build-time and not commit any generated files to your VCS (something I adhere to religiously).

@moodboom There's already a CMake configuration in libpqxx — this isn't it.

**Comment by jtv** [comment]
@JadeMatrix true, what I do is a little weird.  I just wanted people to be able to configure and build straight from the repo, without having to install run autoconf etc. on their own systems.  I don't suppose there's a way of telling Git "this is a generated file," so people can opt not to see the changes there...

The `--enable-maintainer-mode` option is a custom option in my build, just like `--enable-audit`.  They turn on some custom, compiler-specific build and debug settings.  I try to compile with much stricter settings than other people do, in hopes of catching problems before they affect other people.

**Comment by JadeMatrix** [comment]
@jtv I'm not sure I understand — what does `autoconf` do other than the configure part?  CMake basically takes over and replaces `autoconf`, but also remains tightly integrated into the build files it generates so it knows when configurations have changed.

>I don't suppose there's a way of telling Git "this is a generated file,"

In my opinion, generated files should simply never be committed — their generation should be part of the build process with other things relying on their generation, and they should be ignored by VCS _a la_ `.gitignore` (for in-source builds) or placed in the build output location (for out-of-source builds).

>  I try to compile with much stricter settings than other people do

Those stricter flags (at least as well as I could remember them) are [already in this branch](https://github.com/JadeMatrix/libpqxx/blob/modern-cmake/CMakeLists.txt#L41).  Although I don't understand why you'd want to compile with different settings than other people (e.g. contributors) — which is a problem we ran into early on with my `stream_from`/`stream_to` contribution.  Much better to just standardize strict settings for everyone building libpqxx — less work for you too, as you don't have to come back with a bunch of stuff for contributors to fix that they should have been able to catch on their own.

**Comment by jtv** [comment]
Generating the configure script requires a bunch of software —automake, autoconf, libtool, probably more— which you should not need just in order to build libpqxx.  But having that script means you can build regardless of your OS, compiler, or shell.  You could be using a PowerPC Mac with a Korn-derived shell with weird ideas about syntax and a compiler I've never heard of, and you'll be able to run that script to get a build.  You'll also still be able to customise it with debug options, cross-compilations, optimisation for specialised hardware, etc.  So in CMake terms, I expect the way `configure` fits into the process is closer to that of  `CMakeLists.txt` than it is to the generated build files.

I appreciate that it's annoying for contributors for the "maintainer builds" to come back with additional warnings or errors.  I'll have to remember to let people know about maintainer mode.

That said, I very much want to avoid dictating what options other people use when compiling.  Who knows what compilers they use, on what operating systems and with what hardware options, optimisation choices,  warning policies, and audit and debug tools?

I want a good shot at fixing warnings before they hit unsuspecting users.  Without going too far out of my way, is there a better way to approximate that than to do my own builds with stricter settings than the default?  The stricter build can warn about problems in other people's environments, which may not actually affect my own.  Users should be able to ask for strict checks if and as they want them, but if they get them by default, then every new warning or error in a new compiler version will be a nuisance to users, probably unnecessarily.

**Comment by jtv** [comment]
@JadeMatrix Does Git have a good way to go over your changes and pull them into the main tree, preferably with your name on it since it's your work?  Or will it basically be a patch-and-diff job like in the old days?

I do miss bzr.  :-)

**Comment by JadeMatrix** [comment]
>Generating the configure script requires a bunch of software —automake, autoconf, libtool, probably more— which you should not need just in order to build libpqxx.

That's the advantage of CMake — all of that's built-in.

>So in CMake terms, I expect the way `configure` fits into the process is closer to that of `CMakeLists.txt` than it is to the generated build files.

Yep, that's exactly right.  You run `cmake` to generate files for your preferred build system, which on Linux & macOS defaults to `make`.  CMake comes with [these generators](https://cmake.org/cmake/help/v3.11/manual/cmake-generators.7.html) built-in.

>That said, I very much want to avoid dictating what options other people use when compiling. Who knows what compilers they use, on what operating systems and with what hardware options, optimisation choices, warning policies, and audit and debug tools?

[I've set up the warnings & optimization settings](https://github.com/JadeMatrix/libpqxx/blob/modern-cmake/CMakeLists.txt#L41) for GCC, Clang, and ICC, which use mostly the same flags for these (there are a few exceptions).  MSVC doesn't support the same wide array of flags, but I've added the ones that seem to work — although I haven't tested it so they may not be appropriate.  I do have `-Werror`/`/WX` applied too — maybe a "maintainer mode" equivalent could be added to opt-in to those?  But other than that there are no extra flags set up; it would be up to the user to pass equivalent [`-D CMAKE_CXX_FLAGS=...`](https://cmake.org/cmake/help/v3.11/variable/CMAKE_LANG_FLAGS.html) for their compiler if they so choose.

>The stricter build can warn about problems in other people's environments, which may not actually affect my own. Users should be able to ask for strict checks if and as they want them, but if they get them by default, then every new warning or error in a new compiler version will be a nuisance to users, probably unnecessarily.

I'm not sure what you mean.

>Does Git have a good way to go over your changes and pull them into the main tree, preferably with your name on it since it's your work? Or will it basically be a patch-and-diff job like in the old days?

Same here ;p
Do you mean you want all of the commits preserved on merge?  Just pull the branch into `jtv/libpqxx`?

**Comment by jtv** [comment]
I _finally_ worked up the courage to look at the details.  But with the divergence that's happened since, I just did a brute-force diff and picked out the CMake-related changes.

Do I understand correctly that the Windows build does not need `libpqxx.cxx`?

**Comment by JadeMatrix** [comment]
No, the Windows build is the *only* thing that needs `win32/libpqxx.cxx`

**Comment by KayEss** [comment]
Isabella Muerta made an offer to help out projects with CMake, so I asked her if she would look at libpqxx, and she kindly agreed: https://twitter.com/slurpsmadrips/status/1175939304058585088

Obviously there's no time line and she may never get a chance to actually look, but I'll point her at this thread so she will see the refactoring branch if/when she does get a chance.

**Comment by jtv** [comment]
Meanwhile I've moved some checks into separate files, so that the autoconf build and the CMake build can share them.

I think I'll simplify the `__cxa_demangle` checks to just check whether that function exists at all.  No point testing the full signature.  I'd prefer to do the whole check in the C++ code, without any configure step at all, but I haven't been able to figure out the SFINAE details.

**Comment by JadeMatrix** [comment]
I can take a look at updating this for v7, but I'm afraid I haven't been keeping up with the new development so I'm not as familiar with the codebase.  What I'd probably do is create a separate branch off of current master and copy-paste the CMake changes, as it's largely orthogonal to other source code.

I think it's a good idea to reduce the number of custom compile-time checks as much as possible.  In 6.4 those only effected stuff in headers, which luckily meant those checks could be run both on the builder's machine and the user's machine with different results and just work.  If any of that propagates to the compiled library it becomes a maintenance nightmare; the fewer you have the less chance of that happening.

**Comment by jtv** [comment]
I'd love an update, because clearly I got a little jumbled up when I tried to figure out the diff.  I would suggest sticking to minimal changes that we can merge individually though, so it doesn't become a big dramatic change.

**Comment by JadeMatrix** [comment]
I'll take a look this weekend, even if it just ends up being support material for Isabella.

**Comment by JadeMatrix** [comment]
@jtv Alright I got the changes manually added to a 7.0-based branch: [JadeMatrix/libpqxx@modern-cmake-7](https://github.com/JadeMatrix/libpqxx/tree/modern-cmake-7)

Disclaimers (as usual):
* Windows build hasn't been tested
* Documentation build hasn't been touched, may not work anymore
* CircleCI config hasn't been touched and *definitely* doesn't work anymore
* This still has the build & import time configuration stuff that auto-configs `PQXX_HAVE_GCC_PURE` and `PQXX_HAVE_GCC_VISIBILITY` on the user's machine
* Both static and shared libs are built, which is not proper CMake style (use of the `BUILD_SHARED_LIBS` switch is preferred)

Stuff added just in this branch:
* `PQXX_MAINTAINER_MODE` and `PQXX_ENABLE_AUDIT` CMake options; former enables `-Werror`, latter sanitization
* Shared & static `pqxx` libs build from a single [CMake `OBJECT` library](https://cmake.org/cmake/help/v3.7/command/add_library.html#object-libraries) called `_pqxx`; did this because some systems (macOS) seem to build each source once per target that uses them, and some don't.  Or maybe it's my imagination and all do.  Either way, the object library means each source builds once, as configs don't change between the two libraries.  (This can be removed if `BUILD_SHARED_LIBS` is used instead.)

I've also taken a look at @slurps-mad-rips's branch:
* Is using `${CMAKE_INSTALL_DATADIR}/cmake/libpqxx` more correct than `"${CMAKE_INSTALL_LIBDIR}/cmake/libpqxx/"` for installed CMake support files?  Granted I'm on macOS and install most stuff through Homebrew, and the projects there seem to install to both `share/` and `lib/` with the latter seeming to be more favored.
* `FILE(GLOB ... CONFIGURE_DEPENDS)` is interesting, never noticed that in the documentation.  I still prefer listing source files explicitly, as the docs still include the warning even for `CONFIGURE_DEPENDS` ¯\\\_(ツ)\_/¯

**Comment by slurps-mad-rips** [comment]
@JadeMatrix 

Regarding the change to DATADIR, it's considered that "configuration" files go into `share` under a given installation root on Linux. From the "directory hierarchy"

> The "share" word is used because what is under /usr/share is platform independent

Hence the change. It's minor however, so feel free to ignore it.

Regarding `CONFIGURE_DEPENDS`, the reason they still don't recognize it is because they're worried about some new build system becoming popular that doesn't support custom rules like Make or Ninja. Effectively, using XCode as the generator means one would have to regenerate the project. If you're concerned regarding Visual Studio, I happen to know Microsoft recommends CMake + Ninja as a combo if using CMake at all.

Also having looked at the branch, I'd recommend to keep the commands in `lowercase`, as this is what Kitware does not. Granted its all case insensitive (so, yes, you could theoretically use "sPoNgEbOb case" to call commands, but please don't), but I've found it helps with readability and also your pinky if you use a typical QWERTY layout when having to write CMake >:P

Additionally, I'd recommend to keeping with the generator expression approach to adding options. Alternatively, your `if()` for checking the compiler could be changed to an `IN_LIST` call, but that's up to you :)

If you want I could start forking off of your current changes and going from there and we can start making small PRs for each change. My diff is pretty big and honestly I would change it in hindsight a bit for readability 😅

**Comment by JadeMatrix** [comment]
@slurps-mad-rips 
I (currently don't have much of an opinion either way regarding `DATADIR` vs. `LIBDIR`.  FWIW I checked again all the packages installed via Homebrew on my system that have some form of CMake package support (sadly not that many) install it to `lib/cmake/`.  On the other hand, I did a quick `mv lib share` on package I don't have installed system-wide, and CMake found it just fine (verified in cache), so at least on macOS both will work.

Shame `GNUInstallDirs` doesn't provide a `CMAKEDIR` we all can just blindly use.

Good points on `CONFIGURE_DEPENDS`, no arguments there.  I tend to leave half-baked code and abortive design efforts lying around during early development so I'd probably find it annoying at first.  I've also seen build artifacts and other sorts of garbage (`.hg` and `.git` dirs) swooped up in globs for non-compilation purposes, but that's not terribly applicable here.

I probably picked up UPPERCASE for CMake stuff from examples early on.  I know we debated it at work and settled on uppercase as the closest we could get to consistency with built-in CMake stuff, but I don't recall the actual arguments made either way.  I tend to let autocomplete do most of it.

If I wanted to sound smart I'd say I would have used `IN_LIST` if I already had a list to use, and that I generally dislike creating single-use variables (especially with CMake scoping rules) (unless semantics require it).  Actually it's probably because that check is a copy-paste that has grown several entries from its original iteration and I never noticed.

I've already made the bulk of the changes I had in mind, so feel free to use what you want.  I'm sure I'll learn a thing or two (more than I have already).  Whether you want to PR into mine or directly into @jtv's is up to you; if I have any more ideas I'll bring them up here first and we can go from there.  *(Do note I did rather brazenly delete all the non-CMake build stuff in my branch; it's isolated to two commits that can (hopefully) be cleanly reverted though)*.

**Comment by jtv** [comment]
Sounds like going directly into my branch would be best then!  Also saves me the hateful Git cleverness of merging from another repo.  :-)

@slurps-mad-rips thanks for advising us.  I know much less about CMake than @JadeMatrix does, so I'm _way_ out of my depth.  At the moment we have several build systems side by side.  I even extracted some of the configure-time checks into C++ files so that the CMake and autoconf builds can share them.  (I hope I'll be able to move them directly into the source code in the future.)

**Comment by jtv** [comment]
The work to get the Visual Studio build going revealed some problems with the CMake setup.  Turns out I was a fool to ask for a build that could generate a shared library and a static library side by side!

On Windows, building a shared library _also_ produces a static library, which acts as "glue" between the client programme and the shared library.  And so in that case the libraries weren't really side by side.  The two static libraries were written to the same file, with one accidentally overwriting the other.  :(

So, we'll have to make the CMake config build _either_ a shared library _or_ a static library, depending on what the user wants.  @KayEss tells me this is the idiomatic CMake way.

**Comment by jtv** [comment]
I suppose this bug ticket is going to be obsolete by now, so I'll close it.  We've made great progress with the CMake build, and I'd like to thank everyone involved!
