### ISSUE TITLE
Async queries

### ISSUE THREAD

**Issue by jonesmz** [jtv/libpqxx#190]
The pipelines API, which provides the only asynchronous method of sending queries and retrieving results with the server, has no mechanism to notify the user's code when a query is finished.

https://libpqxx.readthedocs.io/en/latest/a01018.html

Is it possible to extend this so that a callback can be registered?

Ideally the registered callback would be on a per query basis, so that the user's code does not need to map callbacks to ids.

But it would also be acceptable to have the callback accept a list of query ids and nothing else.

While I'm at it, is it possible for the pipeline to be enhanced to provide an exec_params() style interface, that allows for paramaterized queries?

---------------------

My motivation for asking is that my application makes use of the boost asio framework to handle everything, as it's a network I/O driven application. Right now my code simply calls pqxx's functions, and blocks until pqxx is finished running.

I've looked at https://github.com/yandex/ozo, but there seems to be a licensing issue with it, where that library explicitly relies on a GPLv3 library.

**Comment by jtv** [comment]
I'm sorry, I missed this question earlier because of the other async discussion!

A callback is an interesting idea.  Of course you wouldn't be able to issue queries within it, because you'd still be inside the pipeline.  But you'd still have to block and wait _somewhere..._  It may need a separate thread.  One day we'll do full async, but first C++ implementations have to catch up.

As for `exec_params` and `exec_prepared` in a pipeline, yes absolutely that would be possible!  I haven't gotten around to it in the past, but if there's interest we can definitely do it.

**Comment by jonesmz** [comment]
> I'm sorry, I missed this question earlier because of the other async discussion!

Could you link to the other async discussion?

> A callback is an interesting idea. Of course you wouldn't be able to issue queries within it, because you'd still be inside the pipeline. But you'd still have to block and wait somewhere... It may need a separate thread. One day we'll do full async, but first C++ implementations have to catch up.

Hrmm, I'm guessing that you envision libpqxx to remain as a single threaded library, so the use of an asio framework likely isn't your plan.

There was discussion here https://github.com/jtv/libpqxx/issues/164 of this alternative library: https://github.com/KayEss/pgasio, which uses Boost ASIO, and I'll be investigating that, of course. But the nature of the discussion there made me think that libpqxx wasn't interested in following a similar model.

> As for exec_params and exec_prepared in a pipeline, yes absolutely that would be possible! I haven't gotten around to it in the past, but if there's interest we can definitely do it.

While the pipelines model of doing things isn't perfect, the lack of this functionality is the major reason I haven't switched my code to using it.

Like I said before, I'm already blocking to wait for libpqxx to get an answer back from the database. But a lot of my code needs to do 2 or 3 queries, mostly independently of each other, in a row. Pipelines, if they had support for parameters, would at least allow me to wait on all of the active queries at the same time without compromising on other code quality concerns.

**Comment by jtv** [comment]
Correct, the way I see things right now, I'd prefer to keep libpqxx single-threaded.  Going asio is a separate question though: that's something I'd very much like to do, but it's likely to come with radical changes, and compiler support needs to shape up first.  I really don't want to add a dependency on Boost.

I believe asio will also work better if I work directly on a socket, instead of layering on top of libpq.  The pipeline class might be able to execute multiple queries concurrently, that sort of thing.  But ripping out and replacing libpq is no small thing.  I need to be more conservative than pgasio can be: libpqxx must provide SSL, various authentication mechanisms, and so on — all provided by libpq.

**Comment by jtv** [comment]
@jonesmz, it's been a while but this may interest you: In #274 I've explored a new feature, "streaming queries."  Instead of `tx.exec()` you can do `tx.stream()` and you'll receive the results in a completely different way --
 1. You can start processing rows before the full result is in.  (This does mean that e.g. a network error could interrupt you while you're already processing data.)
 2. Iterating over the data now looks like a standard C++ "ranged `for` loop".  Very convenient.
 3. It's considerably faster.
 4. Only one row of data is in memory at a time (unless you store it somewhere of course).
 5. Each value comes out as a type you specify, e.g. `int` or `std::string_view`.  Conversion is built in.

Unless somebody spots a problem with the design, I'm going to release this as 7.1.0 pretty soon.  Please let me know what you think!

**Comment by jonesmz** [comment]
@jtv I'll take a look, thanks for thinking of me.

But fair warning, I've adopted this library in my code because of the tight integration with Boost ASIO: https://github.com/yandex/ozo

**Comment by jonesmz** [comment]
After looking at the code in your PR, I have to say I'm still not a fan of libpqxx in general. The overall model of blocking the thread while waiting for a reply from the server doesn't sit well with me.

You're right that the new streaming concept is better for situations where you're querying for a very large set of data, but that was never the problem that I had.

My situation is that I had many hundreds of queries that needed to be accomplished based on events from outside my application, and I didn't want to make the entire application wait for them to finish.

Since I originally brought this subject up, my application has evolved fairly significantly.

First, I've managed to completely separate write-only operations from read-only operations. There are no longer any read-write operations in the main set of functionality. There are some read-write in the non-critical path, but there's no sense in optimizing those, obviously.

Secondly, I've written my own "pipeline" concept on top of normal queries. This is similar to what the libpqxx pipelines do, but more application specific. By using a function written in plpqsql that accepts an array, or collection of arrays, for the parameters, I can batch the operations that I need to execute together based on how long it takes for the query to finish.

Roughly speaking, my pipeline framework has two states:
1) Query in flight
2) Query not in flight

When a new set of parameters is given to the framework, if the query is in flight, the new parameters get added to the storage and the framework does nothing else with them.  But if the query is not in flight, it initiates a new query with all the sets of parameters that are queued, including the new set.

When a query is in flight, and finishes, if there are any parameters queued, it initiates a new query with all the parameters available.

A variant of this allows for the framework to store std::function's as callbacks, for operations that return one row of data.

I don't bother supporting operations that return multiple rows of data with this approach, it's too complicated and outside the scope of what I want to accomplish.

The "correct" way to handle this is at the protocol level, using something like what is described here: https://2ndquadrant.github.io/postgres/libpq-batch-mode.html

Each query gets assigned some ID number that's specific to the connection object, and then the server can execute the queries in whatever order it wants (probably based on some policy information provided by the client of the connection).

Then, the server sends the results back, associated with the ID number for the query that triggered them.

That would allow me to rely on the postgresql server to handle all my unrelated queries as it wants, without needing to have multiple connections, and without the client side of things needing to do any batching of operations.

But the standard libpq does not support this, as far as I can tell.

More discussion about it can be found here: https://github.com/yandex/ozo/issues/195

**Comment by jtv** [comment]
@jonesmz I was unaware of Batch Mode.  Is that in a 2nd Quadrant fork of libpq?  It sounds a lot like what I do in `pqxx::pipeline`, and of course by then `pqxx::pipeline` must have been around for about a decade so it may have played a role in developing the idea.  Anyway, I'm curious about the server-side reordering of queries...  How do you keep that safe!?

In defence of libpqxx by the way, when I started looking into asynchronous execution models for libpqxx, the language just wasn't ready for it.  Even today, I think going full asio would be a real portability problem.  Boost has been too messy in the past (I've had real trouble cross-compiling it for instance) so I'd like to avoid the dependency if I can.  But it'd be great to have some place where I could introduce limited asio somewhere as a starting point.  Something that isn't too painful to implement in two different ways.  I'll have another look at streaming queries from that viewpoint.

**Comment by jtv** [comment]
I think the discussion here has about run its course.  Yes, I'd like to do async but compilers need to catch up, and there's the question of efficiency given the extra libpq calls.  I'll close the ticket, and keep it in mind.

**Comment by jtv** [comment]
Yes, I know, thanks.  I've already brainstormed with the author of that change.  It's so close to what libpqxx does (without even being aware of it apparently — same problem, same constraints, different minds following them to their logical conclusions) that I think it will be possible to rewrite the libpqxx pipeline to make use of it.

The bad news however is that I'll really want to do that _before_ I start extending the pipeline class further.  And that will take time.
