### ISSUE TITLE
Docs don't specify version number

### ISSUE THREAD

**Issue by JeffAbrahamson** [jtv/libpqxx#194]
The documentation [here](https://libpqxx.readthedocs.io/en/latest/a01309.html) (for example) specifies "latest", but doesn't indicate which version it considers to be latest nor does one easily find a way to jump back to previous versions of the documentation.

**Comment by jtv** [comment]
Indeed.  I've looked at this on occasion, but I don't know how to change it.  When you search for libpqxx on readthedocs, it also says there's no description for the project — even though the project does have a description.

One thing I have changed is to make the link point to the "stable" version by default, rather than to the "latest."  Any idea how I can incorporate a versions menu, or at least s?

**Comment by JeffAbrahamson** [comment]
I don't know, either.

I did find that on the [postgresql.org](https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING) (just an example link that happened to be open) site I could easily jump between versions, and that provides a the C documentation, which, combined with the pqxx source, usually sets things right.  But that's perhaps more cumbersome than need be.

**Comment by jtv** [comment]
Okay, I kludged a small improvement into `master`.  At least it'll show the version number on the main page now...  Couldn't figure out how to make it appear in the page header.

I suspect that it's harder here than it usually is because the libpqxx documentation is written in Markdown, not ReST.  The normal Sphinx substitutions like `|version|` won't work.
