### ISSUE TITLE
so name convention

### ISSUE THREAD

**Issue by walkthetalk** [jtv/libpqxx#2]
maybe libpqxx.5.0.so should be libpqxx.so.5.0 ?

**Comment by jtv** [comment]
Hmm...  Looks like, yes!  Question is, how?

To be honest I'm not even sure I want shared libraries in the default build.  Too sensitive to small changes for run-time mixing-and-matching.

**Comment by VestniK** [comment]
Versioning implementation in cmake: https://github.com/VestniK/libpqxx/commit/6e83dfcd5f000918cdec59a9b630ff246c61d2da it is done on top of https://github.com/jtv/libpqxx/pull/128 but can be backported to master if there will be problems with merging my MR.

**Comment by jtv** [comment]
Argh...  I can't seem to find any way to merge this properly in a way that doesn't look like an awful Git hack that I completely fail to understand!  I tried merging it as a patch but that won't work because the ancestor commit doesn't exist in my repo.

Any chance you could put it in a pull request for me, so we keep your name on the patch?

How I miss bzr...  :-)
