### ISSUE TITLE
Transactor deprecated with no good alternative

### ISSUE THREAD

**Issue by kalman5** [jtv/libpqxx#218]
I'm doing some experiments with the new pqxx 6.4.5 and I see that Transactor has been deprecated in favor of a lambda based transactor framework.

From my understanding whe need to create a lamba (or more in general a callable object) and then use:
`template<typename TRANSACTION_CALLBACK>
inline auto perform(const TRANSACTION_CALLBACK &callback, int attempts=3)
  -> decltype(callback())`

The issue is that the new "framework" doesn't allow several things it was possible to do with the Transactor:

1. Sleep between attempts, raise an alarm, etc..
2. Log why the attempts are failing

so in order to achieve the same functionalities that a user was getting out of the box the user has to rewrite (over and over) a lambda that does everything the old connection_base::perform was doing.

Why deprecate the Transactor ?

**Comment by kalman5** [comment]
Everything you say is reasonable however the direction is to shift "the hard" work to the user.

The transactor as it's today can be just removed, is not a replacement, if you think about it, as it is today: "a framework lambda based" is a mere while loop calling the lambda, ignoring silently any "recoverable" exception, transforming any transient issue with the database in a tight loop (user can not delay the attempts). I solved the issue just using as replacement the perform function I posted above that does exactly what the old `pqxx::transactor` was doing but without a base class and without the `pqxx::connection_base::perform`.
Sure I need to implement all the "concepts" on_commit/on_abort/on_doubt even if I want ignore those but that's ok, I don't see a single reason to silently ignore issues while interacting with my database. The only one I would remove is the "on_doubt" it will throw immediately so it will "intercepted" anyway just leaving the on_commit/on_abort.

About the pqxx::lazy_connection at this point let's remove it and let the final user to use a smart_pointer initialization at the very last moment.

Thinking about the not "auto reconnect" connection after all what you say is true, in case of error the final user can close/connect the old connection, reconnecting behind the scene, again without logging the event is something I would avoid.

When you say I haven't seen anyone using this feature are you referring to a users survey you did recently ?

**Comment by jtv** [comment]
I haven't surveyed users, no...  I talk to some users, and of course I've been writing about what I intended to change, and I marked things as deprecated.  But I can't think of a good way to ask users for feedback, beyond asking them to file a ticket just like you did.  Not getting a lot of feedback is part of what makes this work difficult.

Looking at your transactor code, I realise that we can't just retry when the connection breaks, because connections no longer automatically reconnect on failure!

Is that a problem?  I'm not sure.  If you're writing an application where you connect to the database just to perform a single transactor, I could imagine the transactor being responsible for establishing the connection.  But it's kind of "dirty" for the transactor to replace a long-lived connection that's meant to do other things as well.

And in either case, you might want to use a connection pool, rather than just construct a new connection.  So again I want to be careful not to encroach on the application's decision space too much.  It's another case where it's probably not hard for _the application_ to deal with the problem, but _inside libpqxx_ the application's architecture is an unknown.  A callback could handle it, but then you get a slightly surprising side effect from a callback, which is a recipe for bugs.

So the best course of action might be to just let a `broken_connection` go, and let the application deal with it.  Perhaps a separate framework-style helper will suggest itself.

**Comment by kalman5** [comment]
O right, in the incoming 7.x connections should be closed explicitly and the reopened, the transactor I posted will work for only for the 6.x part. I'm wondering if the users need a pqxx++ with the functions are being removed from pqxx. At the end we will have ton of users dealing with broken connections, and with transactor notify them what wrong is going on.

**Comment by jtv** [comment]
Yes, I think it could be really useful to add on a few extra functions for these things.  But in practical terms it has to go in stages: reduce complexity, figure out and perform the core changes, and then re-grow the extras on top of that.

**Comment by jtv** [comment]
(Confusingly, the previous C++ library, which libpqxx replaces, was called `libpq++` — that's how I came up with the name libpqxx.)

**Comment by jtv** [comment]
@kalman5 It's been a while, and I kind of forgot about this conversation for a while.  Are you reasonably happy with the way things stand?  (Not perfect, I understand, but perhaps this becomes easier once we have Concepts.)

**Comment by kalman5** [comment]
I'm currently using libpqxx 6.4.5, I replaced the removed transactor with my own one that has all the features of the removed one.

**Comment by jtv** [comment]
Oops, I didn't see a notification for that last message you wrote.

We could probably just re-implement the old transactor API on top of the new one, for those who want it.  I guess the only thing you'd lose is the automatic reconnection.  That's the part that introduced the complexity and the risk.

**Comment by jtv** [comment]
I'm on a bug-closing spree.  I'll close this one, but feel free to open a new one when needed.
