### ISSUE TITLE
Building library using VC compiler

### ISSUE THREAD

**Issue by DaeMon87** [jtv/libpqxx#223]
I followed the instructions in the install docs but had difficulty building using the VC compileres make files.

The error I got was 

        copy "\libpq.dll" "lib"
        The system cannot find the file specified.
        NMAKE : fatal error U1077: 'copy' : return code '0x1'
        Stop.

Looking into the make file it appears that the LIBPQPATHNOSURROUNDQUOTES variable is not set as well as LIBPQDPATHNOSURROUNDQUOTES

to correct this I copied the libraries from my postgresql install directory to the directory I was running this build from and then added 

LIBPQPATHNOSURROUNDQUOTES=.
LIBPQDPATHNOSURROUNDQUOTES=.

to my win32/common file.

This allowed my build to complete

**Comment by jtv** [comment]
Any news?  I'd like to be able to close this issue.

**Comment by jtv** [comment]
I'll just close the ticket.  Feel free to open a new one if that should turn out to be a mistake.

**Comment by jtv** [comment]
Update: I've got the CMake build working on AppVeyor.  And since this shows that the CMake build can work on Windows, I have _removed the custom Visual C++ build files._

The one big remaining problem with the CMake build right now is that it only builds a shared library.  We'll fix that.

What was probably going wrong in this case is that the "libpqxx.lib" that goes with "libpqxx.dll" was _overwriting_ the "libpqxx.lib" which was meant to be the static library.  For now we worked around that by disabling the static library build.  The next step will be to let you choose in the standard CMake way which form of library you want.
