### ISSUE TITLE
`std::vector` or `std::array` encoding support?

### ISSUE THREAD

**Issue by vinayan3** [jtv/libpqxx#242]
I'm trying to write values to a PG Array. It'd be nice if there was way to do the encoding piece.  Currently, I'm going to roll my own little converter to create a string for the array.

Is this a feature that is coming?

**Comment by jtv** [comment]
That sounds like a good idea, and easier than the parsing part.  It's about time we pushed this forward again.

**Comment by jtv** [comment]
I just implemented this in the 7.0.0 development line.  No plans to backport it to 6.x — it took some extensions to the string conversion machinery, which has changed dramatically since 6.x.

You can now embed a `std::vector` or `std::array` in an SQL query by passing it to `connection::quote()`.  As usual for postgres, it produces an array in string form, so depending on context, you may need to cast that string to the type you need.  See `test/unit/test_array.cxx` for examples.

Please let me know how this works out for you.  Unfortunately _parsing_ an SQL array is still awkward, and probably won't ever be as easy as just calling `from_string`.  The main reason is that we need to know the encoding before we can parse the array string.

Another thing I'd like to address in the future, if I can, is that converting a vector or array to an SQL array requires the input to be materialised in memory.  With C++20's ranges in particular, it would be nice to be able to pass a generator, but at the moment the code needs to be able to iterate the whole thing twice — once to size its buffer, and then again to actually fill that buffer.  A good solution for that would require a way for the string-generating code to extend its buffer on the fly.

**Comment by tomlankhorst** [comment]
>  The main reason is that we need to know the encoding before we can parse the array string.

In rows and fields, the encoding is known. So their `.as<...>()` functions could support parsing. 
Does this make sense to you @jtv ? I could try to mock something up if I find time this weekend.

**Comment by jtv** [comment]
I'm having computer trouble so I'm extremely limited in what I can do right
now.

There is some support for SQL arrays.  For parsing them, use
field::as_array().  It's not very user-friendly yet; you'll have to "walk"
the elements of the array.  (It's not as simple as it sounds because arrays
can be multi-dimensional.)  Yes, this, area of the API needs work.

Writing an SQL array is easy though.  IIRC you can just write a std::vector
or std::array.

In the future we can support any "std::ranges::range" as an SQL array, so
long as its element type isn't char or byte.  (I'm making those exceptions
because we'll interpret those as SQL strings or BYTEA, respectively.)  Or
maybe it should be a matter of std::basic_string and std::basic_string_view
getting special treatment - haven't worked that out yet.
