### ISSUE TITLE
Hammered for choosing version 7.0

### ISSUE THREAD

**Issue by ThomasMcLeod** [jtv/libpqxx#248]
I'm getting hammered at work for choosing version 7.0 insead of the "mainstream" version 4.0 that that Canonical distributes for Ubuntu. People are saying that 7.0 is a "roll your own" version and the implication is that it's not appropriate for commercial software.

I'm trying to defend using 7.0. So what exactly is the difference between the Debian version and this version? Why is the Debian version so far behind? I see that 4.0 it was first released in late 2011. Does the Debian version support all versions of Postgres? Does this version? Is the Debian version more compatible in some way? Thanks in advance for providing this information and thanks for supporting Open Source software.

**Comment by jtv** [comment]
Tough situation, and I'm sorry to hear it.  Actually 7.0 has not been released yet, so I'd recommend going with 6.4.5 for now, and if you can, regularly testing against 7.0 so you're ready for the leap.

Why does Debian ship with an ancient version?  It looks like there's just no package maintainer for it.  Debian has a process for asking for volunteers, but maintaining packages can be hard work — a friend once told me the usual mistake for new maintainers is to adopt too many packages.

The 4.0 version _should_ work with current versions of postgres, although obviously there will be features you don't get.

But let me try to answer your main question as I see it — what are the reasons for sticking with the packaged version or for building your own?

Obviously the big argument is "the Debian package is unmaintained."  That pretty much sweeps all arguments _for_ using the package off the table.  You're not going to get automatic updates, OS-specific patches, and actively tested software combinations, because nobody on the OS side is available to do the work.  I can't promise you all that either, but at least the upstream version is getting updates, and there's people here who can help you when you run into problems.

The next one is binary compatibility.  But libpqxx is a native C++ library, and I'm not really maintaining any binary compatibility anyway.  When you upgrade your libpqxx, you re-build both libpqxx and your own application.  In fact I generally recommend linking statically anyway, exactly because it'd be too hard to maintain binary compatibility.  This would be different for a C library.  You get a lot of compile-time compatibility between versions, but almost no binary compatibility.

As the final technical argument, of course there's a _reason_ why we've been making all those changes since 4.0.1!  I believe the library got better.  A lot better.  You get better compatibility with modern C++ compilers, API cleanups, bug fixes...  Years' worth of development.  See the NEWS file.

But in fairness, I do see one argument that goes the other way, and that's a psychological one.  When technical people have their own opinions about these things, sometimes managers get the impression that the techies are pursuing their own agenda. What from our perspective can be "obviously better" can look to a manager like "wasting time and money on improving something that's already good enough."  I used to get upset about that, but now I see it differently.  They're paying me their money to achieve their goals.  It's an unspoken requirement: _they_ must be comfortable with whatever I build.  And if they're not as technical, it won't be an easy thing for them to judge.  They'll have to look for clues such as preconceived ideas, defensiveness, and whether disagreement upsets you.  Of course if you _started out_ with wanting the newer version, that will look to them like one of those clues!

The _good_ news  is that the mere fact of seeing their point makes the discussion easier.  My advice?  Don't take anything personally, be willing to go with what either decision, and calmly focus on what's most important.  Propose an experiment if you can, so you can assess the best choice together.

**Comment by ThomasMcLeod** [comment]
That's for your wise counsel, much appreciated.

**Comment by jtv** [comment]
Let me know how it works out!

**Comment by ThomasMcLeod** [comment]
We downgraded to 4.0.1. The only trouble I had reverting the code was that, since the old connection class has no default constructors, I could not store connection pool objects in std containers. I had to build an array of connection objects in a char buffer with placement new.
I'm curious to know how one could determine that 7.0 was not released yet. I see that there is no Git tag for it. I that the only way to know?

**Comment by tt4g** [comment]
@ThomasMcLeod You can get a release notice by GitHub Notification: https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories#watching-a-single-repository

**Comment by jtv** [comment]
Bad news.  But having seen good people lose good jobs in this kind of disagreement, I'd rather see you live to fight another day.

Bit surprised about connections not having default constructors.  Constructing a connection without an argument has been possible pretty much from the beginning.  There's no _move or copy constructors_ of course — typo?

You're right that it should have been much, much clearer that 7.0 is not a released version.  But I do want an extremely light-weight policy for managing development versions...  How about I add an "alpha" suffix to the VERSION file?

**Comment by jtv** [comment]
Turns out I can't sneak a suffix into VERSION.  It breaks the CMake build.  :(  I'll just have to release 7.0 soon (I've sort of run out of problems to solve) and then we should have a protracted period of stability.
