### ISSUE TITLE
Transaction commit using Pipeline does not throw exception for Undefined Column error

### ISSUE THREAD

**Issue by leordev** [jtv/libpqxx#263]
I'm using the pipeline class to build a SQL transaction and commit it. If any of my SQL statements fails, libpqxx does not throw any exception and my whole transaction is missed - which can generate big data inconsistencies in my environment.

Source code sample: https://github.com/leordev/debug-libpqxx/blob/master/src/main.cpp

 **How to reproduce:** 
```
git clone https://github.com/leordev/debug-libpqxx
cd debug-libpqxx
git submodule update --init --recursive
mkdir -p build/run && cd build/run
cmake ../..
make -j

# dont forget to export your PG env variables
./src/divider 
```

You will receive the following output:
```
connect to postgresql... connected!
>>> starting sql transaction...
    CREATE TABLE IF NOT EXISTS my_test (my_num int NOT NULL)
    INSERT INTO my_test (my_num) VALUES (123)
    INSERT INTO my_test (my_num, dummy) VALUES (999, 'dummy str')
<<< Transaction Committed Successfully!%
```

But actually the above transaction didn't go through - it actually should have thrown `SQL Error [42703]: ERROR: column "dummy" of relation "my_test" does not exist
  Position: 30`. Now, if you comment the lines 22-24 https://github.com/leordev/debug-libpqxx/blob/master/src/main.cpp#L22-L24 -- The transaction will work because there's no SQL error in it. 

_Another facts:_
- if I add a sql syntax error, something like `INSERT aaaaa`, it fails as expected. Check https://github.com/leordev/debug-libpqxx/blob/master/src/main.cpp#L28
- If I don't use pipeline at all, and use only `transaction.exec`s it fails as expected, so at this moment I'm thinking about changing my program to get rid of the pipelines optimization and use `transaction.exec` for now... Any other ideas?

 **My system and versions:** 
-- libpqxx: tag 6.4.5 (a6b1d60) source imported manually in the [`external/libpqxx` folder](https://github.com/leordev/debug-libpqxx/tree/master/external)
-- Found PostgreSQL: /usr/local/lib/libpq.dylib (found version "11.5")
cmake --version
cmake version 3.15.5
macOS Mojave Version 10.14.6 **(but the error also happens in my Ubuntu server)**
Apple clang version 11.0.0 (clang-1100.0.20.17) Target: x86_64-apple-darwin18.7.0

**Comment by jtv** [comment]
To start with the good news, your transaction did not commit.  It failed and aborted implicitly, and by and large the pipeline behaved as intended.  If you try to use the transaction in any way after the pipeline fails, you will see an exception — because the transaction was already aborted.  The `commit()` ended up as a no-op, and I'll get back to that in a moment.

You're not meant to get an exception _when you insert_ a failing query into the pipeline.  You're meant to get an exception _when you request the query's result._  Effectively **the exception is the result.**  In this case, the problem is that you never asked for the result!  You called `complete()`, which fires off any remaining queries to the backend, retrieves their results, and decouples from the transaction... but it doesn't return the queries' results and it doesn't report the queries' failures.  The results are still sitting in the pipeline waiting for you to request them.

If I change your code so that it requests the result of the failed query (either before or after the commit — the `complete()` enables you to do it after the commit if you like), then I do get an `undefined_column` exception at that point, exactly as you'd expect.

To fix the test code properly, request results for the queries you inserted.  If you're really not interested in the results except to know that there was no error, just loop through them:

    while (!pipeline.empty()) pipeline.retrieve();

(And yes, I need to document this properly!)

The open question is: why was there no exception _when you tried to commit the failed transaction?_  To commit after a failed query is a bug in the test code, but ideally the transaction should have detected that bug.  The pipeline never kicked the transaction into a failure state, so the transaction object doesn't know that the transaction on the backend has already failed.  And I suspect there's also a problem with a query result still sitting in the queue waiting for you to pick it up.  It will take me some time to figure out exactly when the transaction should and shouldn't be kicked into a failure state.

**Comment by leordev** [comment]
Thank you very much @jtv for the library and also for the whole amazing explanation above. I got it fixed, updated my repo again with the above fixes! (https://github.com/leordev/debug-libpqxx/blob/master/src/main.cpp#L36-L37) It fails nicely if I process the pipeline by retrieving it:

```
connect to postgresql... connected!

>>> starting sql transaction...
inserting 1000 rows...
... Pipeline completed.
+++ Pipeline cleaned in 9 ms
=== Transaction committed in 6 ms


>>> starting sql transaction...
inserting 1000 rows...
... Pipeline completed.
+++ Pipeline cleaned in 10 ms
=== Transaction committed in 2 ms


>>> starting sql transaction...
inserting 1000 rows...
... Pipeline completed.
+++ Pipeline cleaned in 12 ms
=== Transaction committed in 5 ms


>>> starting sql transaction...
inserting 1000 rows...
... Pipeline completed.
+++ Pipeline cleaned in 10 ms
=== Transaction committed in 4 ms


>>> starting sql transaction...
inserting 1000 rows...
inserting poisoned data: INSERT INTO my_test (my_num, dummy) VALUES (999, 'dummy str')
libc++abi.dylib: terminating with uncaught exception of type pqxx::undefined_column: ERROR:  column "dummy" of relation "my_test" does not exist
LINE 1: ...y_num) VALUES (123); INSERT INTO my_test (my_num, dummy) VAL...
                                                             ^

... Pipeline completed.[1]    14697 abort      ./src/divider
```
