### ISSUE TITLE
Sort on pqxx:result does not work and generates no compile error

### ISSUE THREAD

**Issue by janhec** [jtv/libpqxx#285]
There are plenty of ways to retrieve a sorted result by using clause ORDER BY, so there is no major problem in functionality because there are alternatives.
Experimenting with client-side sorting, I found the result object cannot be sorted, although the code compiles and runs fine (it just does not sort). The query using ORDER is designed to put the result rows in the wrong order, to be rectified by the following sort().
 
    auto BT = pq->exec("SELECT * FROM __get_bedrijven(8) ORDER by bedrijf_plaats;");
    std::vector<string> nms1, nms2;
    for (auto& bt : BT) nms1.emplace_back(bt[1].as<string>());
    auto srthlp = [](decltype(BT.cend()) it1, decltype(BT.cend()) it2)
    {
        const std::string str1{ (*it1)[1].as<string>() }, str2{ (*it2)[1].as<string>() };
        return str1 < str2;
    };
    std::sort(BT.begin(), BT.end(), srthlp);
    for (auto& bt : BT) nms2.emplace_back(bt[1].as<string>());

By breakpoints, the returns of srthlp are verified. No sorting is effected by the final sort(), nms1 and nms2 are identical.
My suggestion is, if the result contents are immutable, to adapt declaration to cause a compiler error, as would be generated by

    const std::vector<string> astr{"bb","aa"};
    sort(astr.begin(),astr.end());

**Comment by jtv** [comment]
Yes, you're right.  It never occurred to me to try something like this, because result objects are supposed to be immutable...  Got some more urgent things to look into right now, but hope to get this done soon.

Thanks for spotting this!  And welcome...  Seeing a very sudden burst of Dutch people here lately, so getting curious how you got into libpqxx.  _Hoe meer zielen hoe meer vreugd._  :-)

**Comment by janhec** [comment]
Hey Jeroen,
Geweldig werk dat je doet!
Ik heb geen directe band met andere Hollanders op dit forum, helaas.
Behalve 1 want ik dacht dat ik 1x eerder wat gemeld heb
(PQencryptPasswordConn()).
Ik heb projecten die de BAG gebruiken, en ook een project dat eerst een
soort excel project was, tot ik de anderen kon overtuigen dat het een
database project moest zijn.
Dat leek me ook de beste manier om taken te verdelen, werken aan een client
UI in C++/clr en functies maken in de database omgeving.
Welke database dan, nou postgresql natuurlijk! Ondertussen was ik begonnen
met een UI in windows forms, geen C# maar C++/clr. Vanwege eerdere ervaring.
Tijdje bezig geweest met frameworks en toen snel weer de weg ingeslagen van
minder is meer.
Was blij dat ik libpq via een libpqxx kon doen! Maar wel een massieve
leercurve, inclusief security, SCRAM, mail via plpython, etc.
Never a dull moment but doing weird things, now and then, as a consequence.
Jan

and .... for the non-Dutchies:
Hey Jeroen,
Great job you're doing!
I don't connect directly to other Dutchies on libpqxx, maybe just one,
because I remember posting about  PQencryptPasswordConn().
I have projects relating to the BAG (Dutch building and address
repository), and a project which was migrated from a spreadsheet to
database.
Which could hardly be any other than postgresql. Good way to split tasks
between client UI (C++ windows forms) and server functions to manipulate
data.
I don't have great experiences with frameworks, so I am very happy to use
libpqxx and grateful not to have to do libpq directly all the time.
Had (and stil have) a steep learning curve also including security, scram,
mail in postgresql using plpython.
Never a dull moment but doing weird stuff some of the time as a consequence.

**Comment by jtv** [comment]
Forcing myself back to English since these conversations are on the record.  :)

This is all wonderful to hear.  And yes, I remember the `PQencryptPasswordConn()` change, that was a welcome fix.  Though in all honesty at the time I was a bit overwhelmed and didn't really feel like making changes.

Do I understand correctly that you're compiling libpqxx to .NET?  I've been curious how well that worked, since I try to support a broad range of platforms.  Haven't heard about anyone doing that in a long, long time.  Which hopefully is a case of "no news is good news."

**Comment by jtv** [comment]
This took some digging into design decisions made decades ago..  Really, all that `pqxx::row` is is a kind of _reference_ to the actual data.  And so I decided at the time that they should be able to do everything that an iterator can do.

I'll look into the possibility of deprecating that.  Because we've got iterators.

**Comment by jtv** [comment]
I've marked `row::swap()` as deprecated.  Once it's gone, it will no longer meet the requirements of `std::sort()` and that'll be the end of it.

If you don't mind, I'll close the bug at this point.  It's not a full resolution, but it's on the rails and I'd like to keep up!
