### ISSUE TITLE
pqxx::nullness is not usable in a constant expression for custom data type

### ISSUE THREAD

**Issue by JCCPort** [jtv/libpqxx#298]
I have a custom postgresql datatype that is (double, double, double) called dimensions.

I am trying to write entries of this type into a table using pqxx stream_to in the following manner (where the columns "pos" and "dir" are of my custom type "dimensions"):

```
void dataWriter::writeStepRows() {
    pqxx::work txn(*connection());
    pqxx::stream_to stream{
            txn,
            "steps",
            std::vector<std::string>{"run_id", "step", "pos", "direction", "interaction"}};
    for(auto & i : data_) {
        auto data = std::get<0>(i);
        auto UUID = std::get<1>(i);
        for (unsigned int j = 0; j < data.size(); j++) {
            std::tuple pos = std::make_tuple(std::get<0>(data[j]), std::get<1>(data[j]), std::get<2>(data[j]));
            std::tuple dir = std::make_tuple(std::get<3>(data[j]), std::get<4>(data[j]), std::get<5>(data[j]));
            std::string interaction = std::get<6>(data[j]);
            std::tuple entry = std::make_tuple(UUID, j, pos, dir, interaction);
            stream << entry;
        }
    }
    stream.complete();
}
```

This gives the following error:

`/usr/local/include/pqxx/strconv.hxx:288:3: error: the value of ‘pqxx::nullness<std::tuple<double, double, double>, void>::has_null’ is not usable in a constant expression
  288 |   if constexpr (nullness<TYPE>::has_null)`

Would you please be able to assist me in finding a way to get this working?

Thanks, Josh

**Comment by jtv** [comment]
First off, best to define a C++ type `dimensions` as an equivalent to your eponymous custom SQL type.  That way you'll be able to treat a `dimensions` object as a unit, and also, insert it into your stream as a single field's value.

Then, you'll need to specialise `pqxx::nullness<dimensions>` and `pqxx::string_traits<dimensions>` so that libpqxx's conversion functions will know how to write those values into the stream, and/or read it from the database.  Have a look at `include/pqxx/doc/datatypes.md`, as well as `include/pqxx/strconv.hxx`.  (There's more detail in `include/pqxx/internal/conversions.hxx`, but I hope you won't need to go there.)

It's a bit of work, and frankly I rarely ever hear from people doing it.  So if you run into any questions, please post them on this ticket.

**Comment by jtv** [comment]
@JCCPort, have you had a look at `datatypes.md`?

**Comment by JCCPort** [comment]
I ran into a separate issue that took a couple of days to fix, I'll try to implement what you've said above and will let you know ASAP what the outcome is.

**Comment by jtv** [comment]
Thanks, no rush.

**Comment by jtv** [comment]
@JCCPort had time to look?

The "7.1" development branch (actually it's called `transaction_stream_from`, the one visible in #274) introduces an extra field: `nullness<TYPE>::always_null`, which says whether `TYPE` is one of those rare cases where a type has _only_ null values.  So you'll need to have that in your `nullness` struct as a `constexpr`, normally with value `false`.

**Comment by jtv** [comment]
I'll just close this ticket.  Feel free to reopen it (assuming that works), or open a new one if needed.
