### ISSUE TITLE
Timed transactions

### ISSUE THREAD

**Issue by zatsepin** [jtv/libpqxx#3]
Hi Jeroen,

I just was searching something like transaction which could cancelled by timeout and met these mails in archive

http://lists.pgfoundry.org/pipermail/libpqxx-general/2007-November/000039.html

Why didn't you include this patch into upstream repo?

**Comment by jtv** [comment]
I'm sorry for just ignoring this proposal for so long.  It looks like would have required a lot of work to get my head around, make it portable, and write up the tests.  And so I ran away from it hoping that someday I would have the time and energy, instead of saying "this needs more work and I don't think I can do it."
