### ISSUE TITLE
Allow to  reuse stream_to after complete.

### ISSUE THREAD

**Issue by patriotyk** [jtv/libpqxx#305]
For now it is not possible to use the same instances of `pqxx::work` and `pqxx::stream_to` after committing a data. I think, it is a bug because after `commit()` those objects becomes useless.
Also I think instantiating of this objects could be to heavy and there is no any sense to instantiate them every time.

**Comment by jtv** [comment]
This is a design decision, not a bug.  A `pqxx::transaction` is not an object that _manages_ transactions; it _is_ a transaction.  When the transaction ends, the `pqxx::transaction` becomes useless because it _is_ the transaction, and the transaction is over.

Constructing a transaction is not free, but that's mainly because it starts a transaction on the database.  Reusing the object for 2 transactions won't fix that, because it'd still need to start 2 transactions.

**Comment by patriotyk** [comment]
Thank you for the quick response.
