### ISSUE TITLE
configure failed due to the wrongly set variable `with_postgres_lib`

### ISSUE THREAD

**Issue by asdetrefle** [jtv/libpqxx#311]
When running the `configure` script from tag `7.0.6`, I ran into a problem where some tests could not find `libpq`. This happens even if I pass `--with-postgres-lib=/dir/to/libpq`. After some research, I found that was because the linker flag `-L/dir/to/libpq` was never passed to the compilation command. And this was caused by [**Line 19127**](https://github.com/jtv/libpqxx/blob/7.0.6/configure#L19127) of the script where `with_postgres_lib` is set to empty. Below is the code from [L19120](https://github.com/jtv/libpqxx/blob/7.0.6/configure#L19120) to L19140 from `configure`:

```bash
if test -n "$PKG_CONFIG" && test -x "$PKG_CONFIG"; then
    if test -z "$with_postgres_lib"; then :
  with_postgres_lib=$($PKG_CONFIG libpq --libs-only-L | sed 's/^-L//')
fi
    { $as_echo "$as_me:${as_lineno-$LINENO}: using PostgreSQL libraries at $with_postgres_lib" >&5
$as_echo "$as_me: using PostgreSQL libraries at $with_postgres_lib" >&6;}
    # configure insists on inserting a library search path, so give him a standard one ...
    with_postgres_lib=""  # LINE 19127 - THIS CAUSED MY PROBLEM

    #POSTGRES_LIB="-R${with_postgres_lib}"

elif test -n "$PG_CONFIG" && test -x "$PG_CONFIG"; then
    if test -z "$with_postgres_lib"; then :
  with_postgres_lib=$($PG_CONFIG --libdir)
fi
    { $as_echo "$as_me:${as_lineno-$LINENO}: using PostgreSQL libraries at $with_postgres_lib" >&5
$as_echo "$as_me: using PostgreSQL libraries at $with_postgres_lib" >&6;}

    #POSTGRES_LIB="-R${with_postgres_lib}"

fi
```
Furthermore, if we wrap `with_postgres_lib=""` inside an else branch here, the logic behind still seems wrong to me. I have both `$PKG_CONFIG` and `$PG_CONFIG` set on my machine, but `libpq.pc` is not on the `$PKG_CONFIG_PATH` and I want the configuration using `$PG_CONFIG` for the setup. (Because my `pkg-config` is from Homebrew but my postgres is not installed by Homebrew.)

To me, I think we should firstly try to use `$PKG_CONFIG` to configure `with_postgres_lib` and if it cannot find any then we test with `$PG_CONFIG`.

**Comment by jtv** [comment]
I agree it's wrong.

The `configure` script is automatically generated based on `configure.ac`, so it's better to talk in terms of `configure.ac`:

    if test -n "$PKG_CONFIG" && test -x "$PKG_CONFIG"; then
        AS_IF(
           [test -z "$with_postgres_lib"],
           [with_postgres_lib=$($PKG_CONFIG libpq --libs-only-L | sed 's/^-L//')])
        AC_MSG_NOTICE([using PostgreSQL libraries at $with_postgres_lib])
        # configure insists on inserting a library search path, so give him a standard one ...
        AC_SUBST(with_postgres_lib, "")
        #POSTGRES_LIB="-R${with_postgres_lib}"
        AC_SUBST(POSTGRES_LIB)
    elif test -n "$PG_CONFIG" && test -x "$PG_CONFIG"; then
        AS_IF(
           [test -z "$with_postgres_lib"],
           [with_postgres_lib=$($PG_CONFIG --libdir)])
        AC_MSG_NOTICE([using PostgreSQL libraries at $with_postgres_lib])
        AC_SUBST(with_postgres_lib)
        #POSTGRES_LIB="-R${with_postgres_lib}"
        AC_SUBST(POSTGRES_LIB)
    fi


The reason we don't try `pg_config` first is that `pg_config` is deprecated.  I could make it try `pg_config` if `pkg-config` doesn't find anything, but it'd be a stopgap solution.  The moment `pg_config` is removed, the problem would come back.

I think there a few other problems in the script though.

One is `POSTGRES_LIB`.  Who is supposed to set it?  I always assumed that it was autoconf magic, but perhaps the only code that sets is those two commented-out assignments.  In which case, this entire block of script ends up achieving precisely nothing.

The next is: what happens when neither `pkg-config` nor `pg_config` is available?  You _should_ be able to pass `--with-postgres-lib` to work your way out of that situation.  The `AC_SUBST` part should be an unconditional statement at the end.

Then there's the `-R` in the commented-out lines.  I'd prefer a `-L`, I think — unless someone more knowledgeable can tell me why that's wrong.

And finally of course, there's far too much unconditional code here.

Would you mind helping me with a bit of testing on this?  I'm dealing with some personal drama at the moment, so I probably wouldn't be too good at testing right now.  But I could try writing up a new version of the script and ask you to test it with your particular situation.  Does that sound OK?

**Comment by jtv** [comment]
@asdetrefle actually the diff was too big for comfort, so I did some testing and then committed my changes to `master`.  Could you see if it solves the problem for you?

**Comment by asdetrefle** [comment]
Thanks, yes the new code makes sense to me now.

I've done various testing with different setups on my Mac and CentOS, whether having `libpq.pc` on `$PKG_CONFIG_PATH` or not, or having  `$with_postgres_lib`  set or not. And it is working as expected now.

**Comment by jtv** [comment]
Great!  I'll close the ticket then.
