### ISSUE TITLE
Is it possible to perform a SELECT [ITEMS] FROM table WHERE ITEM in LIST?

### ISSUE THREAD

**Issue by looopTools** [jtv/libpqxx#326]
Hey, 
I have been searching for a way to run a query which SELECT based on items in a list using wildecards. 
But I have been unable to find a solution. 
In excerpt what I wanna do is:

```C++
conn.prepare("seen", "SELECT fingerprint FROM basis WHERE fingerprint IN $1")
worker.exec_prepared("seen", fingerprints);
```

Where fingerprints is a vector of binary strings where each string represents a `std::vector<uint8_t>` (confusing I know). Is this possible in pqxx?

**Comment by jtv** [comment]
I'm not entirely well right now so I'm not sure I'll be a lot of help.  Things may be a bit clearer to begin with if you use a regular statement, rather than a prepared statement, and explicitly represent the data as a string yourself using `to_string`.

If `fingerprint` is effectively a `BYTEA`, have a look at `pqxx::binarystring` for that.  It _could_ be as simple as just passing a `std::vector<pqxx::binarystring`.

**Comment by looopTools** [comment]
You actually answered my question. 
Thanks alot :)

**Comment by jtv** [comment]
:-)
