### ISSUE TITLE
Is it possible to retrieve col name with stream?

### ISSUE THREAD

**Issue by fhelen** [jtv/libpqxx#327]
Hello,
Thank you for your really usefuu job.
I would like to use stream, in order to parse select query and store result in map.
Example: [field_name_1]:[data].
How can i get field name with a stream?

Thanks by advance
Florian

**Comment by tt4g** [comment]
As far as I look soruce code in pqxx 7.1.1, there is no support get column name (field name) from `pqxx::stream_from`.
However, `pqxx::stream_from` has a member variable `pqxx::stream_from::m_fields`, which seems to manage the current column name.
If an API is added to this member variable to access it safely, it may be possible to get the column name.

Another way, You can  get column name from `pqxx::result::column_name(row_size_type)` or `pqxx::field::name` but these are not accessible from pqxx stream.

https://github.com/jtv/libpqxx/blob/10f00b85279728721325d30d1821de41d66fc903/include/pqxx/result.hxx#L161-L162

https://github.com/jtv/libpqxx/blob/10f00b85279728721325d30d1821de41d66fc903/include/pqxx/field.hxx#L82-L83

**Comment by jtv** [comment]
I wasn't expecting the column name to be very useful to anyone in this situation, so I never thought of providing the information.

There is no `result` object in this case, so that won't work.  And `stream_from` doesn't have the information either — its `m_fields` member stores field _data,_ not field names.  The `stream_from` constructor may have the field names, but only if you choose to provide them in the first place.

**Comment by fhelen** [comment]
Hello,
Thank you for your answers.
