### ISSUE TITLE
MacOS: error: inline function 'pqxx::string_traits<pqxx::binarystring>::size_buffer' is not defined

### ISSUE THREAD

**Issue by looopTools** [jtv/libpqxx#331]
Hello, again. 

I am using libpqxx 7.1.1 and this is based on #326  
I have the following code 

```c++
...
m_conn.prepare("seen_fingerprints", "SELECT fingerprint FROM basis WHERE fingerprint IN $1");
...
    ....
    {
        std::vector<pqxx::binarystring> fingerprints;        

        for (auto it = seen_fingerprints.begin(); it != seen_fingerprints.end(); ++it)
        {
            auto fingerprint = pqxx::binarystring(it->first.data(), it->first.size());
            fingerprints.push_back(fingerprint);
        }

        pqxx::work worker{m_conn};
        pqxx::result res {worker.exec_prepared("seen_fingerprints", fingerprints)};
       ....        
        worker.commit();        
    }
```

This build on Linux, no problem. But on MacOS I get these errors: 

```
[ 99/102] Compiling src/alexandria-storage-node/database.cpp
In file included from ../src/alexandria-storage-node/database.cpp:1:
In file included from ../src/alexandria-storage-node/database.hpp:5:
In file included from /usr/local/include/pqxx/pqxx:4:
In file included from /usr/local/include/pqxx/connection:6:
In file included from /usr/local/include/pqxx/connection.hxx:27:
In file included from /usr/local/include/pqxx/prepared_statement.hxx:17:
In file included from /usr/local/include/pqxx/internal/statement_parameters.hxx:26:
In file included from /usr/local/include/pqxx/strconv:4:
/usr/local/include/pqxx/strconv.hxx:168:3: error: inline function 'pqxx::string_traits<pqxx::binarystring>::size_buffer' is not defined [-Werror,-Wundefined-inline]
  size_buffer(TYPE const &value) noexcept;
  ^
/usr/local/include/pqxx/internal/conversions.hxx:672:55: note: used here
                                          elt_traits::size_buffer(elt) - 1};
                                                      ^
In file included from ../src/alexandria-storage-node/database.cpp:1:
In file included from ../src/alexandria-storage-node/database.hpp:5:
In file included from /usr/local/include/pqxx/pqxx:4:
In file included from /usr/local/include/pqxx/connection:6:
In file included from /usr/local/include/pqxx/connection.hxx:27:
In file included from /usr/local/include/pqxx/prepared_statement.hxx:17:
In file included from /usr/local/include/pqxx/internal/statement_parameters.hxx:26:
In file included from /usr/local/include/pqxx/strconv:4:
/usr/local/include/pqxx/strconv.hxx:154:23: error: inline function 'pqxx::string_traits<pqxx::binarystring>::into_buf' is not defined [-Werror,-Wundefined-inline]
  static inline char *into_buf(char *begin, char *end, TYPE const &value);
                      ^
/usr/local/include/pqxx/internal/conversions.hxx:732:23: note: used here
    string_traits<T>::into_buf(buf.data(), buf.data() + buf.size(), value)};
                      ^
2 errors generated.
``` 

I have tried to configure like this `CXX=clang++ ./configure --disable-documentation CXXFLAGS=-O3` and `./configure --disable-documentation CXXFLAGS=-O3`.  Both works on Linux.

**Comment by tt4g** [comment]
As far as I see look source code, `pqxx::string_traits<std::vector<T>>` is dependent on `pqxx::string_traits<T>` but `pqxx::string_traits<pqxx::binarystring>` is not declared.

Should you have to pass the `std::vector<T>` to `worker.exec_prepared(...)`.

**Comment by looopTools** [comment]
@tt4g can you ellaborate sorry. How should I parse this? tried to find documentation for this but couldn't.

**Comment by tt4g** [comment]
@looopTools Well, maybe there is no documentation. I checked the source code with the error message.

I get most of my libpqxx usage from the official documentation below and test codes, 
But I can not found information of `pqxx::binarystring` and `pqxx::string_traits<T>` from these.

* Read the docs: https://readthedocs.org/projects/libpqxx/
* libpqxx: http://pqxx.org

What I do know is that pqxx converts any C++ object into a string in order to pass the parameters of the SQL statement to libpq's API.
This string conversion is defined in the `pqxx::string_traits<T>` template and It is defined in `include/pqxx/strconv.hxx` and `src/strconv.cxx'.

**Comment by looopTools** [comment]
@tt4g I just find it weird that it builds on linux and not on mac. Shouldn't it fail on both then?

**Comment by tt4g** [comment]
> I just find it weird that it builds on linux and not on mac. Shouldn't it fail on both then?

@looopTools Yes. It is weird. But I have no idea what caused it.

By the way, I was just thinking of a workaround.
I can build the following code with pqxx 7.1.1 and MSVC 2019 on Windows 10 x64.

```cpp
#include <pqxx/pqxx>

#include <cstdint>
#include <iostream>
#include <type_traits>
#include <vector>

// In my platform: std::uint8_t == unsigned char == pqxx::binarystring::char_type
static_assert(std::is_same_v<std::uint8_t, unsigned char>);
static_assert(std::is_same_v<std::uint8_t, pqxx::binarystring::char_type>);

int main(int, char**) {
    pqxx::connection con{"host='127.0.0.1'"
                         " port=5432 dbname='test'"
                         " user='test'"
                         " password='123456789'"
                         " client_encoding='utf8'"};

    con.prepare("p_statement", "SELECT $1::bytea AS one");

    std::vector<pqxx::binarystring> binary_parameters;
    binary_parameters.emplace_back("foo");
    binary_parameters.emplace_back("bar");
    binary_parameters.emplace_back("baz");
    binary_parameters.emplace_back("\033[31mRED\033[0m"); // ANSI color

    std::vector<std::uint8_t> temp;

    for (auto it = binary_parameters.begin(); it != binary_parameters.end(); ++it)
    {
        // Concatenate all binary data.
        temp.insert(temp.end(), it->begin(), it->end());
    }

    // Copy from std::vector<std::uint8_t> to pqxx::binrarystring.
    // Because pqxx::binarystring does not support operations such as append and push_back,
    // and the constructor copies data from contiguous memory areas
    pqxx::binarystring parameter{temp.data(), temp.size()};

    pqxx::work worker{con};
    pqxx::result res{worker.exec_prepared("p_statement", parameter)};

    for (auto&& row : res) {
        pqxx::binarystring one{row.at(0)};
        std::string_view view = one.view();

        std::cout << "result: " << view << "\n";
    }

    worker.commit();

    return 0;
}
```

Will this snippet help you?

**Comment by KayEss** [comment]
`char` is `signed` on Mac, but `unsigned` on Linux (or the other way around -- in any case different). This could change the specialisation looked for and would be easy to mix up.

**Comment by jtv** [comment]
I think I may see the problem.  There's a special case.

When you pass a `binarystring` to a prepared statement, libpqxx never converts it to a string.  There's a special facility in libpq for passing binary parameters.  So, libpqxx keeps it in binary form and passes it that way.  For that, we don't need a conversion from `binarystring` to string form.  And so I never implemented that conversion, because I saw it as an open invitation to make code inefficient.  Why convert binary to text format and have the server parse it back, when there's a way to pass binary directly?

But what happens when you try to pass a `std::vector<pqxx::binarystring>`?  Well, there's a string conversion for `std::vector<T>`, but it (of course) makes use of the string conversion for `T`.  In this case, `T` is `binarystring`, and so...  _not implemented._

I have no idea why this would compile on one platform and not on another.  I would suspect that there's some unnoticed difference, perhaps hidden in an old object file that isn't being recompiled, something like that.  Or perhaps it's related to what @KayEss said: `char` being signed on one platform and unsigned on the other.  Sounds plausible, I just can't think how it might come into play.

One thing I can try to help address the problem is to implement a string conversion for `binarystring`.  It's not as efficient as passing a `binarystring` to a prepared statement, because it needs to do escaping, so I'll have to add copious amounts of documentation on sane use.  And of course we'll still have to see whether it works with the `IN` syntax in the first place.

(I think I've also found a bunch of dead code related to prepared statements,  so I also need to clean that up.)

**Comment by looopTools** [comment]
@tt4g thanks I will try and use that and see :) 
@KayEss damnit your right, I had forgotten about that. 
@jtv I don't know if it is need as I am probably a single user crazy enough to do this 😅 I will try tt4g suggestion or I will find a work around. This would just have been really nice as it will save around 17 bytes (in the worst case) per entry in that table of the database. Where the table can become really big :)

**Comment by jtv** [comment]
The cat only just allowed me back on my laptop.  Turns out lubuntu isn't great at saving power with my laptop, so it was nice and warm and... perfect for sitting on, evidently.  Do let us know how you get on.

I'm beginning to wonder if perhaps it's time for a `bytea` class in libpqxx, with two-way conversion.  It doesn't look like something I can just build into `binarystring` without changing the API.

**Comment by looopTools** [comment]
@jtv I can outline my "problem" and then you can judge. 
I have a ton of SHA-1 and SHA-2 hashes which I need to store in the database. 
Now let us stick with SHA-1.
SHA-1 takes in its "binary"-form 20 bytes, if it is converted to a UTF-8 `std::string` it looks like whatever and is not necessarily a safe string. To go around this, one could convert the hash to the hexadecimal representation and store that in the DB the conversion will be as follows:

```c++
#include <string>
#include <sstream>

std::vector<uint8_t> hash; // assume this is a valid 20 byte SHA-1 HASH 
std::stringstream ss; 
for (const auto& b : hash)
{
    ss << std::hex << (int) b; 
}

auto hash_string << ss.str(); 
```
However for each hash this doubles the size of the data from 20 to 40 bytes. Now let us be fair to string an assume our hash `bytea` will take the extra 4 bytes in the database. So the hash is 24 bytes and the string representation is I believe 41 bytes, that is a difference of, as mentioned, 17 bytes per entry of each entry for this table in the database and I expect to have thousands if not millions of these entries, so 17 bytes start to be a significant impact. 

Also, I will never add just one entry into this table, so performance-wise bulk insert is more efficient.
I am currently using @tt4g solution, but when I have the time I will do a performance benchmark, comparing this solution to a multi-insert version. To see which yields the highest throughput. 

I personally think that a designate `bytea` class will increase the ease-of-use when working with blobs of data in pqxx, but maybe I am lone in this assumption :)

**Comment by jtv** [comment]
We're talking about two different things here: _transferring_ the data to the database, and _storing_ the data in the database.  It should be possible to _transfer_ your data in hex-escaped form (as with `esc_raw()`) but into a binary form (as with the BYTEA type).  Should cost you a bit of CPU and network time, but no extra storage on the server.  Arrays may complicate things a bit though.

Some very good news is that as long as the back-end is recent enough, it'll easy enough to build a `to_string` etc. for `binarystring`.  And the result is faster as well!

**Comment by looopTools** [comment]
@jtv AWESOME!

**Comment by jtv** [comment]
Doing a little cleaning up.  Are we done with this ticket?

**Comment by looopTools** [comment]
i would say yes :)

**Comment by jtv** [comment]
Cool, thanks.

**Comment by jtv** [comment]
@looopTools I just committed one-way string conversion support for `binarystring`.  You can now convert a `binarystring` to string format (which escapes the data of course), insert it in a `stream_to`, or even do the same for e.g. a `std::vector<pqxx::binarystring>`.  Hope that helps.

I may do conversion in the other direction next.  But I may only do that for the hex-escaping format, not the format used in pre-9.0 versions of postgres.
