### ISSUE TITLE
Wrap PQconnectdbParams()

### ISSUE THREAD

**Issue by millnet-maho** [jtv/libpqxx#343]
Have you considered adding a connection constructor that takes a std::map or something and calls PQconnectdbParams() instead of PQconnectdb()? When you create an application or service, you might want to let the user/administrator configure it in a more user-friendly manner than just entering a complete connection string, and having to do quoting/escaping kinda sucks a little, but the worse part is if you need to combine a configured connection string with additional options and therefore need to parse it first.

**Comment by jtv** [comment]
I have, once or twice, and decided against it.  If you look at these problems in history, a string format is much more robust than a series of structs as options change over time.  Moreover, libpqxx would have to mirror _every single option_ in libpq.  Which would start another rush circus every time libpq adds a new option, with provisions for version mismatches, requests for backports, and so on.

Compared to all that, I don't think a string is that bad.  It'd be nice to support escaping of option strings, but then again if you use the URL format, that's a job for another, more generic library.

**Comment by millnet-maho** [comment]
Why structs? I agree, that would be a pain to maintain. I was thinking something along these lines:
```c++
void pqxx::connection::init(const std::map<std::string, std::string>& options)
{
  const char *keywords[options.size()+1];
  const char *values[options.size()+1];
  size_t i = 0;
  for (const auto& option : options) {
    keywords[i] = option.first.c_str();
    values[i] = option.second.c_str();
    ++i;
  }
  keywords[i] = values[i] = 0;

  m_conn = PQconnectdbParams(keywords, values, 0);
  .
  .
  .
```

**Comment by jtv** [comment]
Oh, right, I was thinking of the wrong API!  Probably because I had to deal with `PQconninfoOption` structs for libpqxx 7.0.  Key/value string pairs are robust.  I couldn't use them before, because `pqxx::connection` used to store its connection string.  In 7.0 it can produce _an equivalent_ connection string, but not its exact original connection string.

So yeah, that sounds like a useful idea!  Coming up with a really good API for it will take some work though:
 * I'd rather not commit to `std::map`.  It's unnecessarily specific, it's not particularly efficient, and tragically it _looks_ generic and specific.  I'd rather generalise that.
 * But then we run into overloading questions: Take a pair of iterators, or a reference to a container?  How do we generalise it without also getting overload clashes, perhaps in the future?
 * How do we pass the strings?  We can support `std::string` (really inefficient if you don't already have `std::string`), or `pqxx::zview` (might not construct trivially from the strings you already have), or C-style strings (which smells of C API leaking through), or `std::string_view` (which we'd need to copy in order to guarantee a terminating zero).  None of these is perfect for all cases, so we'll want to support multiple forms.

In C++20 I think we could more or less say "anything that we can iterate to get things that unpack to a pair of things that act like one of these string-like types."  So this might be a good place to start adding optional C++20 features.

**Comment by millnet-maho** [comment]
Maybe this is sloppy thinking, but isn't the level of inefficiency we're talking about here rather negligible compared to connecting to a database and running multiple queries? There typically won't be *that* many options either.

But order could matter(?) and at any rate it's at least possible to specify more than one `dbname` option, so a sequence of keyword-value pair is better.

**Comment by jtv** [comment]
If it's sloppy thinking then I've been guilty of it myself many times over.  :-)  I don't disagree with your reasoning.

_However_ the most important reason for people to use C++ these days is top-notch performance.  There might be someone who's making lots of quick connections for single queries _on a Unix domain socket,_ so connection overhead is minimal and now they worry about the extra overhead.

Plus, I can be a bit of a perfectionist at times and just don't want to embarrass my future self if there's a better way.

**Comment by jtv** [comment]
@millnet-maho I just pushed an experimental implementation!  Requires C++20 support (with concepts), and you must also `#define PQXX_HAVE_CONCEPTS`.  Please try it out and see what you think.

Right now there's nothing to define `PQXX_HAVE_CONCEPTS` automatically.  At first I only want  this code tested by people who know they're testing it and don't mind.

The next release will be 7.2.0.  I'm hoping to make some other changes before I release it.

**Comment by jtv** [comment]
For reference, I found I could compile the concepts code with gcc 10, but not gcc 9 or clang 10.  I had to pass `-std=c++2a` to get C++20.

**Comment by KayEss** [comment]
In my testing clang 10 and gcc 10 both compile concept code just fine, but only libstdc++ has the concepts header implemented. Oh and concepts are **really** good -- well worth the wait

**Comment by jtv** [comment]
Yes, I can feel concepts going into all sorts of places.  I imagine though that it'd be easy to go overboard, and create confusing or conflicting overloads.

@KayEss do you happen to know how legitimate my "if constexpr resize" trick is?  I did something like:

```cpp
  std::vector<...> outputs;
  if constexpr (std::ranges::sized_range<decltype(inputs)>)
    outputs.reserve(inputs.size());
```

**Comment by KayEss** [comment]
> do you happen to know how legitimate my "if constexpr reserve" trick is?

I **think** that depends on the wider context. If the code appears in a "templated entity" then it's probably OK, if it doesn't then it's probably not OK. I guess `input` is a templated argument so it ought to be fine.

**Comment by jtv** [comment]
Yes, exactly.  If it works, it's just wonderful: "What kind of range did I get here?  Do we know its size beforehand?  If so, pre-allocate room for just the right number of outputs."

**Comment by jtv** [comment]
I guess we can close this ticket now.  If there are problems with the new function, those can go into a new ticket.
