### ISSUE TITLE
provide test setup procedure

### ISSUE THREAD

**Issue by yscontrol** [jtv/libpqxx#347]
I built test executable runner_static.exe on ubuntu 16.04 from this source code and install it as well as postgresql-9.3.6 on W10 but  runner_static.exe  fails during execution bc the test routine did not start  postgresql-9.3.6  server. What is the test setup including steps to start and configure postgresql for libpqxx tests. Below is the error 

```Running: test_000
(Expected) Connection to database failed

Running: test_001
Exception: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
```

**Comment by tt4g** [comment]
The server will not be started by the unit test.
Make sure you have a server that can connect to the local host before you start testing.

**Comment by yscontrol** [comment]
If UT does not start server, then can you point to steps to start it
manually such that the libpqxx client test would pass. I could start server
like

psql -U *userName and CREATE DATABASE but this has to be done to match
parameters used by libpqxx test cases. So I wonder if instructions for
running libpoqxx tests ( to start and configure server parameters)
exists /*

**Comment by tt4g** [comment]
The unit test should not have specified any parameters for the connection.
Therefore, the connection is to localhost.
The user name and database name will be used as the name of the user running the unit test.

Sorry, I'm currently away from C++ development, so I'm not able to verify this behavior.

**Comment by GordonLElliott** [comment]
You guys are somewhat talking across each other, a bit.
 
There must be something similar on Ubuntu, but @yscontrol also mentioned Windows 10, I think. I didn't realize that the new libpqxx version 7.xx.xx worked all the way back to Postgres 6.3.6.

On windows 10, I know that installing versions 10,11, or 12 from the Windows intallation sets up if selected to automatically start a server when the operating system is booted. OR, when using pgAdmin it starts the server--I'm not entirely clear. When I run pgAdmin it shows all my servers as starting in any case. **And** I remembr that when I had version 8 installed things worked the same way, so the intermediates should also do so.

In the instructions for [BUILDING-cmake.md](https://github.com/jtv/libpqxx/blob/master/BUILDING-cmake.md#configuring-the-test-database) there is a section on configuring the test database which involves setting environment variables. The variables would be set to localhost default installation and use pgAdmin or psql to make a testing database (mentioned in the proper variable). @tt4g on Windows I couldn't use defaults on all the variables, had to set something. (I know nothing of what is needed on Linux.)

You pretty much need to install a local running PostgreSQL on Windows, that was required if using the windows binary installer in order to get the libraries needed--so this should be intalled. If used another method to install PostgreSQL on Windows, then I'm not sure what happens.

**Comment by tt4g** [comment]
> @tt4g on Windows I couldn't use defaults on all the variables, had to set something.

I forgot that environment variables are also used for connection parameters.

As far as I know, installing PostgreSQL in the Windows installer does not set any environment variables.
However, I don't know if the installation method is custom configured.

**Comment by jtv** [comment]
See the documentation in the source tree — `BUILDING-cmake.md` or `BUILDING-conifgure.md` depending on your build environment.  Look for the section entitled "Configuring the test database."

**Comment by GordonLElliott** [comment]
Sorry, I might have been confusing.

There are default values for each of the parameters needed. Indeed PostgreSQL installation does not set any of those, and each parameter starts with a default, then uses values from environment variables (only if set), then highest priority is values passed in connecting in C++. The runner program connect does not use command line arguments and the connection is constructed with no arguments, so default or enivrionment variable seems to be the only route to set. See @jtv 's note above on the "configure the test database" documentation.

In Windows the "peer authentication" is apparently not available, so the only way to pass the password seems to be [.pgpass or pgpass.conf file](https://www.postgresql.org/docs/9.3/libpq-pgpass.html) if you don't set an environment variable. Setting environment variables for password is generally not considered safe, so that pretty much leaves configuring the pgpass.conf file in Windows.

Remember

**Comment by yscontrol** [comment]
Sorry, I missed the [Configuring the test database]( https://github.com/jtv/libpqxx/blob/master/BUILDING-cmake.md#configuring-the-test-database) section, please close this issue

**Comment by jtv** [comment]
Ah right, yes, I restructured the build documentation in the 7.x series.  Sorry, it's hard to keep multiple timelines straight in one's head.

In your version, the text about running the tets would be in `README.md`, under `Building libpqxx` — the `Using CMake` section or `On Unix-like systems`, depending on your build system.  It's also explained in `win32/INSTALL.txt`, under `Running the test suite`.

**Comment by GordonLElliott** [comment]
I did notice and try an interesting method. This works in Windows 10, and I presume will work on other systems to some extent.
 
The default user is the computer user. But has to be exact case (upper/lower) as well.
Default database is likewise the exact user name, exact case.

So I set up a pgpass.conf file (naming in Windows-- .pgpass in Linux) which gives the password for the user automatically. Then set up both a database user and a database with that name (once again exact case, and I labeled it as just for test purposes).

The tests ran flawlessly without setting any environment variables.

(Anybody ever get a piece of lead type out of the "upper case" and the rest of the line of lettering out of the "lower case", setting the letters in a line, and printing from that?--**don't answer that! (not a forum),** but I have. Just if anyone was wondering where the term "upper case" came from. I don't know if Linux installs will have the same issues, but that was one reason I could not get that to work initially because of one or more type case errors.)
