### ISSUE TITLE
not support std::nullopt as NULL

### ISSUE THREAD

**Issue by gzliudan** [jtv/libpqxx#360]
When I pass std::nullopt as NULL, The compiler report below errors:
```bash
In function `void pqxx::internal::params::add_field<std::nullopt_t>(std::nullopt_t const&)':
undefined reference to `pqxx::nullness<std::nullopt_t, void>::is_null(std::nullopt_t const&)'
In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > pqxx::to_string<std::nullopt_t>(std::nullopt_t const&)':
undefined reference to `pqxx::nullness<std::nullopt_t, void>::is_null(std::nullopt_t const&)'
undefined reference to `pqxx::string_traits<std::nullopt_t>::size_buffer(std::nullopt_t const&)'
undefined reference to `pqxx::string_traits<std::nullopt_t>::into_buf(char*, char*, std::nullopt_t const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
When I pass std::optional<TypeName>(), the above erros disappears.

**Comment by jtv** [comment]
Yes, as far as I know `std::nullopt` exists specifically for initialising a `std::optional`, not as a general representation of a null value.  But supporting it sounds like a useful idea.

**Comment by jtv** [comment]
By the way, to generate an SQL null value, you can simply use `nullptr`.

**Comment by gzliudan** [comment]
Yes, I can use nullptr since I know data is null when coding. But support std::nullopt is also usefull, for example in ternary expression:  some_condition ? std:::optional<TYPE>(data) : std::nullopt

**Comment by KayEss** [comment]
A ternery expression only has a single type, it can't return one of two types. The type of your expression will always be a `std::optional<>` with the `std::nullopt` being lifted to the optional type when returned. As far as I know all expressions in C++ (that return values) are monotypical.

There are way too many unit types in C++ and I don't blame Jeroen for only wanting to support one (or two of them).

**Comment by gzliudan** [comment]
Below expression is valid in C++:
auto var = std::optional<int>(123456);
auto data = bool_expression ? var : std::nullopt;

If std::nullopt is supported as NULL, then our codes will be more simpler.

> A ternery expression only has a single type, it can't return one of two types. The type of your expression will always be a `std::optional<>` with the `std::nullopt` being lifted to the optional type when returned. As far as I know all expressions in C++ (that return values) are monotypical.
> 
> There are way too many unit types in C++ and I don't blame Jeroen for only wanting to support one (or two of them).

**Comment by jtv** [comment]
Yes, that ternary expression _works,_ but `data` will _always_ have the same type as `var`.  It's a `std::optional`, not a `std::nullopt`.

So in the case where `bool_expression` is false, you are constructing an empty `std::optional`.

**Comment by gzliudan** [comment]
But write std::nullopt is more handy than write std::optional<type>(), since nullptr is treated as NULL, std::nullopt can be as NULL for same reason.

**Comment by tt4g** [comment]
I'm not a native speaker, so if it's hard to understand what I'm trying to convey, please ask me questions.

IMO.

`nullptr` is keyword (literal) that is assignable pointer.
But `std::nullopt` is object.
This is a very big difference.

##### nullptr

`nullptr` can be assigned to any pointer.
Because this is a key word. The compiler interprets `nullptr` as an assignable pointer.

NOTE: `nullptr` does not have type.
Although there is `std::nullptr_t`, `nullptr` exists before `std::nullptr_t` because the specification defines `std::nullptr_t = decltype(nullptr)`.

##### std::nullopt

`std::nullopt` is a constant object of `std::nullopt_t`.
So, `std::nullopt_t foo = std::nullopt` can be compiled.

There is no inheritance relationship between `std::nullopt_t` and `std::optional<T>`.
However, `std::optional<T>` is initialized to the invalid state if `std::nullopt_t` is specified in the constructor.

Importantly, `std::nullopt` may be used in the future to initialize objects similar to `std::optional<T>` in an invalid state.
This is because `std::nullopt` is defined as an independent type from `std::optional<T>`.

If `std::nullopt` is used by any initialization other than `std::optional<T>`, the compiler will not be able to determine the type of `std::nullopt`.

**Comment by jtv** [comment]
Thanks @tt4g, looks perfectly clear to me!

@gzliudan, did I mention that you _can_ use std::nullopt in the current
`master`?  It was really easy to add, and it triggered a few other small
improvements as well.  So thanks for the suggestion.  :)

**Comment by gzliudan** [comment]
Yes, I saw your new commit which support std::nullopt as NULL, so I closed this issue. Thanks your hard work.
