### ISSUE TITLE
Add MD5SUM or SHASUM with releases

### ISSUE THREAD

**Issue by kriegalex** [jtv/libpqxx#370]
This is a nice to have when using automated scripts to install libraries. This avoids bugs when downloading the tarballs.

**Comment by kriegalex** [comment]
Here are a few to help

MD5SUM 6.4.7
```
7f873d3f1218bad43d78e6c2ba80caf4  pqxx-6.4.7.zip
702afa5a6501948af391b895b8e446bc  pqxx-6.4.7.tar.gz
```

MD5SUM 7.1.2
```
da1f5573575db4b03dcedf0a745d88e2  pqxx-7.1.2.zip
f4b2dab47bcb7c3e2152baa8003db51a  pqxx-7.1.2.tar.gz
```

**Comment by jtv** [comment]
To be honest, it's been a long time since I last saw data corruption during download that required a manual checksum to detect.  The compression algorithms have consistency checks built in, and of course an encrypted connection has very strong consistency checks as well.  I'll close the ticket for now, and reconsider if more people request checksums.
