### ISSUE TITLE
Help - upgrade from 6 to 7

### ISSUE THREAD

**Issue by Laro88** [jtv/libpqxx#387]
Hello.
We have used prepared statements with various parameters using the (x)(y)(z).exec() style - but looking at 7 things seems to have changed a lot.

We had:
```
Ctx.reprepare("update_planbasis", q.str());
pqxx::result r = Ctx.prepared("update_planbasis")(rPlanBasis.name)(rPlanBasis.comments)(rPlanBasis.draft)((int)rPlanBasis.planArea.type)(planid.AsInt()).exec();
```
which is (was?) nice to work with as we made a small container class (Ctx)  where we have a reprepare function that allows us to "reprepare" a query what we then can use in Ctx.prepared as the Ctx.prepared function returned an pqxx::prepared::invocation object.

What is the recommended upgrade strategy from 6 to 7 - are there any documentation on this available?

Yours sincerely
Laro

Btw. I will upgrade to streaming when I have solve this little issue :-)

**Comment by tt4g** [comment]
Try to use `pqxx::connection::prepare()` and `pqxx::connection::exec_prepared()`.

See: https://libpqxx.readthedocs.io/en/7.2.1/a01352.html

**Comment by jtv** [comment]
What @tt4g said.  ☺

I hope you'll like the new API for this.  You now pass the arguments like...

```cpp
    Ctx.exec_prepared(
        "update_planbasis",
        rPlanBasis.name, rPlanBasis.comments, rPlanBasis.draft,
        (int)rPlanBasis.planArea.type, planid.AsInt());
```

I think it's easier to read, as well as cleaner internally.  But also, it eliminates some pitfalls where the old API more or less invited people to use the intermediate objects in unsupported ways.

**Comment by Laro88** [comment]
Work in progress - have +150 (x)(y)(z).exec(); calls to convert before I can start unittesting :-)

What is the appropriate way to handle the conditional null inserts like below?
```
exec_prepared("create_image")
(rImage.imageid.AsInt(), rImage.imageid != Xobjects::NO_ID) //NULL if not set to valid condition
(rImage.scale)
(rImage.orientati ...
```
We have them in the design and they are hard to get rid of due to other applications using the database.

**Comment by jtv** [comment]
Pass a `std::optional<int>`.

**Comment by jtv** [comment]
@Laro88, mind if I close this issue now?

**Comment by Laro88** [comment]
I think things are fine, haven’t ben able to test it as we have an old Corba dependency that is a bit tricky....

**Comment by jtv** [comment]
Corba!  It's been a while since I last heard that name.  Good luck.  :-)

**Comment by zvalcav** [comment]
Hello,

thanks for all your effort with pqxx. I really like it and use it in many projects. I've similar problem, like Laro88.

> I think it's easier to read, as well as cleaner internally. But also, it eliminates some pitfalls where the old API more or less invited people to use the intermediate objects in unsupported ways.

By unsupported way you mean for example passing pqxx::prepare::invocation object as reference to different functions to fill all the necessary values? Because now I'm stuck and have to rewrite everything in my projects that uses prepared insert statements or keep 6.2 as long as it works with postgresql.

How can I accomplish something similar? Will filling the vector of strings and passing it as parameter to exec_prepared work? What about null values? Old API was more object friendly as it seems to me. Without the ability to "fill values in propper class" I would have to pass all values in every inherited class. But every change in table structure would require change in every class.

**Comment by jtv** [comment]
For a vector of values, have a look at dynamic_params.

There's several ways to pass nulls: if your parameter's type is char * you
can pass a null pointer; or you can use std::optional, shared_ptr, or
unique_ptr.

**Comment by zvalcav** [comment]
Thank you for reply. I've checked dynamic_params. However I'll keep 6.2 in use for a long time. Its original approach seems much more readable to me.

**Comment by jtv** [comment]
That is sad to hear, because I thought the new parameter style would be a
lot more natural and easy to read!  At least for cases where you know the
number and type of the parameters at compile time.

I'm wondering...  Is there anything I could do to make dynamic parameters
more pleasant for you?  Make the API richer?  Allow conversion from any
container type or sequence to dynamic_params?  What kind of thing do you do
with it that's harder with the new API?

**Comment by zvalcav** [comment]
Hi,

Sure, I totally get it and in most cases it will be more natural and easier to read.

In my case however it is not always true. I have a lot of cases where I just insert all the values in one place, put lot of values in ()() chains and finally call exec(). However I have a lot of values in log tables and to save some space I'm inserting NULL instead of 0 wherever possible. It helped me save about 20% of disk space.

I'm creating pqxx::prepare::invocation as object which I pass through all inherited classes and check if there is any value to insert or insert NULL. Invocation is(was) very good for this with its operator()(). Even null value was pretty easy to insert. Try to imagine how much time will someone spend (even myself after year or two) trying to figure out why the hell there is empty shared_ptr in the middle of insertion process. May be creating some predefined object to represent NULL value may make it easier too in case of vector<string>.

I know all the parameters and type at compile time, but my log tables have a lot of columns and writing all insert statements for each inherited class would be pain to write, debug and even in case of change of number of columns in database it would require to change all the functions. Not to mention all the ternary operators in exec_prepared params. With old approach I need to change table, prepared statement and one function and I'm done. I thought about passing vector<string> instead of invocation, but I stopped at first occurrence of condition to insert value or NULL. Not sure whether std::string would pass null termination properly or should I pass vector<const char*> or char** which would take me so close to pure C that there won't be much difference between pq and pqxx. All of it would make my code less readable and to be honest, PostgreSQL needs to know whether there is value or NULL and not something that tries to represent it. Invocation() was pretty straight forward. I can't use your tip to use nullptr, shared_ptr, unique_ptr since I can't put them inside of vector<string>.

I hope it should not be that hard to preserve some alternative to invocation, which served my purpose perfectly. Object, to contain all the passed values, even NULL ones, and just make dynamic_params process this object, not just stl container which is much harder to convince to accept different types of values.

I understand your approach. I'm also trying to do things more readable, easier to use, free of old stuff etc. But with your library, which must be used world wide, there are some more things to consider. I was using libpqxx-dev since Debian Stretch (4.0 in repos). Buster has 6.2 in repos and it works well too and there is no compilation warning about deprecation of prepared. But on my new Laptop I had to switch to Ubuntu (6.4.5 in repos) and that is how I came to this problem with compilation warning. Version 7.0+ without this functionality will be potential show stopper for users using repo versions in the future.

**Comment by jtv** [comment]
Sure you can insert smart pointers in vectors!  And I'm not sure off the top of my head, but I think even `unique_ptr` thanks to the magic of move semantics.  _Creating_ those smart pointers was made easier by `std::make_unique` and `std::make_shared`, too.

Another way to allow nulls is `std::optional`.  And if you've got multiple types of parameters, even `std::variant` will work!  So you can have a vector of arguments that each individually might be a string, an integer, a `double`, a composite object, and so on — and turn them all into a dynamic parameters array using `pqxx::make_dynamic_params()`.

**Comment by zvalcav** [comment]
Sure, I can do it this way, but we are back at the beginning. So I'll say it again, I'm going to stick with 6.2 for a long time. Thank you for your time. FYI https://en.wikipedia.org/wiki/KISS_principle

**Comment by jtv** [comment]
I'm well aware of the KISS principle!  The new way of working allowed me to
reduce complexity.  I'll think about ways to facilitate a Builder pattern
on top of that.

**Comment by jtv** [comment]
@zvalcav I've built something that should do what you need, but as an actually supported API this time.  See the `params-builder` branch.

(And don't worry, it's not actually called "params builder."  The new class is called just "params" and I think you'll like it.)

**Comment by zvalcav** [comment]
@jtv params look very promising :-) Thank you.

Good you are aware of KISS principle. I didn't mean it as any offense. Just it is often best to fix problem where it can be fixed most easily, which you did very well.

There could be potential limitation in this template function, since `std::to_string` doesn't handle double and long double well. It has limitation which I encountered recently in one of my projects where I needed more than 6 decimal digits precision. Better solution is usage of `std::stringstream` in combination with `std::fixed`. Something similar to this solution: https://stackoverflow.com/a/16606128/8870620

```
template<typename TYPE> void append(TYPE const &value)
  {
    // TODO: Pool storage for multiple string conversions in one buffer?
    if constexpr (nullness<strip_t<TYPE>>::always_null)
      m_params.emplace_back();
    else if (is_null(value))
      m_params.emplace_back();
    else
      m_params.emplace_back(entry{to_string(value)});
  }
```

I suppose that to pass NULL value you would .append any of the possible representations for null you mentioned earlier to params, right?

**Comment by jtv** [comment]
Thanks @zvalcav.  I must say I was a bit annoyed at that KISS link.  :-)

The conversions of floating-point numbers are a completely separate issue really; that's generic throughout libpqxx.  I do actually fall back on `std::stringstream` if there is nothing better available, but I see now that I never actually set the _precision_ for that stringstream.  If the compiler is more modern, you get `std::to_chars` — but sadly g++ and clang++ don't have that yet.  I had been hoping that this would work out sooner.  I'll have to file a separate ticket.

**Comment by zvalcav** [comment]
What about adding `void operator()()` to params to preserver current functionality of passing NULL value? I feel comfortably with the old approach and it could be better for readability than passing shared_ptr or something similar.

**Comment by jtv** [comment]
Sure.  It's a named function of course, not `operator()`, but I can add one without a parameter for null values.

By the way I'm looking again and it does look as if I set the right precision for that stringstream...  Where did you see it go wrong?

**Comment by zvalcav** [comment]
Sure. append() would make it too.

It is here https://github.com/jtv/libpqxx/blob/params-builder/include/pqxx/prepared_statement.hxx#L194. But now, on second look I've noticed it is `pqxx::to_string` and not `std::to_string`. Sorry for wrong assumption.

**Comment by jtv** [comment]
Ah.  No, can't use `std::to_string` because it applies a locale.  But `pqxx::to_string` does use `std::to_chars` where possible.
