### ISSUE TITLE
Check if connection has active worker

### ISSUE THREAD

**Issue by noctera** [jtv/libpqxx#396]
I couldn`t reopen the last issue so I created a new one.
I continue from this issue  [393](https://github.com/jtv/libpqxx/issues/393)

I`m programming the pool of connections right now.
My class has a vector of connections
```
std::vector<pqxx::connection> connectionPool;
```
that get`s initialized in the constructor
```
Database::Database(std::string dbName, std::string userName, std::string password, std::string hostAddress, int port)
{
	conn = "dbname = " + dbName + " user = " + userName + " password=" + password + " host=" + hostAddress + " port=" + std::to_string(port);
	//initialize the connection pool
	for (int i = 0; i < 200; ++i)
	{
		connectionPool.pushBack(pqxx::connection(conn));
	}
}
```
Now I want to create a function that returns the reference to a connection if the connection is free
```
pqxx::connection &Database::getConnection()
{
}
```
But now I have problems. How can I check if a function has an active ```pqxx::worker``` prozess running.
Could someone help me?
Thanks in advance :)

**Comment by jtv** [comment]
There is no `pqxx::worker`...  To confirm that I understand you right: you're asking for a way to know whether a connection in your pool is _currently in use_ by your application?

That is something that you'll need to track yourself.  Otherwise you'd get either race conditions (a thread locks the pool, grabs a connection, unlocks the pool, but before it can "activate" the connection another thread does the same thing and gets the same connection because it's not "active" yet), or longer locking times (thread locks the pool, grabs a connection, "activates" it in some way which may take time, and unlocks the pool).

By the way, be careful with `std::vector` here.  If you ever change the size of the pool after you start using it, that may move the connections to new memory locations and break everything.

**Comment by noctera** [comment]
So my idea was ti have a pool if connections laying around. Every function that needs database access calls a function that is returning a reference to a connection object, that is currently free. And with this reference the worker object gets initialized with the reference of the connectiom object. 
But I think this idea won't work

**Comment by noctera** [comment]
Or should I create a connection object on every request and give it to the database class

**Comment by tt4g** [comment]
<summary>

Example for proxy-pattern implementation.

<details>

```cpp
#include <iostream>
#include <queue>
#include <mutex>
#include <memory>

class Pool 
{

    // Forward declaration
    class Proxy;

public:
    
    Pool() : 
        mutex_(),
        pool_()
    {
        for (int i = 0; i < 10; ++i) {
            this->pool_.push(std::make_shared<int>(i));
        }
    }
    
    ~Pool()
    {
        // Clear std::queue.
        this->pool_ = std::queue<std::shared_ptr<int>>();
    }
    
    std::unique_ptr<Pool::Proxy> getProxy()
    {
        return std::make_unique<Pool::Proxy>(*this);
    }

private:

    class Proxy
    {
    public:

        Proxy(Pool& pool) 
            : pool_(pool),
              connection_(pool.pop())
        {

        }
        
        ~Proxy() {
            this->pool_.push(this->connection_);
        }
        
        int& getConnection()
        {
            return *this->connection_;
        }
        
    private:
        Pool& pool_;
        std::shared_ptr<int> connection_;
    };

    std::shared_ptr<int> pop()
    {
        std::lock_guard<std::mutex> lock(this->mutex_);
        
        std::shared_ptr<int> con = this->pool_.front();
        this->pool_.pop();
        
        return con;
    }
    
    void push(std::shared_ptr<int> con)
    {
        std::lock_guard<std::mutex> lock(this->mutex_);
        
        this->pool_.push(con);   
    }
    
    std::mutex mutex_;
    std::queue<std::shared_ptr<int>> pool_;
};

int main()
{
    Pool pool;
    
    for (int i; i < 20; ++i) {
        auto proxy = pool.getProxy();
        
        std::cout << "i=" << proxy->getConnection() << std::endl;
    }
}
```
</details>
</summary>

[Wandbox](https://wandbox.org/permlink/0SdsOqD0uDLTyZal)

**Comment by jtv** [comment]
@noctera Your idea sounds just fine to me, so long as:
 1. Your worker _releases_ the connection after use, so that the pool can give it to a thread once again.
 2. The connection objects don't get moved to different memory locations.
 3. Errors are handled well, e.g. sometimes you may need to close a connection and start a new one.

**Comment by noctera** [comment]
Thanks. I just have to find the best workaround for it. Right now I`m creating a new connection for every method. But when there are 1000 requests at once the server gets locked up with a segmentation fault, because to many objects are created. But maybe some reason is also the Worker, that gets created on every method call. You can see, it's a little bit difficult, but I think I can solve it somehow

**Comment by jtv** [comment]
If most of your threads will need a database connection, then the answer is simple: you should just have the same number of connections as workers.

**Comment by jtv** [comment]
I'll close this ticket then.  Feel free to open a new one if there is another problem or question.  Happy new year!
