### ISSUE TITLE
Concrete instantiations of STL template types in API surface

### ISSUE THREAD

**Issue by elelel** [jtv/libpqxx#427]
libpqxx makes assumptions about concrete STL containers that are used to interface with it's functions. For example, after the recent change to largeobject/blob the reading functions take std::basic_string<std::byte> as the buffer to read blob into. There may be quite a lot of debate what stdlib containers are the "correct" way to store binary blobs (vector? spans? strings? of std::byte? of char? of uint8_t?), but whatever the choice is, the fact is that there is no de-facto concensus and to bridge two libraries that use concrete STL types one usually has to use some way of type-unsafe recasting and/or C-style functions with func(void* buf, size_t sz) signatures. That what I currently do, though libpqxx doesn't provide C overload, other libraries do, so I can feed {basic_string.data(), basic_string.size()} to them after reading a blob with libpqxx. What I can't workaround is memory allocation control. I would like to be able to use std::pmr:basic_string instead, but there's currently no way for that with libpqxx, other than just falling back to libpq API that let plain buf*/size calls.

There are two ways out of this: attempt to provide overloads for the possible types plus a fallback with pass-through buf*/size to C api, or use generic stl structures in generic programming way in lib interface. The latter is preferable, but that means more work and making the library much more header oriented.

**Comment by jtv** [comment]
I had a slightly different direction in mind, using C++20: read into a `std::span<std::byte>` so that resizing is entirely under your own control, and all the details that bother you become more or less irrelevant.

All the use of `std::basic_string<std::byte>` and `std::basic_string_view<std::byte>` is really just provisional until we can do that.

I do stand by `std::byte` as the right choice though.  It is exactly the type we want.  I don't think integration with other languages and libraries is a good argument against that, in that the argument can be applied equally to `char` and `unsigned char`, and I'm not going to support all 4 directly.  If you're going to cast, `std::byte` seems like the right type on the C++-native side.

**Comment by elelel** [comment]
I think that the "correct" way would be using the approach C++ and STL uses since C++98 which is generic programming. The interface should be something like std::copy https://en.cppreference.com/w/cpp/algorithm/copy which does not care about the concrete types. It's very natural with blobs. All we need to know to read a blob that the destination can fit certain amounts of bytes and there exists an operation to write them. We do not need to impose a restriction that it is some sort of container, we do not need to know a thing about it's element and say "hey the correct way to call these separate thingies bytes or something". This approach didn't change in C++20.

C++20 spans are more restrictive than C void* buffers. In particular, you can't create them from c pointers. It's tempting to think about them as string views, but they are not equivalent. Unlike string_view you can't construct them from pointer with dynamic buffer size. 

Regarding the details that bother me, right now I simply can't use blobs with libpqxx, though I'm on C++20 :) To actually use it, I patched it as in PR and use void*/sz paththrough.

**Comment by JadeMatrix** [comment]
> C++20 spans are more restrictive than C void* buffers interface. In particular, you can't create them from c pointers unless the size is set on compile time.

You can create a span with dynamic extent (the default) from a pointer+size or begin+end pointers, since pointers are iterators.  I'll agree you still need to keep track of the size, unless it's a C array that hasn't decayed to a pointer.

But I agree an interface similar to `std::copy()` would be better, as that works naturally with things like [`std::back_inserter`](https://en.cppreference.com/w/cpp/iterator/back_inserter).  `std::span` doesn't appear at first glance to work with `std::back_inserter` ([link](https://godbolt.org/z/TPqf54Grb)) as it can't calculate a size (makes sense).

**Comment by elelel** [comment]
> since pointers are iterators. 

Good point that I completely missed! 

> But I agree an interface similar to `std::copy()` would be better, as that works naturally with things like [`std::back_inserter`]

Making it an algorithms-like function would be perfect. For now I would be quite satisfied with much more modest changes:
- Don't force the container of BLOB to be of some particular type. It's a BLOB, the reading function doesn't need to know anything about the nature of underlying data other than it's total size. Not doing essentially forces copying the container to convert it to std::sting_view<some_other_T>.
- Don't force the container's Allocator parameter on user but leave it as it was declared in libstd
- Don't fiddle with memory-affecting functions like here: https://github.com/jtv/libpqxx/blob/91fbad7d1aea5417f2c51555832ceeeb29f26faa/src/blob.cxx#L144

Here are the motivating example of resize misuse. Please, correct me if I'm wrong.
```
  // Allocating 4GB of memory at single point when reading two 2GB blobs one after another
  size_t blob1_sz = 2GB -1;
  size_t blob2_sz = 2GB;
  pqxx::blob iblob = pqxx::blob::open_r(t, oid1);
  std::basic_string<std::byte> buf;
  iblob.read(buf, blob1_sz); 
  // ^^^ Before reading allocates 2GB - 1 by calling resize(). Wastes resources for writing out 0s
  iblob.read(buf, blob2_sz); 
  //  ^^^ Potentially allocates 2GB more. If you dont' have 4GB in total for the buffer you are in bad_alloc state
  // Then zeros out the whole new buffer, if it wasn't realloc style buffer extension for trivially-constructibles
  // Then copies the old 2GB - 1 into new buffer over the zeros
  // Then the old 2GB - 1 buffer is released
  // Then zeroes that were overwritten with old BLOB are now overwritten with blob2
```

**Comment by jtv** [comment]
Okay, we'll do a `std::copy`-like interface then.

@elelel there's no need to "sell" me on the benefits of templates — that is not the issue here at all.  Been a big fan for almost a quarter century, and I always wanted to support a freer range of containers.  It's just that I expect Concepts to rock our perspective on these things, and I left some room for C++20 improvement without "crowding" the overloads.

For a bunch of reasons I never really liked the practice of wrapping container extension in an output iterator, but I do accept that there were probably good reasons.  Let's just hope the reason wasn't merely "passing callbacks was too awkward before we had lambdas."  ☺)

All that said, I still think there will be a place for a `pqxx::blob::read(std::span<std::byte>)`.  Let's not forget that _the caller specifies the maximum size_ here.  So it's not as if the size will ever be a surprise.  I think it'll be both clearer and potentially more efficient to let the caller handle the sizing.

**Comment by jtv** [comment]
Actually I'm way off with my years.  I fell in love with C++ templates in the _early_ 1990s, not the _late_ 1990s.  Heavens, I feel old.  :-D

**Comment by elelel** [comment]
> there's no need to "sell" me on the benefits of templates — that is not the issue here at all.
Sorry, I didn't mean to be pushy even if it may have sounded so. For many years libpqxx was one of the very few major C++ libraries that were STL components and concepts-aware (in non-codified C++20 meaning of that word) and it would be very silly on my part to claim there's any template aversion here.

> All that said, I still think there will be a place for a `pqxx::blob::read(std::span<std::byte>)`. Let's not forget that _the caller specifies the maximum size_ here. So it's not as if the size will ever be a surprise. I think it'll be both clearer and potentially more efficient to let the caller handle the sizing.

What I meant is that the caller specifies two sizes: one that comes with base_string and the one as the function's parameter. So he needs to 1) realize that there's the first one hidden in the container and 2) the second size will be somehow recinciled with the state of the first one. Potentially by copying memory back and forth :)

**Comment by jtv** [comment]
Thanks for your kind words @elelel.

The idea of a `span` version is that you will pass only one size.  It's just "this is my buffer; please try to fill it."  You could pass a `basic_string<byte>` and I think that would be automatically converted to a `span` of the correct size.

It would be up to you to make the buffer as large as you wanted it, so if you use a `string` you'll want to `resize()` it before calling `blob::read()`.  You might even get a `span` back, instead of a size, if that's more convenient.  Of course you could construct the `span` out of a `void *` and a `ptrdiff_t`, or whatever else.

Now that I'm thinking about it again...  One complication with a `std::copy`-like version of `blob::read()` is that most of the work happens inside libpq.  There's no C++ code at all that deals with the bytes on a one-by-one basis.  Is there a good way to represent that as an output iterator?  (Without adding an extra copying pass, of course.)

**Comment by jtv** [comment]
(And by the way, @JadeMatrix good to see you again!)

**Comment by JadeMatrix** [comment]
@jtv I've been stayed kind of busy and haven't kept up with `libpqxx` recently; sounds like there's been quite a bit of progress since v6.

I just saw this pop up in my notifications and wasn't particularly paying attention to the context here; my main point was it's possible to have dynamic spans and spans from raw pointers.  Sounds like `std::span<std::byte>` is the correct interface in this case.

**Comment by jtv** [comment]
Say @elelel, do we still need this ticket?  If not, I'll close it.  Tickets have been piling up again.

**Comment by elelel** [comment]
No, sorry that I didn't close it earlier.
