### ISSUE TITLE
Crash on repeated construction/destruction of pqxx::connection

### ISSUE THREAD

**Issue by apophis666** [jtv/libpqxx#430]
Hi, 
I think i've found a bug in libqpxx 7.2.0. 

The following code causes a crash:

 ```
  for (int i = 0; i < 100000; i++) 
   {
        pqxx::connection con("host=localhost dbname=csp_store user=user password=password");
        if (i % 1000 == 0)
            std::cout <<" i : " << i <<  std::endl;
   }

```

Running on
$ uname -a
FreeBSD sonicyouth 12.2-RELEASE-p4 FreeBSD 12.2-RELEASE-p4 GENERIC  amd64

$ pkg info postgresql-libpqxx
postgresql-libpqxx-7.2.0
Name           : postgresql-libpqxx
Version        : 7.2.0
Installed on   : Sat Feb  6 22:02:43 2021 CET
Origin         : databases/postgresql-libpqxx
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : databases
Licenses       : BSD3CLAUSE
Maintainer     : pgsql@FreeBSD.org
WWW            : http://pqxx.org/
Comment        : New C++ interface for PostgreSQL

I have a PoC, not sure where to drop it though.

**Comment by jtv** [comment]
Can we see the try/catch block that's around this loop?  I assume you did
something like

    try
    {
        for (int i = 0; i < 100000; i++)
        {
            pqxx::connection con("host=localhost dbname=csp_store user=user
password=password");
            if (i % 1000 == 0)
                std::cout <<" i : " << i << std::endl;
        }
    }
    catch (std::exception const &error)
    {
        std::cerr << error.what() << '\n';
    }

Because I don't see what could crash that loop itself, but of course it may
produce an exception sometimes.  From what you say you must be trying to
handle that exception (because otherwise, duh, an unhandled exception will
cause a crash :-) and sometimes things go wrong there.  In particular, some
compilers have trouble throwing and catching exceptions across
shared-library boundaries.

**Comment by apophis666** [comment]
Thanks, my PoC indeed throws an exception with a trivial error that explains the crash. This makes me realize I've probably drawn a conclusion to quickly. The code I'm using this in does not seem to throw anything. As it is more likely that I made an error in my own code I want to apologize for wasting your time and head back to my debugger.

**Comment by jtv** [comment]
It happens.  Best of luck!
