### ISSUE TITLE
configure / make based install does not install documentation while CMake installation based install does

### ISSUE THREAD

**Issue by loqs** [jtv/libpqxx#436]
Building with the 7.4.1 tag also applies to current master ed38623d831d5d1147fa381e86d5c738f634b920
Using configure / make the documentation is built but not installed with:
```
./configure --prefix=/usr  --enable-shared --enable-documentation
make
make prefix=/usr install
```
Using CMake the documentation is built and installed with:
```
cmake -B build -S "${pkgname}-${pkgver}" \
      -DCMAKE_BUILD_TYPE:STRING='None' \
      -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
      -DBUILD_SHARED_LIBS:BOOL='ON' \
      -DBUILD_DOC:BOOL='ON' \
      -Wno-dev
make -C build
make -C build install
```
Is this difference intended?

Adding the documentation to install-data-local in doc/Makefile.am with the following installs the documentation:
```
install-data-local: reference
       $(MKDIR_P) $(DESTDIR)$(datadir)/$(PACKAGE)/doc/html/Reference ; \
         for file in html/Reference/* ; do \
           if test -f $$file ; then \
             $(INSTALL_DATA) $$file $(DESTDIR)$(datadir)/$(PACKAGE)/doc/html/Reference ; \
           fi ; \
         done ;
```
However it installs the documentation all the time irrespective of BUILD_REFERENCE.

**Comment by jtv** [comment]
Not exactly intended, no...  If we build the documentation I guess we might
as well install it.

Does anyone particularly want the documentation installed though,
nowadays?  For me it's easier to read the online documentation than to look
it up locally.  I still use "man" because it's so ridiculously fast and
easy to access, and eliminates doubt about forks and version differences.
But once I've got to open a browser, I might as well do an Internet search.

**Comment by jtv** [comment]
So...  Are there any strong conventions on what an automake build would normally do when it comes to documentation, and what a CMake build would normally do?

If not, maybe the automake build should just not build documentation by default, saving some build time.  I think automake projects do traditionally build docs, but in different formats which aren't all that relevant nowadays.

**Comment by tt4g** [comment]
As far as I know, there is no convention in the files that are normally installed in a project with CMake.
It is configured so that most projects will be installed in the installation path used by the C/C++ library.
An option is available to copy additional license files and install documentation.

I think the installation target is freely decided by the project.

IMO: There is no restriction that autotools and CMake must be able to install the same files.
Each of them has their own strengths and weaknesses, and you should not force them to do something they are not good at.

**Comment by jtv** [comment]
Exactly @tt4g.  I would like the CMake build to do what's conventional for a CMake build, and the autotools build to do what's conventional for an autotools build.

But if there are no clear conventions, I'm not particularly motivated to make any chages here.  There's things to be said for all three defaults: don't build the docs, or build them so you can read them locally but without installing them, or build and install them.  I have no strong feelings about it, and I'm waiting for someone to _give_ me a reason to care.  :-)

**Comment by jtv** [comment]
Cleaning up old tickets.
