### ISSUE TITLE
Connection error not caught in try/catch

### ISSUE THREAD

**Issue by AgatheLagache** [jtv/libpqxx#449]
Hello, 

I am using a simple C++ console app and libpqxx 7.3.1 to communicate with a PostgreSQL 13 database. I get some trouble when trying to connect to the database. Here is my code :

```
#include <iostream>
#include <pqxx/pqxx>

int main() {
    try {
        pqxx::connection c{ "postgresql://postgres:password@localhost/database_test" };
        if (c.is_open()) {
            std::cout << "Opened database successfully: " << c.dbname() << std::endl;
        }
        else {
            std::cout << "Can't open database" << std::endl;
            return 1;
        }
        c.close();
    }
    catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
    }
}
```

There is no problem during compilation, but when the program is executed, it returns this error, which is not detected by the try/catch :

> Exception lifted to 0x00007FFA508B0157 (pqxx.dll) in ConsoleApplication1.exe: 0xC0000005: Access violation when reading location 0x0000000000000010.

In the console, I get the cout "`Opened database successfully: database_test`" but in the msg of the error seems to close the connection : `0x00007ffa508d7928 "Closing connection with outstanding receivers."`.

Do you know why this error is not caught by the try/catch ?
Thanks

**Comment by KayEss** [comment]
An access violation is the same as a segfault on Unix systems and you're getting this because a NULL pointer is being dereferenced. These aren't exceptions so can't be caught as such. I think Windows provides some APIs that allow them to be handled, but I don't know the details. Typically you should strive to never have any.

I don't see any obvious error in the code that would cause this, but then I don't see anything that would print `0x00007ffa508d7928 "Closing connection with outstanding receivers."` either.

**Comment by jtv** [comment]
Could this be a case of Debug code being linked against Release code?

(On an unrelated note: you don't need to check whether `c.is_open()`.  If the connection fails, you'll get an exception.)

**Comment by jtv** [comment]
To be clear: I think this is a problem of Release vs Debug code because what's happening is, at the C++ level, clearly and totally insane.  From the point of view of the C++ code, calling libpqxx in this way would never produce this kind of outcome.

So I think libpqxx is receiving a bogus pointer from your code, probably because the two binary components disagree about where things are in memory.  That typically happens when you compile one part of the code in Release mode and the other in Debug mode.

**Comment by jtv** [comment]
@AgatheLagache any progress?

**Comment by AgatheLagache** [comment]
Indeed, it was a problem caused by the Debug code. With the Release code, I didn't have any error.
I think the issue can be closed as it was not a problem from the library, thanks for your explanations !
