### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by vitruvvius** [jtv/libpqxx#470]
Is it possible to bind arrays in the following example?

/*
void prepare_find(pqxx::connection &c)
{
  // Prepare a statement called "find" that looks for employees with a
  // given name (parameter 1) whose salary exceeds a given number
  // (parameter 2).
  c.prepare(
        "find",
        "SELECT * FROM Employee WHERE name = $1 AND salary > $2");
}
This example looks up the prepared statement "find," passes name and min_salary as parameters, and invokes the statement with those values:

pqxx::result execute_find(
  pqxx::transaction_base &t, std::string name, int min_salary)
{
  return t.exec_prepared("find", name, min_salary);
}
*/

with say a std::vector<string> ??

this is the primary feature i'm looking for in a sql library since using SELECT * FROM UNNEST enables one to do batch inserts

**Comment by jtv** [comment]
To make the example a bit clearer...  Are you looking for a way to do the
same thing except with an array of names?  You can use std::vector as an
SQL array, though off the top of my head I'm honestly not sure if that
works as a parameter in a prepared statement.  I'm away from my computer at
the moment.  I'd say give it a try!

(In general, yes, libpqxx recognises a std::vector and translates it to its
SQL equivalent using an array.  But prepared statement parameters are a bit
of a special case with the underlying libpq library.  That's why I always
need a bit of wiggle room for those.)

But -- if what you really want to do is efficient batch inserts, there's a
simpler thing you can try.  Use pqxx::stream_to.  This will let you stream
a batch of items directly into a table, and it's quite efficient.

**Comment by vitruvvius** [comment]
thank you! i'm a bit confused how to bind parameters w/out a prepared statement - unless i'm missing something from looking through unit tests / documentation

**Comment by vitruvvius** [comment]
as a side note, i'm currently wrapping this library into an imperative approach in executing statements using coroutines. if you happen to still be thinking about async c++, i'd highly reccomend that you check out the rust crate sqlx. their API is quite nice from prior experience

**Comment by jtv** [comment]
Sorry if I was unclear — I was referring not to other cases of binding parameters (although there is one such case: parameterised statements) but to other cases where libpqxx converts values between C++-side types and SQL textual representations.

Anyway, definitely have a look at `stream_to`.  It may save you some complexity and it's generally quite fast.

The problems with async at the moment, for me, are very C++-specific.  I don't think looking at Rust is going to help there.  They are (1) insufficient compiler support, (2) the problem of fitting the right kinds of waiting into the calling application, and (3) the very low-level nature of the async API as it stands.

**Comment by vitruvvius** [comment]
although the semantics are different, sqlx and other drivers have much better API and for a library used as much as this, it would make sense to review a success story
