### ISSUE TITLE
Build failed on windows with non-constant expression

### ISSUE THREAD

**Issue by KuddelSK** [jtv/libpqxx#472]
Building on Windows results in an "non-constant expression.." error in connection.cxx line 979. I fixed it locally by changing the line to: 
`short const events{static_cast<short>(forwrite ? POLLWRNORM : POLLRDNORM)};`
similar to the conversion few lines below it.

**Comment by StefanKramer** [comment]
I used clang-cl version 12.0.1 for the build. But i don't think that it depends on the compiler version as the c-runtime header are taken from the Windows SDK.

**Comment by jtv** [comment]
Thanks.  I think what happened is this:
 * `POLLWRNORM` and `POLLRDNORM` are `short` constants.
 * There is no `short` version of the ternary `:?` operator.  So it coerces the values to `int`.
 * The truncating conversion back to `short` is probably technically non-const.

Of course I expected compilers to compute the truncation at compile time, and happily accept it without error because they can see that there's no funny business.  But the details may depend on how Windows defines those two constants.
