### ISSUE TITLE
Inserting array of data (Like float)

### ISSUE THREAD

**Issue by Dashing-Nelson** [jtv/libpqxx#479]
Hello,

first of all, great library. I am a bit stuck on what would be the best way to insert array of floats in the table using stream_to write_values. I know we could convert the array to (char *). But would there be any better way? this was when I was using pure libpq.

`char *convertFloatArrayToChar(const float floatArray[], const int size)
    {
        std::string value = "{";
        if (size > 0)
        {
            for (int i = 0; i < size; i++)
            {
                value.append(std::to_string(floatArray[i]) + ",");
            }
            value.pop_back();
        }
        value += "}";
        char *cstr = new char[value.length() + 1];
        strcpy(cstr, value.c_str());
        return cstr;
    }`

**Comment by jtv** [comment]
Thanks!

There _is_ a better way, yes — but I'll be the first to admit that we can make it a lot better in C++20.

If you just insert a `std::vector<float>` into the stream as a field value, (or a vector of anything, really), the stream will automatically represent that value as an SQL array.

**Comment by jtv** [comment]
Addendum.  This trick also works for `std::array<float>`.  Or `std::vector<int>`, and so on and so on.  Even nested arrays should work.  But with C++20's notion of Concepts, I'd like to make this array support a lot broader in the future.  I'd like to support the same thing for any other kind of container.

One complication is that a `std::string` is a container of `char`, but obviously you wouldn't want to treat it as an SQL array.  Of course libpqxx does not support `char` as a value type (because it's a bit too ambiguous to be safe), but I'd also have to be sure that `std::basic_string<std::byte>` works, for example.

**Comment by Dashing-Nelson** [comment]
sure sounds good! this code worked for libpq but it seems there is a better way! thanks alot!
