### ISSUE TITLE
Delete row of pqxx::result

### ISSUE THREAD

**Issue by nthung11cist** [jtv/libpqxx#497]
my code:
result = work.exec("SELECT * FROM table_name")
for (temp : result ) {
  append temp to output
  delete result[temp_index]
}
I want reduce memory, but dont know how to delete result at temp_index. i use libpqxx 4.0.1 ubuntu 18
please help. thanks so much!

**Comment by jtv** [comment]
You can't delete or modify data in a `pqxx:result`.  Even if you could, it would not reduce the _peak_ memory consumption: there would still be a time where you'd have the whole result in memory.

If that is a problem for your application, consider using `work.stream()` instead of `work.exec()`.  That way you only need to hold (roughly) one row in memory at a time.  It's also likely to be faster.

**Comment by nthung11cist** [comment]
> You can't delete or modify data in a `pqxx:result`. Even if you could, it would not reduce the _peak_ memory consumption: there would still be a time where you'd have the whole result in memory.
> 
> If that is a problem for your application, consider using `work.stream()` instead of `work.exec()`. That way you only need to hold (roughly) one row in memory at a time. It's also likely to be faster.

Thank you so much!
