### ISSUE TITLE
Determine column type when reading data from pqxx::field

### ISSUE THREAD

**Issue by BFamzz** [jtv/libpqxx#509]
Please I need some clarification here.

I am trying to store some data into JSON objects.

I have the following code:

```
for (const pqxx::row &rowResult : selectResult) {
        nlohmann::json rowData;
        for (const pqxx::field &fieldResult : rowResult) {
            if (!fieldResult.is_null())
            {
                rowData[fieldResult.name()] = fieldResult;
            }
        }
    }
```

The assignment operation cannot work unless a type is specified in fieldResult like 
`
rowData[fieldResult.name()] = fieldResult.as<std::string>();
`
or some other desired type.

Also, from the source, there is an overloaded `as()` function as shown below:
```
template<typename T> T as() const
  {
    if (is_null())
    {
      if constexpr (not nullness<T>::has_null)
      {
        internal::throw_null_conversion(type_name<T>);
      }
      else
      {
        return nullness<T>::null();
      }
    }
    else
    {
      return from_string<T>(this->view());
    }
  }
```
But using the function results in a compiler error:

![Screenshot (182)](https://user-images.githubusercontent.com/38426051/145103907-4d2d1935-68e3-4e90-be31-ffe872e35598.png)

Please is there a way to use this function or is there a way to determine the column type.

Thanks.

**Comment by jtv** [comment]
Before I read on...  Small note: don't use a _reference_ to the `pqxx::row` — it's more of an iterator type.  So use `pqxx::row` as a value, not `pqxx::row&`.

**Comment by jtv** [comment]
Now that I've read the rest...  Yes, in order to read the field value you need to request it with a specific type.  This is all _strongly statically typed,_ so you can't just get a value without its type being known, like you might in e.g. JavaScript.

So to read the value of `fieldResult` as an `int`, for instance, you'd call:

    fieldResult.as<int>()

The result came from the database in a textual format, so this _parses_ the textual value into an `int`.  If it's not a value that is suitable for an `int`, it'll throw an exception.

Similarly, if you wanted a `double`, you'd do...

    fieldResult.as<double>()

**Comment by BFamzz** [comment]
Thanks for the note on `pqxx::row`. It's duly noted.

Thanks for your response. I understand parsing into the required data type. However, if a table has 10 columns with different data types (integer, text, boolean, etc) and the values want to be retrieved and stored via loops (as shown earlier), the only way to is to check the column name and parse the data accordingly.

Kindly confirm if this is the only way or there's another way that doesn't require going through all column names.

Thanks.

**Comment by jtv** [comment]
There are tricks, but it all depends on what exactly you need.

If you at least know the number and types of the columns at compile time, it's really simple: use a loop to go through the rows in the result, but don't use a loop for the fields in the rows.  Specify a compile-time type for each column.  You can even just convert a whole row at once to C++ values using `pqxx::row::as<...>()`.  I think this is generally the nicer way to go.

But if you don't have that information, it gets really tough.  At _some_ point you're going to have to know what type of data you're dealing with, but until then you can just treat everything as a string.

Again there's several ways of doing that.  Simplest to manage is to use `fieldResult.as<std::string>()`.  But if you need high performance, you can use `fieldResult.c_str()` to retrieve the field's text as a C-style `char const *`.  Just make sure that `fieldResult` still exists by the time you process the data!

Then, at the point where you need to process the data and you know its type, you can parse a value `text` into (for example) an `int` using `pqxx::from_string<int>(text)`.

**Comment by jtv** [comment]
(Oh, and what I said about not using a reference for a row, also applies for a field.  Don't use a reference for that one either.)

**Comment by KayEss** [comment]
This is how I solved the similar problem for Fostgres: https://github.com/hotkit/fost-postgres/blob/master/Cpp/fost-postgres/recordset.cpp#L108-L163

The fields are always available as text (because that's how Postgres sends them over the wire) and you have access to the underlying Postgres field type enumeration. There's not that many types that matter for JSON and you can always fall back on strings.

**Comment by BFamzz** [comment]
Thanks @jtv @KayEss. The advice given is really helpful. I appreciate. I will close this issue now.
