### ISSUE TITLE
Error on sunning sql query

### ISSUE THREAD

**Issue by dpasha52** [jtv/libpqxx#541]
Hi ,
I am unable to figure out if this issue has to do with the code I have written or from db side ,Need your input here ,

my code snippet looks something like this 
conn->prepare("my_statement",selectSQL);
 pqxx::work * t = new pqxx::work(*conn);
*rs =t->exec_prepared("my_statement");

ERROR: relation "users" does not exist
LINE 1: SELECT * from users
^

SQL Error code: 42P01

found some articles but unable to make the query work. Need input to verify if missing something 
Thank you 
dpasha52

**Comment by jtv** [comment]
You created a transaction pointer instead of a transaction.

**Comment by dpasha52** [comment]
Sorry updated my code now. pqxx::work * t = new pqxx::work(*conn);
 I want to use it that way , using a transaction pointer then calling exec is that allowed

**Comment by tt4g** [comment]
`users` table does not exist, it needs to be created.

**Comment by jtv** [comment]
You can create your transaction using "new", yes.  It's just a bit more
work because you'll then also need to "delete" it when you're done with it.

Consider using a std::shared_ptr, e.g. auto t =
std::make_shared<pqxx::work>(*conn);

The shared_ptr will then automatically delete the pqxx::work when t and any
copies you may have made of it go out of scope.

**Comment by dpasha52** [comment]
Fixed the issue.
