### ISSUE TITLE
Handling of Network Address types in libpqxx

### ISSUE THREAD

**Issue by dineshR478** [jtv/libpqxx#545]
Hi @jtv ,

I have surfed the internet to find an example on how to handle the Network Address Types with libpqxx library. The question here is, can i use field.c_str() to access the IP/Mac address stored in the postgresql table. If not, could you provide me an example of handling it.

**Comment by jtv** [comment]
Yes you can use `field.c_str()`, or any of the other ways to read a field as a string.

Another way would be to define your own classes for these types, and implement conversions between these SQL types and their text representations.  See [include/pqxx/doc/datatypes.md](../blob/master/include/pqxx/doc/datatypes.md) for instructions on how to do that.  It's definitely more work, and there is more change to the API as libpqxx evolves, but the advantage is that you'll be able to use your types as regular values.  So for instance you'll be able to use `field.as()` to convert the field's value to an object of your type.

And of course it would be worth including classes for this in libpqxx itself.

**Comment by jtv** [comment]
I'm starting to think it might be useful for me to maintain a separate library to provide support for things like Boost's `ip::address`.

(Why a separate library?  Because I like to keep the dependencies for libpqxx absolutely minimal.  Right now it depends only on "postgres, any supported version."  It avoids a lot of trouble.  But I have built up a fair bit of experience supporting multiple versions of things.)

**Comment by KayEss** [comment]
What I've done in the past is to include some extra Boost headers for users to optionally include, but that still makes for complications in testing as you ideally have to test both the with Boost and without Boost configurations to make sure you haven't broken anything -- although things like CircleCI makes this relatively simple. It's not clear that it's any better than a separate library -- maybe a tiny bit easier for users? :shrug:
