### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by nonunknown** [jtv/libpqxx#568]
* Its possible to have `pqxx::connection` as a "global" variable?

I mean I've tried:

```cpp

pqxx::connection c

int main()
{
  c = pqxx::connection(connectionString);
}

```

this throws:

```
terminate called after throwing an instance of 'pqxx::broken_connection'
  what():  could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?
```

the right way is to call pqxx::connection every time I do a query?

* I'm trying to create an abstract querying system

I want to know if its possible to get the type of the variable comming in the `pqxx::result` I've tried:

```cpp
  pqxx::result r = worker.exec("select * from Inventory");
  std::cout << typeid(r[0][0]).name() << std::endl; // the result here is the same name: N4pqxx5fieldE
```

also I've tried `.hash()` but its the same hashid

**Comment by KayEss** [comment]
I think you'll still need to delay making the connection until main enters. So you can change the type of the global to either `std::optional<pqxx::connection>` or `std::unique_ptr<pqxx::connection>`

**Comment by jtv** [comment]
Once again I sent a reply by email but it did not appear here.  :-(  I'll try to reconstruct from memory.

Your error happens because by default-constructing a `pqxx::connection`, you are asking libpqxx to connect to a database using the default settings.  This fails to connect in your case, and then crashes because you're not catching exceptions coming out of that constructor.

First thing that springs to mind in your first question: a mutable global variable is generally just not a good idea.  So try not to do that — make the `pqxx::connection` a local variable.

If you can't do that, then you could make it a pointer.  For instance, you could make `c` a `std::shared_ptr<pqxx::connection>`.  Then your `c = pqxx::connection(...)` becomes `c = std::make_shared<pqxx::connection>(...)`, and of course any `c.foo()` becomes `c->foo()`.

Then the second question...  There's no point in looking at the `typeid` of a `pqxx::field` because it's always a... `pqxx::field`.  More fundamentally, field values in libpqxx are basically un-typed.  The server sends them as strings, which libpqxx can then parse to convert them to a given other type.  For instance, if a field's textual value is "`3`" then you can read it as an `int`, or as a `short`, an `unsigned long long`, a `float`, and so on.  You request a specific type, and the field will try to parse its value as that type.

You _can_ query a field's SQL type, using its [type() method](https://libpqxx.readthedocs.io/en/latest/a01044.html#ad2da9b613fdf2b38a36e92eafd9b223a).  But this returns a numeric ID, which you would then need to look up in PostgreSQL's built-in [`pg_type` table](https://www.postgresql.org/docs/current/catalog-pg-type.html), or compare to an expected value.  (Most types' IDs in postgres have fixed, known values.)  I think it's pretty rare for applications to look in `pg_type`, but it ought to work.

For example, the type `int8` has an `oid` of 20, so if you queried a column of `int8` type, then a `pqxx::field::type()` in that column would return 20.  You could then get the name using `SELECT typname FROM pg_type WHERE oid=20`.

**Comment by nonunknown** [comment]
thanks for the response guys! this is really cool!

**Comment by jtv** [comment]
You can have a pqxx::connection as a global variable, yes.  But as always,
a mutable global variable is usually a bad idea.

The problems you're hitting here are:
1. If the construction of the global variable throws an exception, you have
no way to handle it.
2. By constructing a pqxx::connection without passing a connection string,
you are asking libpqxx to connect to the default database with all default
options, which you don't even want to do but which in your case is failing.

IMHO the best way to fix these problems is to avoid using a global variable
for this.

But if you wanted a minimal change, you could fix it by making c a (for
instance) std::shared_ptr<pqxx::connection>, and then instead of "c =
connection(...)", using "c = std::make_shared<pqxx::connection>(...)".

Next let's look at your other question: the type of a field.  It took me a
while to figure out what you were trying to do.  It doesn't make sense to
look at the typeid of a pqxx::field, because its type is always...
pqxx::field.  And the value inside it is effectively untyped.  The database
sends it as a string, and you can convert it to any type you like, provided
that what's in the string is suitable for parsing as that type.  So if a
field contains the string "123", you can read it as a string, or as an int,
or as a float, an unsigned long, a double, and so on.

It is possible to query the SQL type that that particular column had on the
server side, but I really never use it.  It returns an "oid" referring to a
type in the PostgreSQL system catalog:

https://libpqxx.readthedocs.io/en/7.7.3/a01044.html#ad2da9b613fdf2b38a36e92eafd9b223a

I don't know off the top of my head where you'd look up that oid, and I'm
on my phone which makes it hard to find.  But you can obtain details either
by querying some built-in postgres table such as pg_class ("WHERE oid =
..."), or simply comparing them to fixed values that you're expecting.
Many built-in types have fixed, unchanging oid values.
