### ISSUE TITLE
Feature request: Can 'quote' and 'escape' be separated from connection/transaction?

### ISSUE THREAD

**Issue by dpriedel** [jtv/libpqxx#595]
Hi

I find that I have a need to create query requests separately from running those queries.  The problem I have is that I need to 'quote' or 'escape' user inputs that go into the query.  But I am not in the code which runs the queries (which has connection and transaction objects), so those functions are not available to me.

For the time being, I work around this by creating a connection in my code which creates the queries whose only function is to provide access to quote/escape functions.

Is there a better way?

Thanks

Dave Riedel

**Comment by tt4g** [comment]
There is a `PQescapeString()` function that does not require a connection, but is deprecated by PostgreSQL.
As noted in the documentation (https://www.postgresql.org/docs/14/libpq-exec.html), this function does not adjust its behavior according to the current connection properties (such as character encoding). Therefore, it may not escape correctly.

Since there is no safe function in libpq that does not require connection, it is not possible to provide an escape function that does not require a connection.

NOTE: PostgreSQL strings can be defined in several ways besides single quotes (e.g., quoting with `$`).
Prepared statements should be used instead of including user input in the SQL.
See: https://www.postgresql.org/docs/14/sql-syntax-lexical.html

**Comment by jtv** [comment]
Yup, the problem is exactly that in order to handle strings correctly, we _need_ to know the encoding that applies to that specific connection at that time.

The solution does not have to be _prepared_ statements; a _parameterised_ statement will do the trick.

I suppose in theory it would be possible to add support for escaping a string in a given encoding.  But that would require exposing some kind of enum indicating the encoding, and there are complications with that.

**Comment by jtv** [comment]
I'm sorry not to have a better answer for you @dpriedel...  Is it at least an answer that you can live with, knowing the reason the way it works like this?  If so, I'll close the ticket.  If not, we may have to introduce something akin to a locale class or enum.

**Comment by dpriedel** [comment]
I can work with this. So go ahead and close the ticket.


Thanks for looking into it.

**Comment by jtv** [comment]
Glad to hear it, thanks!
