### ISSUE TITLE
std::optional<std::string_view>> not working in stream_to.

### ISSUE THREAD

**Issue by HindrikStegenga** [jtv/libpqxx#596]
Hello, 

I am trying to use `pqxx::stream_to::table` in version 7.7.4 and have a lot of row data stored in std::optional<std::string_view>>'s.
However, it seems that the implementation of `string_traits `for `std::string_view` is missing the `to_buf `function. 
See `conversions.hxx:r616`:

```
/// String traits for `string_view`.
template<> struct string_traits<std::string_view>
{
  static constexpr std::size_t
  size_buffer(std::string_view const &value) noexcept
  {
    return std::size(value) + 1;
  }

  static char *into_buf(char *begin, char *end, std::string_view const &value)
  {
    if (internal::cmp_greater_equal(std::size(value), end - begin))
      throw conversion_overrun{
        "Could not store string_view: too long for buffer."};
    value.copy(begin, std::size(value));
    begin[std::size(value)] = '\0';
    return begin + std::size(value) + 1;
  }

  /// Don't convert to this type; it has nowhere to store its contents.
  static std::string_view from_string(std::string_view) = delete;
};
```
This causes a template substitution failure when using std::optional specifically, as that seem to use the to_buf function whereas just passing std::string_view seems to use the into_buf function.
Could this be added?
And also regarding the note on the from_string function, why not just return the passed view param here?

**Comment by jtv** [comment]
You are correct.  Well done digging this up.  Unfortunately there are good reasons for it.

The problem with `to_buf` for `string_view` is that we'd either need to copy the string into the buffer (which is expensive and may be unnecessary), or just use the existing pointer into the existing string (but whose lifetime is out of our control).  Similarly, if I implemented `to_string`, I might be returning a view on a string that may no longer exist by the time you use it.

The _good_ news is that none of that needs to matter in this particular situation.  In `stream_to` I added special-case support for `string_view` so that you could use it in the way you'd expect — I just didn't build the same support for `optional<string_view>`!  And of course I can't do just that; I'll want to build support for `shared_ptr` and `unique_ptr` as well, and probably some other types.  It'll take some thought, which I don't expect to be able to do for the next few days.  But after that, I'm confident we can solve this.

**Comment by HindrikStegenga** [comment]
Thank you for the quick response!
I seem to stumble into another but similar issue. Apparently I can't insert `std::optional<std::string>>` values when using the stream operators. It works when using `stream.write_values()` but not when doing `stream << std::optional<std::string>(std::nullopt)` for example. I get an error that it cannot find a matching function call for begin().

**Comment by jtv** [comment]
To be honest I'd like to get rid of the `<<` operator anyway.  If it works using `write_values`, use that.

**Comment by jtv** [comment]
@HindrikStegenga that latest commit should solve the problem.  If you could confirm, I can release an update.

**Comment by HindrikStegenga** [comment]
I can confirm the PR resolves the issue. Thanks!
