### ISSUE TITLE
win10 x64, compile ok, run with exception -- bad array new length

### ISSUE THREAD

**Issue by zhoutk** [jtv/libpqxx#602]
The following codes runs correctly on Linux.
```
        Json ExecNoneQuerySql(string aQuery, Json values = Json(JsonType::Array)) {
          Json rs = DbUtils::MakeJsonObject(STSUCCESS);
          string err = "";
          pqxx::connection *pq = GetConnection(err);
          if (pq == nullptr)
	          return DbUtils::MakeJsonObject(STDBCONNECTERR, err);
          pqxx::params ps;
          int len = values.size();
          for(int i = 0; i < len; i++){
	          ps.append(values[i].toString());
          }
          try
          {
	          pqxx::nontransaction N(*pq);
	          pqxx::result R(N.exec_params(aQuery, ps));
                 ...
	          R.clear();
          }
          catch (const std::exception &e)
          ...
        }
```
But on win10, ps.append(values[i].toString()) will cause an exception -- bad array new length. While change to - params.append(values[i].toString().c_str()); , it works.  
Then,  
```
pqxx::nontransaction N(*pq);
pqxx::result R(N.exec_params(aQuery, ps));
```
will cause an exception -- 0x000002a8d797c5c0 "SEH exception with code 0xc0000005 thrown in the test body."

why?
thanks!

**Comment by KayEss** [comment]
In the JSON library that you're using, what type does the expression `values[i].toString()` produce?

**Comment by jtv** [comment]
Generally, when asking a question like this, try to show a _minimal reproduction_ of the problem.  Most of the time you'll discover what the problem is just while you're doing that — but if you don't, it'll be easier for people to help you.

What @KayEss is driving at, I think, is that it's probably one particular type, or object, that triggers the problem.  Then you could show us the problem in just 3 lines: create object, create `pqxx::params`, call `append()`.

**Comment by zhoutk** [comment]
Thank you for your reply first!
After careful analysis and debugging, the problem may be about memory use style on windows.
At first, I linked the release version of libpqxx, show error like above. Next, I linked debug version, it's can run to end correctly, but a exception be thrown on the end.
linking release version, run unit test like this:
 ![zorm-rlz-err](https://user-images.githubusercontent.com/1542521/193199300-43ecc758-dbcd-4118-a926-0e82a7a9eae9.PNG)
linking debug version, run unit test like this:
![zorm-debug-err](https://user-images.githubusercontent.com/1542521/193199348-bbc3b865-085b-48b3-9e02-feb02e3ba8fe.PNG)
This question aises in my project [Zorm](https://github.com/zhoutk/zorm), run ./src/main.cc is the minimal reproduction of the problem.  Because the project rely on libpqxx, I upload all files in thirds/libpqxx which will be used compiling on win10.

The project has been adapted sqlite3 and mysql on linux, macos and windows, postgres on linux and macos, but error on win10.

**Comment by zhoutk** [comment]
> In the JSON library that you're using, what type does the expression `values[i].toString()` produce?

std::string, thanks!

**Comment by tt4g** [comment]
> linking release version, run unit test like this:

Debug and release builds cannot be mixed. The application will not run properly because the STL memory layout will not match due to optimization.
Please be consistent with debug or release builds.

> linking debug version, run unit test like this:

I think it is a compile options issue.
It seems that this error occurs when the options `/MD`, `/MDd`, `/MT` and `/MTd`, which determine the standard Windows library to link, do not match between the library and the application.

See https://learn.microsoft.com/en-us/answers/questions/240332/assert-when-using-mtd-dynamic-library.html

**Comment by zhoutk** [comment]
You are right, thanks!
I'm trying to solve this problem.
I close this, thank all of above.
