### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by illegal-instruction-co** [jtv/libpqxx#638]
How could i do run tests, in my side it is not working cuz of pqxx::connecting or pqxx::connection.

Does the unit tests are really related with database ?

**Comment by jtv** [comment]
See `BUILDING-cmake.md` or `BUILDING-configure.md` (depending on which build system you use) in the repo.  They include instructions on how to run tests.

**Comment by illegal-instruction-co** [comment]
ok, i got it now. But i wonder what if someone interest to make unit testing a project which is depended to this library ? 

We should be able to create rows and fields to simulate some probabilities, but libpqxx was designed in a way that strictly prevented this. Even the libpqxx's unit tests can't even use the right methodology. It is depended to database for testing some sceniors.

**Comment by jtv** [comment]
Can you be a bit clearer about what you're trying to do?  Creating rows and
fields should be easy enough.

**Comment by illegal-instruction-co** [comment]
First of all i should make all the tests without installing database stuff to testing server. Because i just want test the target sceniors as lite way.

For example:

Target:
```
string Foo::getData(row& row) {
	if (row[zview("Boo")].as<string>() == string("Zoo"))
		return "Foo";
	return row[zview(Language::code_ltr)].as<string>();
}
```
I want to test 2 branches of if condation with gtest. So i must return spesific values from "as" method.

There are possible ways to do.

These are what i thought: 

1. ( and should be simplest ) Creating fake field and fake row to give them to getData
2. Vtable hooking for as function to returns spesific value.

**Comment by illegal-instruction-co** [comment]
First of all i should make all the tests without installing database stuff to testing server. Because i just want test the target sceniors as lite way.

For example:

Target:
```
string Foo::getData(row& row) {
	if (row[zview("Boo")].as<string>() == string("Zoo"))
		return "Foo";
	return row[zview("Boo")].as<string>();
}
```
I want to test 2 branches of if condation with gtest. So i must return spesific values from "as" method.

There are possible ways to do.

These are what i thought: 

1. ( and should be simplest ) Creating fake field and fake row to give them to getData
2. Vtable hooking for as function to returns spesific value.

**Comment by jtv** [comment]
So you're trying to inject fakes for testing.  That is a great thing to do in tests, but there are both costs and benefits.

Unfortunately gtest is not magic: it relies on vtables, which most classes don't need.  I did not include vtables in libpqxx classes where they weren't functionally needed, partly because there's a slight performance cost to having vtables.  Small though the cost may be, the risk was to slow down production code for the needs of the tests.

Another reason is that opening classes up for extension through inheritance widens their effective APIs, meaning that future changes become more likely to break third-party code in unexpected ways.

And finally, virtual functions can complicate construction and destruction in surprising ways, because a derived-class object must go through both its own constructor and destructor, and those of its parent classes.

**Comment by illegal-instruction-co** [comment]
You would be right about the costs, i don't know. But i think, forcing projects - which one uses libpqxx and uses TDD - to the be depended a database environment a little bad. I think third-party libraries, especially those that are used so much should be a little more useful in these matters and provide convenience. This is just a suggestion.

**Comment by jtv** [comment]
It's a tradeoff.  I'm sorry it doesn't work out the way you want; I like to work in the same way when possible.  But it's harder with statically compiled code.  Consider doing the injection at the layer of your own code.

**Comment by jtv** [comment]
I don't think there's anything we can do about this ticket, so I'll just close it.
