### ISSUE TITLE
Link errors after upgrading to version 6

### ISSUE THREAD

**Issue by wichert** [jtv/libpqxx#64]
Homebrew just upgraded libpqxx to version 6, which immediately seems to have broken my code. It now fails to link:

```
Undefined symbols for architecture x86_64:
  "pqxx::row::row(pqxx::result, unsigned long)", referenced from:
      pqxx::const_result_iterator::const_result_iterator(pqxx::result const*, unsigned long) in loader.cc.o
  "pqxx::internal::clear_result(pg_result const*)", referenced from:
      pqxx::result::make_data_pointer(pg_result const*) in loader.cc.o
  "pqxx::internal::basic_transaction::do_commit()", referenced from:
      vtable for pqxx::transaction<(pqxx::isolation_level)0, (pqxx::readwrite_policy)0> in loader.cc.o
      construction vtable for pqxx::internal::basic_transaction-in-pqxx::transaction<(pqxx::isolation_level)0, (pqxx::readwrite_policy)0> in loader.cc.o
  "pqxx::internal::basic_transaction::basic_transaction(pqxx::connection_base&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, pqxx::readwrite_policy)", referenced from:
      pqxx::transaction<(pqxx::isolation_level)0, (pqxx::readwrite_policy)0>::transaction(pqxx::connection_base&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in loader.cc.o
  "typeinfo for pqxx::internal::basic_transaction", referenced from:
      construction vtable for pqxx::internal::basic_transaction-in-pqxx::transaction<(pqxx::isolation_level)0, (pqxx::readwrite_policy)0> in loader.cc.o
      typeinfo for pqxx::transaction<(pqxx::isolation_level)0, (pqxx::readwrite_policy)0> in loader.cc.o
  "VTT for pqxx::internal::basic_transaction", referenced from:
      pqxx::internal::basic_transaction::~basic_transaction() in loader.cc.o
```

I noticed that pqxx::row::row is listed as deprecated, but as far as I can see my code does not try to use it. My usage pattern looks like this:

```
pqxx::result result;
result=transaction.exec(…..);
for (const auto &row: result) {
    ProcessRow(row, some_object);
}
```

Where `ProcessRow` takes an `const pqxx::row &row` parameter, so no copying should ever happen.

I have no idea what is up with the transaction link errors.

**Comment by jtv** [comment]
Hi Wichert!  This is interesting...

The `row` constructor in `row.hxx` is _documented_ as deprecated, using a Doxygen `@deprecated` marker, but it's not actually marked as deprecated _in the code_ by any deprecation attribute.  The reason for that is that the constructor isn't going away, it's just going to be made private.  So the library itself can still call it, and it does so from an inline function — which means that the call is visible at link time.  That part at least makes sense.

The big mystery is why the linker was told that this constructor is deprecated in the first place.  The first theories I thought of were...

1. Maybe I added and later removed a deprecation attribute.
2. Maybe the compiler somehow picked up on that _comment_ and marked the constructor as deprecated.

Neither of these looks particularly plausible to me.  I looked around the history for row.hxx but didn't find any forgotten deprecation attribute.

Could it be that a Brew package maintainer added a patch adding an actual deprecation attribute to that constructor?  Have a look at your row.hxx header.  For me, the relevant lines read:

    /// @deprecated Do not use this constructor.  It will become private.
    row(result r, size_t i) noexcept;

**Comment by wichert** [comment]
Homebrew does not seem to add any patches, see [their formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libpqxx.rb)

**Comment by wichert** [comment]
I don't think this has anything to do with it being marked as deprecated. It might be a difference between clang and gcc?

**Comment by jtv** [comment]
OK, I just released 6.1.0, which includes the fix.

**Comment by egorpugin** [comment]
I do not understand.
We have PQXX_LIBEXPORT specified for the whole row class. Why do we need this near constructor?
Visual Studio considers this as an error. (I sent a PR with removal of such `PQXX_LIBEXPORT`s.)

It is possible that in original case the issue was not about PQXX_LIBEXPORT.
Maybe some build defect or something else.

**Comment by jtv** [comment]
Thanks @egorpugin, you are right.  Clearly I'm not fully awake today.  I'm undoing the commit.

Yes, it _is_ possible that the problem was something else.  I just don't know what it could be!  Sometimes mangling changes in compilers cause these errors, especially if the library is compiled with one compiler (or set of options) and the client is compiled with another.  But this looks like such a straightforward function prototype.

Although...  Didn't noexcept become part of the C++ type system at some point _after_ C++11?  Maybe this kind of link error happens when the compiler compiling the library and the compiler compiling the client have different opinions about whether the "noexcept" is part of the signature.

Wichert, perhaps you could try either (a) compiling with different versions of the C++ language standard (e.g. for gcc or clang: `-std=c++11` vs. `-std=c++14` vs. `-std=c++17`); or (b) temporarily removing that `noexcept` from the declaration in the row.hxx header?

**Comment by egorpugin** [comment]
Yeah, I also thought about `noexcept`.

**Comment by wichert** [comment]
It turns out the problem is much simpler: cmake had the header file location for the 5.0 release cached, but used the 6.0 dylib for linking. And unsurprisingly that combination does not work...

**Comment by jtv** [comment]
This happens to people from time to time...  I'll have to think about some kind of guard to prevent this from happening.  There's a version string in the headers, so perhaps I could set up a "trap" to produce a link error when that version does not match the version of the library itself.
