### ISSUE TITLE
c++17 compiler test needs -std=c++17

### ISSUE THREAD

**Issue by prlw1** [jtv/libpqxx#733]
The configure.ac test for c++ 17 checks whether `__cplusplus < 201611L`, but the value of `__cplusplus` changes according to the `-std` flag. e.g., for me:
```
$ g++ -std=c++17 foo.cc -o foo
$ ./foo
cpp: 201703
$ g++  foo.cc -o foo
$ ./foo
cpp: 201402
```
AFAICT the configure test checks without the -std flag, so rejects my compiler.

**Comment by jtv** [comment]
This is the expected behaviour.  The configure script used to try and select a C++ version, but it was an ugly can of worms.  So I made it the caller's choice.

So, if your compiler compiles an older version of C++ by default, you'll need to pass an option to select a version.

For example: `./configure CXXFLAGS=-"std=c++17"`

**Comment by prlw1** [comment]
Ah: I thought that as you want c++17, you would set that standard via compiler flags, but now I see that you really want >= 17, so don't want to be limited to c++17 if the compiler can do c++20 or more... so notabug

**Comment by jtv** [comment]
Exactly!  Plus, other compilers may have different flags... Like I said, ugly can of worms.  :-)

**Comment by KayEss** [comment]
I wonder if it wouldn't be better to detect the availability during the configure step and drop a `HAVE_xx` macro in the header file -- then there won't be an ODR violation because the capabilities will be fixed.

**Comment by gdt** [comment]
My impression is that standard practice is to test if the compiler accepts the --std flag you want, and to fail otherwise.   Testing for an acceptable std flag and `HAVE` is certainly a reasonable expansion of that.

**Comment by KayEss** [comment]
> compiler accepts the --std flag you want

This gets messy very quickly across all of the compilers libpqxx supports, which is why it's left to the user to decide what they want

**Comment by jtv** [comment]
Mixing binaries compiled by different compilers is a bad idea in C++ -unlike with C there is no guarantee that they will be compatible.  Yes a few compilers are ABI-compatible with gcc, but even that is thin ice.  Different versions of the same compiler aren't necessarily ABI-compatible.  The same C++ version on the same version of the same compiler isn't necessarily ABI-compatible depending on compiler options.

So the answer IMO is not "make it easier to do something dangerous," but "if you know what you're doing you're free to do it, but you'll have to know what you're doing."  Even if what you want is quite simple, it has to be a decision that you make in your build environment - because there are no standards to protect you from the agony of choice.

As a point of comparison, even autoconf-archive didn't have even a halfway decent solution to this.  CMake basically addresses it by dictating versions and options and assuming it knows all compilers intimately.  That just doesn't scale - libpqxx has to work on platforms I haven't even heard of.

**Comment by jtv** [comment]
Perhaps you're right @KayEss that I should go back to doing all the compiler/libpq feature checks at configure time... but it's a royal pain and I was fervently hoping to phase most of them out in favour of simple compile-time checks.

Then again... given that mixing object files built for different C++ versions breaks ABI compatibility, and worse, debug options can break runtime compatibility of memory layouts anyway... perhaps it's just not worth trying to solve this.  Perhaps it would be more helpful to try and _detect_ incompatible combinations.

**Comment by KayEss** [comment]
> in favour of simple compile-time checks

I totally get that. It's what I'm doing in my projects and it is nice. But it seems there are also hidden dangers.

You have it harder if you mean to support both cmake and autoconf though -- it means doing these checks twice. You also have to consider what happens when libpqxx is packaged -- it seems right now that's quite likely to break because people using the packaged version have no control over how it was compiled.
