### ISSUE TITLE
version 6.4.5 there is small issue.

### ISSUE THREAD

**Issue by gf-eaton** [jtv/libpqxx#742]
Hello I am using Debian

I use apt `install -y libpqxx-dev`

Couple days ago I was able to compile without any issues.  So I suspect a small incompatibility with libhv!
I will continue investigating and update the post. I will re-sort the `#includes`

This error is now there :
`/usr/include/pqxx/strconv.hxx: In static member function ‘static void pqxx::enum_traits<ENUM>::from_string(const char*, ENUM&)’:`

I am more confident now, Cause I am able to compile some other projects involving libpqxx 6.4.5-2 (that are not using libhv)
Some sort of incompatibility with libhv about the ENUM under Linux Debian with version 6.4.5

Here is a small cross-compiler attempt :
```
In file included from /usr/local/include/hv/HttpServer.h:4,
                 from httpd.cpp:1:
/usr/include/pqxx/strconv.hxx: In static member function ‘static void pqxx::enum_traits<ENUM>::from_string(const char*, ENUM&)’:
/usr/local/include/hv/hexport.h:97:21: error: expected primary-expression before ‘enum’
   97 | #define ENUM(e)     enum e
      |                     ^~~~
make: *** [Makefile:12: httpd-arm64] Error 1
```

I also use Windows and VS2022. The error __does not exist__ using VS 2022.  CMake project is used with vcpkg.

My Makefile as a sample (for Linux only)
```
myEXE: myEXE.cpp
	apt install -y libpqxx-dev
	g++ $^ -O3 -I/usr/include/ -std=c++20 -lpqxx -o $@
```

**Comment by gf-eaton** [comment]
Hello folks,

resorting the `#includes` resolve the issue.  Do not put postgres `pqxx` after `HttpServer,h`

small example.
```
#include <iostream>    //cout
#include <chrono>      //chrono C++20
#include <string_view>
#include <pqxx/pqxx>   //postgres libpqxx C++

#include "hv/HttpServer.h"
using namespace hv;
```

**Comment by gf-eaton** [comment]
Closing.

**Comment by jtv** [comment]
I'm sorry @gf-eaton, it took me a while to notice this message!  Because you'd already closed it I suppose.

Yes, macros are dangerous and I wasn't expecting something as obvious as ENUM to be defined as a macro.  This is why macros defined in the libpqxx headers have a prefix like `PQXX_` — to avoid exactly this kind of clash.

So I would argue it's a bit of a bug in libhv, basically claiming a global identifier for itself like that.  I would have recommended prefixing it with something recognisable, such as `HV_ENUM`.
