### ISSUE TITLE
Can't initialize zview from string_view

### ISSUE THREAD

**Issue by egorpugin** [jtv/libpqxx#811]
```
    pqxx::zview x1 = "123";
    pqxx::zview x2 = "123"sv; // does not work
    pqxx::zview x3 = "123"s;
```

pqxx::zview has `explicit` ctor from string_view.
Is it intentional?
If not, maybe remove it for consistency?

**Comment by jtv** [comment]
That `explicit` is there for a very good reason!

The difference between a `std::string_view` and a `pqxx::zview` is the _promise, verified by a human_ that the string be zero-terminated.  There is no such promise for `std::string_view`.

If we removed the `explicit`, then that would mean "if humans do not make this promise, just assume it."  Which would be colossally stupid.  And most tests would not reveal it, because in practice a lot of `std::string_view` happen to have a zero byte behind them.  So...  Silent bug, waiting to strike.

**Comment by egorpugin** [comment]
I see, thanks.
