### ISSUE TITLE
cmake will take the given lib name and it changes to "-l{libname}" and linker will search using "-l{libname}"

### ISSUE THREAD

**Issue by srinathv2** [jtv/libpqxx#813]
> cmake will take the given lib name and it changes to "-l{libname}" and linker will search using "-l{libname}"

@srinathv2 No. CMake checks if a string and the matching CMake target are defined.
If a CMake target is found, it adds the necessary linker flags to use that target.
If the target is not found, the name is treated as a link target.

See:
- https://cmake.org/cmake/help/latest/command/target_link_libraries.html
- https://stackoverflow.com/questions/74974399/what-is-a-target-in-cmake

_Originally posted by @tt4g in https://github.com/jtv/libpqxx/issues/383#issuecomment-2031767111_

**Comment by srinathv2** [comment]
@tt4g you can check this https://cmake.org/cmake/help/latest/command/target_link_libraries.html#target-link-libraries:~:text=A%20plain%20library%20name%3A%20The%20generated%20link%20line%20will%20ask%20the%20linker%20to%20search%20for%20the%20library%20(e.g.%20foo%20becomes%20%2Dlfoo%20or%20foo.lib).

**Comment by tt4g** [comment]
> you can check this

You repeatedly asked your own question in #383,
Is that comment the only one that explains the behavior I did not understand?
If so, I already know its CMake behavior specification.

What I didn't understand was that `find_package()` should also look for libraries in the `PATH` environment variable, but it failed to do so.
Nevertheless, when I pass only a string to `target_link_libraries()`, it is able to link.
This is because the fact that it is linked means that libpq was found somewhere in the path contained in the `PATH` environment variable.
This behavior appears to be inconsistent,
Furthermore, `find_package()` could not find libpq when I defined the `PostgreSQL_ROOT` variable.
The only way to investigate the reason for this would be to look at #383 author's machine.

**Comment by srinathv2** [comment]
@tt4g this is not about any issue i was letting you know,how target_link_libraries works when you give lib name

**Comment by tt4g** [comment]
I don't know what you want to do by telling me that.

**Comment by srinathv2** [comment]
@tt4g 

> What I didn't understand was that `find_package()` should also look for libraries in the `PATH` environment variable, but it failed to do so.

find_package tries to search the for <lowercasePackageName>-config.cmake or <PackageName>Config.cmake and it helps to find the lib's includes,binaries.We can specify the path to this file before find_package using set(packagename_DIR path),i agree it searches for the <PackageName>Config.cmake file in this order CMAKE_PREFIX_PATH,PATH you can check  https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure how find_package searches for the config file

**Comment by srinathv2** [comment]
> I don't know what you want to do by telling me that.

i saw the comment https://github.com/jtv/libpqxx/issues/383#issuecomment-723992584 and just thought to help and learn,nothing else.

**Comment by tt4g** [comment]
Suddenly such a comment is lost on me.
I understand you want to learn CMake, but this is the libpqxx repository.
If you have a question about the tool CMake, you should do it on a Q&A site like Stack Overflow.
The maintainers of this repository should have been notified of mentions unrelated to libpqxx.
It is considered annoying to them.
