### ISSUE TITLE
`RETURNING` from a `stream_to`

### ISSUE THREAD

**Issue by rbrugo** [jtv/libpqxx#814]
Hi,
I can't find a way to configure a `stream_to` object to return something after the insert, as in
```pgsql
INSERT INTO data (a, b, c, d) 
VALUES
    ...
RETURNING id;
```
Is it possible to do something like this?

**Comment by tt4g** [comment]
Since `stream_to` is executing `COPY` statement, it will not be able to use features such as `RETURNING`.

https://github.com/jtv/libpqxx/blob/ee78906eb2b128665d175e0d0bfd99551a452ec7/src/stream_to.cxx#L105-L114
https://github.com/jtv/libpqxx/blob/ee78906eb2b128665d175e0d0bfd99551a452ec7/src/stream_to.cxx#L27-L35

**Comment by jtv** [comment]
Right - this is one of those restrictions the documentation mentions.  It happens at a deeper level than libpqxx.

So in these situations you'll have to use a `pqxx::result`.

**Comment by jtv** [comment]
Nothing more to be said here, really...  It behaves as documented, and the restriction is outside of libpqxx.  I'll close the issue.
