### ISSUE TITLE
`stream_to` uses `quote_name` as 2 argument function

### ISSUE THREAD

**Issue by soro** [jtv/libpqxx#853]
https://github.com/jtv/libpqxx/blob/29bad0884ec24e0c517c1f33cc462260305a99b7/include/pqxx/stream_to.hxx#L484

causes this compile error:

```
bazel-out/k8-fastbuild/bin/external/com_github_jtv_libpqxx/pqxx/include/pqxx/stream_to.hxx:484:24: 
error: no matching function for call to 'pqxx::transaction_base::quote_name(std::string_view&, std::string)'
```

I do not see a two argument version defined - I assume this might have broken with the 7.9.x changes?

**Comment by jtv** [comment]
That does look like an obscure function that has escaped notice...  I don't know why you're getting the error but I never got one.  It's not a 7.9.x change.

What compiler is this, and did this happen while compiling libpqxx or some other code that _uses_ libpqxx?  It looks like either you're compiling some different code, perhaps because of conditional compilation or something.

**Comment by jtv** [comment]
Ah, I see (part of) what happened: this is a deprecated constructor.  Don't use it.  Use the `pqxx::stream_to::table()` named constructor (or `pqxx::stream_to::raw_table()` if you are so inclined).

I'll see if I can fix the function, but this bug seems to have been there for _years_ without anybody else complaining.  So I'm kind of inclined to just get rid of it.

**Comment by jtv** [comment]
Looked to be simply a closing parenthesis that was in the wrong place.  Have you got a test case that I can run against this?

**Comment by soro** [comment]
Nothing public or something I could easily share, but I can test it if you cut a release. I'll also update the code - looks like we hadn't updated the library version for a very long time.

**Comment by soro** [comment]
Applying this change, I ran into another compile issue because `*col` resolved to `const char`. That might be due to client code, or it might be real breakage - I decided to just fix the client code. Maybe it is indeed better to remove the function if it has been deprecated for a while.

**Comment by jtv** [comment]
Alright — I'll get rd of it.  It was always a bit weird and awkward anyway, passing a series of column names as a pair of iterators.  In C++20 we get better ways of doing that.
