### ISSUE TITLE
pqxx::string_traits<char> missing

### ISSUE THREAD

**Issue by leleftheriades** [jtv/libpqxx#98]
I can't figure out how to pass a char in a prepared statement.
Likewise how do I pass a date?

**Comment by KayEss** [comment]
For the date, you can convert to a string first.

For the char, if you want it in the database as a number then you can just turn it into an int. If you want it as a string then put it in a two byte buffer and send as a `char*`

**Comment by jtv** [comment]
@KayEss is correct.

I'd love to have dates, but they're messy.  There's conflicting formats (e.g. `01/12/2018` could be in December or in January, depending on the format), and timezones (which can be specified in various ways), and different precisions (days, seconds, milliseconds) and so on.  For now they're just strings.

The `char` overload was deliberately left out because it's too ambiguous.  It's not very obvious whether you want it as a number, or as an unsigned number, or as a character (and in which encoding?), or whether you meant to pass a string but accidentally iterated over it.

**Comment by egorpugin** [comment]
It's probably worth to consider https://github.com/HowardHinnant/date library which is included into C++20. String to date/time conversion functions are probably standard (in pg and this lib) as ISO stated them.
If user tricks with date/time in db - representing them in non standard forms - he could use own manual converters.

**Comment by jtv** [comment]
The conversions are exactly where the problem is though.  If the database sends `01/12/2018`, you need to know how _the server_ thinks dates should be formatted, or you can't parse it.  Once you have the information, the actual parsing is probably the easy part.  But I don't want libpqxx to query it for every connection  just on the off chance that it becomes necessary.  And by the time it becomes necessary, there may not be a database connection at all.  Also, there's no way at this moment to  pass state to string conversions.
