### ISSUE TITLE
Skip C Locale

### ISSUE THREAD

**Issue by Johannes76** [jtv/libpqxx#99]
Hi,

We use distributed database in several countries. We store state logs to the database. In case we read the float values back (which is transferred in string format). The following code segment consumes 99% of performance in stress tests:

template<typename T> inline void from_string_float(const char Str[], T &Obj)
…
      std::stringstream S(Str);
      S.imbue(std::locale("C"));
      ok = static_cast<bool>(S >> result);
…
As a temporary solution we take over the float conversions from the libpqxx without std::locale calls.
Our question is: what is the background of this problem, why is this conversion always executed?

**Comment by jtv** [comment]
Before I go further, I have no idea whether it makes any difference, but current versions of libpqxx say `std::locale::classic()` instead of `std::locale("C")`.  Could you have a try to see if that helps?  It looks like it would bypass the locale lookup by name, and that would save _some_ time.  Don't know how much.

Meanwhile, I'll experiment with `thread_local` to work with one static `stringstream` per thread.

**Comment by KayEss** [comment]
@jtv Maybe these functions will help to avoid the `stringstream` and the allocation that they do: http://en.cppreference.com/w/cpp/string/byte/strtof

**Comment by jtv** [comment]
Thanks, @KayEss!  Unfortunately, reading those docs, the `strtof` family _is_ locale sensitive.  It's easy to miss, but the description talks about _the current C locale,_ not (as we were hoping) _the “C” locale._  So in a way that may be worse than what we had.  It's a real shame because it looks as if these functions even handle NaNs and infinities the way I want them.

The `from_chars` family looks more suitable, although it's a bit more complex to use and still needs me to catch NaNs and infinities first.  I may add an alternative implementation for C++17, and then eventually switch over to that.  And in parallel, for older C++ versions, keep a `stringstream` with our custom settings wrapped in a `thread_local` object.

This kind of thing also makes me wonder if more of PostgreSQL shouldn't be exposed as libraries, so clients can re-use the same code that's in the database backend.

**Comment by jtv** [comment]
@Johannes76 what version of libpqxx are you using?  The code you show looks like it's from an older version, probably from before 5.1.1.  There was a change last year which should help with this problem.

**Comment by KayEss** [comment]
Is it for sure that the performance problem is setting the locale and not the memory allocation that the stringstream has to do?

**Comment by jtv** [comment]
I agree it's probably worth knowing where the performance problems really lie.

The `to_chars` and `from_chars` functions are a huge boon.  They do exactly what I need.  Once I can rely on those I'll be able to throw away almost the entire module, replacing almost all string conversions with those two calls plus some error checks.  But, we're not there yet.  :-(  I tried gcc 8 and clang 6 (with libc++), and neither of them fully implements the functions.

**Comment by jtv** [comment]
The issue was originally for an older libpqxx version which was less efficient here than current versions.  I've done some things that should help a bit; we'll be able to do more once those C++17 features are more widely implemented.  I'll close the issue for now, since we don't know that there is still a problem.
